"""Hand-drawn pixel sprites for the source-backed, playerless Mulgore atlas.

These are original atlas archetypes, not claims to reproduce individual 3D models.
Each MaNGOS spawn keeps its own coordinates and identity; the viewer selects a
recognizable sprite family from the creature/gameobject template name.
"""

from __future__ import annotations

from ..pixelart import art, grid, outline_grid
from ..registry import register


def _sprite(name: str, drawing: str, legend: dict[str, str], note: str = "Mulgore atlas sprite") -> None:
    pixels = outline_grid(grid(drawing))
    opaque = [(x, y) for y, row in enumerate(pixels) for x, char in enumerate(row) if char != "."]
    if not opaque:
        raise ValueError(f"{name}: sprite has no visible pixels")
    bottom = max(y for _, y in opaque)
    bottom_row = [x for x, y in opaque if y == bottom]
    anchor = ((min(bottom_row) + max(bottom_row)) // 2, bottom)
    register(name, art(pixels, legend=legend, note=note, anchor=anchor))


def _centered(width: int, *rows: str) -> str:
    """Lay out authored silhouette rows in a fixed-width transparent frame."""
    if any(len(row) > width for row in rows):
        raise ValueError(f"sprite drawing row exceeds its {width}px frame")
    return "\n".join(row.center(width, ".") for row in rows)


FUR = {"k": "ink", "b": "earth2", "B": "earth3", "t": "earth1", "h": "bone3",
       "H": "bone4", "e": "ink2", "r": "red2", "R": "red3", "l": "leather2",
       "L": "leather3", "g": "gold1", "G": "gold2", "w": "white", "s": "straw2",
       "S": "straw3", "o": "earth4", "O": "earth5", "m": "mesa2", "M": "mesa3",
       "v": "water3", "V": "water4", "f": "fire3", "F": "fire4", "x": "ink2",
       "y": "straw4", "Y": "straw5", "p": "prairie3", "P": "prairie4"}

_sprite("az.atlas.actor.tauren", """
    ................
    .......kk.......
    ......khhk......
    .....khbbhk.....
    ....khbbbbhk....
    ...kkbbbeebkk...
    ...kbbbbbbbk....
    ....kbbbbbk.....
    ...kkrRRrrkk....
    ..klrrRRrrrlk...
    ..klrrgGrrrlk...
    ...kllggllk.....
    ....kllllk......
    ....kllllk......
    ...kk....kk.....
    ...kLk..kLk.....
    ...kkk..kkk.....
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", FUR, "Mulgore tauren silhouette, 3/4 facing right")

_sprite("az.atlas.actor.humanoid", """
    ................
    .......kk.......
    ......ksssk.....
    .....kssssk.....
    .....kseesk.....
    .....ksssskk....
    ......kkkk......
    .....krrRrk.....
    ....krrRRrrk....
    ....krRgRRrk....
    ....klllllk.....
    ....klllllk.....
    .....klllk......
    .....k...k......
    ....kLk.kLk.....
    ....kkk.kkk.....
    ................
    ................
    ................
    ................
""", {**FUR, "s": "skin2", "e": "ink", "r": "leather2", "R": "red2",
      "g": "gold1", "L": "earth3"}, "Mulgore humanoid, 3/4 facing right")

_sprite("az.atlas.actor.wolf", """
    ................
    ................
    ..........k.....
    .........kKk....
    ...kkkkkkKkkk...
    ..kbbbBBbbbbk...
    .kbbBBbbbbeekkk.
    .kbbBbbbbBBbkk..
    ..kbbBbbbbbbkk..
    ...kkkbbbkkk....
    ......kbbk......
    .....kkb.kk.....
    .....kk..kk.....
    ................
    ................
    ................
""", {**FUR, "K": "ink2", "b": "grey2", "B": "grey3", "t": "grey1"},
      "Mulgore wolf, side profile")

_sprite("az.atlas.actor.boar", """
    ................
    ................
    ............kk..
    .......kkkkkBBk.
    ..kkkkkBBBBBBek.
    .kBBBbBBBBBBbkk.
    kbbBBbBBBBBk....
    kbbBBBBBBBBk....
    .kBBBBBBBkk.....
    ..kkbbbkk.......
    ...kbbk.........
    ..kk..kk........
    ................
    ................
    ................
    ................
""", {**FUR, "b": "earth2", "B": "earth4", "e": "ink2"}, "Mulgore boar")

_sprite("az.atlas.actor.strider", """
    ................
    ........kkkk....
    .......kYYYYk...
    ......kkYyYYk...
    .....kwwyyywkk..
    ......kkwwkk....
    .........kk.....
    .......kkk......
    ..kkkkkWWWkk....
    .kpppPPPPPpkk...
    .kppPPPPPPppk...
    ..kkkPkkPkkk....
    ....kk..kk......
    ...kk....kk.....
    ...kk....kk.....
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", {**FUR, "W": "white", "w": "white", "P": "prairie5", "p": "prairie3"},
      "Tallstrider with bright crest and long legs")

_sprite("az.atlas.actor.kodo", """
    ................................
    ................................
    .................kk.............
    ...............kkBBk............
    ..............kBBBBBk...........
    .............kBBBBBBbk..........
    ............kBBBBBBBBbk.........
    ...kkkkkkkkkBBBBBBBeebkkk.......
    ..kbbBBbbBBBBBBBBBBBBBkk........
    .kbbbbbBBBBBBBBBBBBBBBbk........
    kbbbbbBBBBBBBBBBBBBBBBbk........
    kbbbbbBBBBBBBBBBBBBBBBk.........
    .kbbbbBBBBBBBBBBBBBBkk..........
    ..kkkkkBBBBBBBkkkBBk............
    ......kBBBBBk..kBBk.............
    ......kBBBBBk..kBBk.............
    ......kk...kk..kk.kk............
    ......kk...kk..kk.kk............
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
""", {**FUR, "b": "earth1", "B": "earth3", "t": "earth2", "e": "ink"},
      "Large kodo, 32 by 24 pixels")

_sprite("az.atlas.actor.bird", """
    ................
    ................
    .........kk.....
    ........kBBkk...
    .......kBBBBek..
    ......kBBBBBBk..
    ...kkkBBBBBkk...
    ..kwwkBBbkk.....
    ..kkkkbbbkk.....
    .....kbbbkk.....
    ......kkk.......
    ......k.k.......
    .....kk.kk......
    ................
    ................
    ................
""", {**FUR, "b": "earth2", "B": "earth4", "w": "straw4", "e": "ink"}, "Plains bird")

_sprite("az.atlas.actor.snake", """
    ............
    ......kkkk..
    .....kBBek..
    ....kBBBBk..
    ..kkkBBBkk..
    .kbbkBBkk...
    .kbbkBBk....
    ..kkbbbkk...
    ...kkBBbkk..
    .....kBBBk..
    ......kkk...
    ............
""", {**FUR, "b": "straw3", "B": "straw4", "e": "red3"}, "Adder, coiled profile")

_sprite("az.atlas.actor.critter", """
    ............
    ....kkkk....
    ...kbbbek...
    ..kbbbbbbk..
    .kbbbbbbbkk.
    .kkbbbbkkk..
    ...k..k.....
    ..kk..kk....
    ............
    ............
    ............
    ............
""", {**FUR, "b": "earth2", "e": "ink"}, "Small Mulgore critter")

_sprite("az.atlas.actor.spirit", """
    ................
    .......kk.......
    ......kVVk......
    .....kVVVVk.....
    .....kVwVVVk....
    .....kVVVVVk....
    ......kkkkk.....
    .....kVVVVVk....
    ....kVVVVVVVk...
    ....kVVVVVVVkk..
    ....kVVVvVVVkk..
    .....kVVVVVk....
    ......kVVVk.....
    .......kkk......
    ......k...k.....
    .....kk...kk....
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", {**FUR, "V": "water3", "v": "water4", "w": "white", "e": "glowcyan"},
      "Ghostly Mulgore spirit")

_sprite("az.atlas.actor.quilboar", """
    ................
    .......kk.......
    ......kHHHk.....
    .....kHbbbbk....
    ....kbbbbeek....
    ...kbbbbbbkk....
    ...kbbRRbbk.....
    ....kRRRrk......
    ....krrRrk......
    .....kllk.......
    ....kk..kk......
    ....kk..kk......
    ................
    ................
    ................
    ................
""", {**FUR, "b": "earth2", "H": "bone3", "h": "bone4", "e": "ink", "R": "red2",
      "r": "leather2", "l": "earth3"}, "Quilboar, small tusked biped")


OBJ = {"k": "ink", "w": "bone3", "W": "bone4", "b": "earth2", "B": "earth3", "t": "earth1",
       "T": "earth4", "r": "red2", "R": "red3", "g": "prairie2", "G": "prairie4",
       "y": "gold2", "Y": "gold3", "f": "fire3", "F": "fire4", "o": "mesa2", "O": "mesa4",
       "s": "straw2", "S": "straw4", "v": "water3", "V": "water4", "m": "rock2", "M": "rock4"}

_sprite("az.atlas.object.herb", """
    ................
    .......yy.......
    ......yYYy......
    .......yy.......
    .......gg.......
    .....gggggg.....
    ....gGggggGg....
    ......ggggg.....
    .......ggg......
    ......gg.gg.....
    .....gg..ggg....
    ....gg....gg....
    ................
    ................
    ................
    ................
""", OBJ, "Gatherable prairie flower")

_sprite("az.atlas.object.ore", """
    ................
    .......kk.......
    ......kMMk......
    .....kMwwMk.....
    ....kMmwwmMk....
    ...kMmmMMmmMk...
    ..kmmmmmmmmmmk..
    .kmmMmmmmMmmmk..
    .kkkkkkkkkkkkk..
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Copper or other ore vein")

_sprite("az.atlas.object.fire", """
    ................
    ........f.......
    .......fFf......
    ......fFFFf.....
    .......fYf......
    ......fffff.....
    .....kbbbbbk....
    ....kbtTtbbbk...
    ...kbbbbbbbbbk..
    ...kkkkkkkkkkk..
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Fire and brazier archetype")

_sprite("az.atlas.object.chest", """
    ................
    ................
    .....kkkkkk.....
    ....kTTTTTTk....
    ...kTTTyTTTTk...
    ..kBBBBBBBBBBk..
    ..kBtBBBBBtBBk..
    ..kBBBBwBBBBBk..
    ..kBBBBBBBBBBk..
    ..kkkkkkkkkkkk..
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Wooden supply chest")

_sprite("az.atlas.object.crate", """
    ................
    ................
    ...kkkkkkkkkk...
    ..kBBBBBBBBBBk..
    ..kBttttttttBk..
    ..kBtBBBBBBtBk..
    ..kBtBBBBBBtBk..
    ..kBtBBBBBBtBk..
    ..kBttttttttBk..
    ...kkkkkkkkkk...
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Rough wood supply crate")

_sprite("az.atlas.object.barrel", """
    ................
    .....kkkkkk.....
    ....kBBBBBBk....
    ...kBTTTTTTBk...
    ...kBBBBBBBBk...
    ...kBtBBBBtBk...
    ...kBBBBBBBBk...
    ...kBTTTTTTBk...
    ....kBBBBBBk....
    .....kkkkkk.....
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Wood barrel")

_sprite("az.atlas.object.totem", """
    ................
    .......kk.......
    ......kRRk......
    .....kRyyRk.....
    ....kRRyyRRk....
    .....kRrrRk.....
    ....kRRrrRRk....
    ....kRRyyRRk....
    .....kRrrRk.....
    ......kRRk......
    ......krrk......
    ......krrk......
    .....kk..kk.....
    .....kkkkkk.....
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Carved tauren totem pole")

_sprite("az.atlas.object.well", """
    ................
    ....kkkkkkkk....
    ...kBBBBBBBBk...
    ...kBkkkkkkBk...
    ...kBkVVVVkBk...
    ...kBkVVVVkBk...
    ...kBkkkkkkBk...
    ...kBBBBBBBBk...
    ....kBBBBBBk....
    .....kBBBBk.....
    ......kkkk......
    .......kk.......
    .......kk.......
    ......kkkk......
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Stone-lined prairie well")

_sprite("az.atlas.object.tent", _centered(32,
    "." * 32,
    "kk", "kTTk", "kTTtTk", "kTTttTTk", "kTTtyTTTk", "kTTRrrTTTk", "kTTRRRrrTTTk",
    "kTRRRRyyRRRRk", "kTRRRRryyRRRRRk", "kTRRRRRrrRRRRRRk", "kTRRRRRRrrRRRRRRRk",
    "kTRRRRRRRRRRRRRRRTk", "kTTYYYYYYYYYYYYYYYYYYYYYYYYTk",
    "kTRRRRRkkbbkkRRRRRRRk", "kTRRRRRkbbbbkRRRRRRRk", "kTRRRRRkbttbkRRRRRRRk",
    "kTRRRRRkbtTbkRRRRRRRk", "kTRRRRRkbtTbkRRRRRRRk", "kTRRRRRkbbbbkRRRRRRRk",
    "kTRRRRRkkbbkkRRRRRRRk", "kTTRRRRRRRRRRRRRRRRRRRRTTk",
    "kTTttttttttttttttttttTTk", "kkTTttttttttttttttTTkk",
    "..kkTTTTTTTTTTTTTTkk..", "....kkkkkkkkkkkk....", "." * 32, "." * 32,
), OBJ, "Hide-and-timber tauren tent with stitched canopy, dark doorway and guy ropes")

_sprite("az.atlas.object.hut", _centered(40,
    "." * 40,
    "kk", "kTTk", "kTTtTk", "kTTttTTk", "kTTtyTTTk", "kTTtTTtTTk", "kTTTTtTTTTk",
    "kTTTTTtTTTTTk", "kTTTTTTtTTTTTTk", "kTTTTTTTtTTTTTTTk", "kTTTTTTTTtTTTTTTTTk",
    "kTTTTTTTTTTtTTTTTTTTTTk", "kTTTTTTTTTTTTtTTTTTTTTTTTTk",
    "kTTTTTTTTTTTTTTtTTTTTTTTTTTTTTk", "kTTTYYTTTYYTTTYYTTTYYTTTYYTTTk",
    "kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk",
    "kBBttBBBBttBBBBBBBBBBBBttBBBBttBBBBBk", "kBBtvvBBttBBBBBBBBBBBBttBBvvBBttBBBBk",
    "kBBtvvBBttBBBBBBkkBBBBBttBBvvBBttBBBBk",
    "kBBttBBBBttBBBBkbbkBBBttBBBBttBBBBBk",
    "kBBttBBBBttBBBBkbbkBBBttBBBBttBBBBBk",
    "kBBttBBBBttBBBBkbbkBBBttBBBBttBBBBBk",
    "kBBttBBBBttBBBBkbbkBBBttBBBBttBBBBBk",
    "kBBttBBBBttBBBBkbbkBBBttBBBBttBBBBBk",
    "kBBttBBBBttBBBBkbbbbBkBBBBttBBBBttBBBk",
    "kBBttBBBBttBBBBkkkkkkBBBBBttBBBBttBBBk",
    "kkBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBkk",
    "..kktttBBtttBBBBBBBBBBBBBtttBBtttkk..",
    "....kkkkkkkkkkkkkkkkkkkkkkkkkkkk....", "." * 40, "." * 40,
), {**OBJ, "T": "tent2", "t": "tent1"},
   "Tauren timber-and-hide longhouse with roof seams, beams, windows, door and entry steps")

_sprite("az.atlas.object.stone", """
    ................
    ................
    .......kk.......
    ......kMMk......
    .....kMMMMk.....
    ....kMmMMMmMk...
    ...kMMMMMMMMk...
    ..kMMmMMMMMMMk..
    ..kMMMMMMMMMMk..
    ...kkkkkkkkkk...
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Mulgore stone or boulder")

_sprite("az.atlas.object.banner", """
    ................
    .........kk.....
    .........kTk....
    .........kTk....
    .........kTk....
    .........kRkkk..
    .........kRRRk..
    .........kRRRkk.
    .........kRRRk..
    .........kRRRkk.
    .........kRkkk..
    .........kTk....
    .........kTk....
    .........kTk....
    .......kkkTkkk..
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Horde banner on a carved pole")

_sprite("az.atlas.object.mailbox", """
    ................
    ................
    .....kkkkkk.....
    ....kRRRRRRk....
    ...kRRRRRRRRk...
    ...kRwwwwwwRk...
    ...kRRRRRRRRk...
    ....kkkkkkkk....
    ......kTTk......
    ......kTTk......
    .....kkTTkk.....
    ................
    ................
    ................
    ................
    ................
""", OBJ, "Red Horde mailbox")

_sprite("az.atlas.object.plant", """
    ................
    ........gg......
    ......ggGGg.....
    .....gGGggg.....
    ....gGGGggg.....
    .....ggggGg.....
    ......ggggg.....
    .......gggg.....
    ......ggg.gg....
    .....ggg..gg....
    ....ggg....gg...
    ...ggg......gg..
    ................
    ................
    ................
    ................
""", OBJ, "Wild prairie herb")

_sprite("az.atlas.object.generic", """
    ................
    .......kk.......
    ......kTTTk.....
    .....kTBBBTk....
    ....kTBBBBBTk...
    ....kBBBBBBBk...
    ....kBttttBBk...
    ....kBBBBBBBk...
    .....kBBBBBk....
    ......kkkkk.....
    ........kk......
    .......kkkk.....
    ................
    ................
    ................
    ................
""", OBJ, "Generic Mulgore placed prop")
