"""Azeroth / Mulgore art: creatures. Must satisfy
``wilds.azeroth.manifest.required()["creatures"]`` (see docs/azeroth/mulgore-art-manifest.md).

The beasts and critters of the plains, at real scale (1 tile = 16 px = 2 yards): critters fit
12x12, small beasts 16x16, a tallstrider stands 16x24 and a kodo is two tiles long (32x24).
Every animal faces RIGHT in a 3/4 side view with its feet (and their 1px ink outline) on the
bottom row. Families share one body: wolf/timber wolf, cougar/lion/mountain lion,
vulture/eagle. Bodies are hand-drawn fill grids; legs are posed polylines stamped under
them, so a walk cycle only moves limbs and bobs the body by 1px (no sliding); the ink
outline is added last around the whole silhouette.
"""

from __future__ import annotations

from ..palette import _ramp
from ..pixelart import Grid, art, grid, outline_grid, overlay, shift
from ..procgen import Canvas
from ..registry import register

# --- colours --------------------------------------------------------------------------
# A neutral warm fur brown (wolves, dog, rabbit) and the kodo's slate hide: the master
# palette has no mid, unsaturated animal browns.
_ramp("azc_fur", "#2e2119", "#4d3a2c", "#735a43", "#9a7f5f", "#c2a883", "#e3d1b0")
_ramp("azc_kodo", "#25222b", "#3b3640", "#56504f", "#776e69", "#9a8f85", "#bdb3a6")


# --- helpers ------------------------------------------------------------------------------

Leg = tuple[str, tuple[tuple[int, int], ...], int, int, str]


def L(ch: str, *pts: tuple[int, int], paw: int = 1, w: int = 1, foot: str = "") -> Leg:
    """A leg: a polyline hip -> ... -> foot in colour ``ch``, ``w`` px thick (growing to the
    right); ``paw`` adds that many pixels in front of the foot (0: lifted or a hoof);
    ``foot`` recolours the last row (hooves)."""
    return ch, pts, paw, w, foot


def fore(ch: str, hx: int, hy: int, off: int = 0, lift: bool = False, ground: int = 14,
         w: int = 1, paw: int = 1, foot: str = "") -> Leg:
    """A foreleg hanging from the shoulder (hx, hy): planted ``off`` px ahead, or lifted
    and folded back under the chest."""
    if lift:
        return L(ch, (hx, hy), (hx, ground - 2), (hx - 1, ground - 1), paw=0, w=w, foot=foot)
    return L(ch, (hx, hy), (hx + off // 2, ground - 2), (hx + off, ground), paw=paw, w=w, foot=foot)


def hind(ch: str, hx: int, hy: int, off: int = 0, lift: bool = False, ground: int = 14,
         w: int = 1, paw: int = 1, foot: str = "") -> Leg:
    """A hind leg from the hip (hx, hy) with the hock bent backwards: planted ``off`` px
    ahead, or lifted with the foot drawn up."""
    if lift:
        return L(ch, (hx, hy), (hx - 1, ground - 2), (hx, ground - 1), paw=0, w=w, foot=foot)
    return L(ch, (hx, hy), (hx - 1 + off // 2, ground - 2), (hx + off, ground), paw=paw, w=w,
             foot=foot)


def _pose(w: int, h: int, body: Grid, legs: tuple[Leg, ...] = (), dx: int = 0, dy: int = 0,
          top: tuple[tuple[Grid, int, int], ...] = ()) -> Grid:
    """Legs first (the body covers their tops), then the body shifted by (dx, dy), then
    ``top`` parts, then the ink outline around everything."""
    c = Canvas(w, h)
    for ch, pts, paw, lw, foot in legs:
        for k in range(lw):
            if len(pts) == 1:
                c.set(pts[0][0] + k, pts[0][1], ch)
            for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
                c.line(x0 + k, y0, x1 + k, y1, ch)
        fx, fy = pts[-1]
        for k in range(lw, lw + paw):
            c.set(fx + k, fy, ch)
        if foot:
            for k in range(lw + paw):
                c.set(fx + k, fy, foot)
    c.blit(shift(body, dx, dy))
    for part, x, y in top:
        c.blit(part, x, y)
    return outline_grid(c.grid(), "k")


def _ol(text: str) -> Grid:
    return outline_grid(grid(text), "k")


def _shadow(g: Grid, x0: int, x1: int, y: int, rows: int = 2) -> Grid:
    """A short soft ground shadow ('S', translucent ink) under a sprite, painted only on
    transparent pixels: ``rows`` rows from ``y`` down, spanning x0..x1 (ends rounded)."""
    out = [list(r) for r in g]
    for k in range(rows):
        inset = (rows - 1 - k) if k < rows - 1 else 0
        yy = y + k
        if not 0 <= yy < len(g):
            continue
        for x in range(x0 + inset + (k == rows - 1), x1 - inset - (k == rows - 1) + 1):
            if 0 <= x < len(g[0]) and out[yy][x] == ".":
                out[yy][x] = "S"
    return tuple("".join(r) for r in out)


def _fallen(body: Grid, legs: tuple[Leg, ...], x0: int, x1: int) -> Grid:
    """A dead beast on its side: legs stiff out toward the viewer, a soft shadow beneath."""
    w, h = len(body[0]), len(body)
    return _shadow(_pose(w, h, body, legs), x0, x1, h - 2)


def _reg(name: str, frames, legend: dict, fps: float = 0.0, note: str = "") -> None:
    register(f"az.creature.{name}", art(*frames, legend={"S": "ink:60", **legend}, fps=fps, note=note))


# ==========================================================================================
# Felines: cougar (sandy tan), mountain lion (red-brown puma), lion (golden, dark mane).
# One lean long-tailed cat body; the lion adds a mane and a tail tuft.
# ==========================================================================================

CAT_BODY = grid("""
    ................
    ................
    ................
    ................
    ..........t..t..
    ..........3443..
    .........334443.
    .........333e3n.
    ..44444443333bb.
    .23333333332b...
    .2.22BBBBB22....
    .2..............
    ..t.............
    ................
    ................
    ................
""")
# idle: an ear flicks back and the tail tip uncurls
CAT_BODY_B = grid("""
    ................
    ................
    ................
    ................
    ...........t.t..
    ..........3443..
    .........334443.
    .........333e3n.
    ..44444443333bb.
    .23333333332b...
    .2.22BBBBB22....
    .2..............
    .t..............
    ................
    ................
    ................
""")
# pounce: body up in the air, ears flat, jaws open, tail streaming out behind
CAT_LUNGE = grid("""
    ................
    ................
    ................
    ...........tt...
    ..........3443..
    .........334443.
    .........333e3n.
    .t24444444333m..
    ..3333333333bbb.
    ...22BBBBB22....
    ................
    ................
    ................
    ................
    ................
    ................
""")
# fallen on its side: back to the sky, legs stiff toward the viewer, head down on the ground
CAT_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...BBBBBBB......
    ..233333333..tt.
    .23333333333444.
    t2333333333x33n.
    .t.2222222.bbb..
    ................
    ................
""")
# rolled onto its side, back to the viewer, legs stiff out over the belly
CAT_DEAD_LEGS = (L("2", (4, 9), (2, 6), paw=0), L("2", (10, 9), (11, 6), paw=0),
                 L("3", (5, 9), (3, 6), (3, 5), paw=0), L("3", (9, 9), (10, 6), (10, 5), paw=0))


def _cat_legs(off: tuple[int, int, int, int], lift: tuple[bool, ...] = (False,) * 4,
              hy: int = 10) -> tuple[Leg, ...]:
    """Far hind, far fore, near hind, near fore: each pair side by side, so a standing cat
    shows two clean 2px legs and a walking one splits them into a clear stride."""
    return (hind("2", 5, hy, off[0], lift[0], paw=0), fore("2", 9, hy, off[1], lift[1], paw=0),
            hind("3", 4, hy, off[2], lift[2]), fore("3", 10, hy, off[3], lift[3]))


_F, _T = False, True
# walk: near pair spread / far pair gathered, then the reverse; lifted legs on the passing frames
WALK = ((1, -1, -2, 2), (0, 0, 0, 0), (-2, 2, 1, -1), (0, 0, 0, 0))
WALK_LIFT = ((_F,) * 4, (_F, _T, _T, _F), (_F,) * 4, (_T, _F, _F, _T))


def _cat_set(body: Grid, body_b: Grid, lunge: Grid, dead: Grid) -> dict[str, list[Grid]]:
    return {
        "idle": [_pose(16, 16, body, _cat_legs((0, 0, 0, 0))),
                 _pose(16, 16, body_b, _cat_legs((0, 0, 0, 0)))],
        "move": [_pose(16, 16, body, _cat_legs(off, lift, hy=10 - (k % 2)), dy=-(k % 2))
                 for k, (off, lift) in enumerate(zip(WALK, WALK_LIFT))],
        "attack": [
            # coiled low, weight on the haunches
            _pose(16, 16, body_b, (L("2", (4, 11), (5, 14), paw=0), L("2", (8, 11), (9, 14), paw=0),
                                   L("3", (3, 11), (2, 13), (3, 14)), L("3", (9, 11), (10, 14))),
                  dx=-1, dy=1),
            # the pounce: forepaws thrown out claws first, hind legs kicking off
            _pose(16, 16, lunge, (L("2", (5, 9), (3, 12), (2, 14), paw=0),
                                  L("2", (9, 9), (11, 11), (12, 12), paw=0),
                                  L("3", (4, 9), (2, 11), (1, 13), paw=0),
                                  L("3", (10, 9), (12, 10), (14, 11), paw=0))),
        ],
        "dead": [_fallen(dead, CAT_DEAD_LEGS, 2, 13)],
    }


# the lion's dark shaggy mane, laid over the cat's neck (dy -1 for the pounce)
MANE = grid("""
    .NN...
    NNN...
    MNNN..
    MNNNN.
    .MNNN.
    ..MMN.
    ...M..
""")
MANE_DEAD = grid("""
    .NN
    NNN
    MNN
    .MN
""")


def _cats() -> None:
    cougar = {"1": "sand1", "2": "sand2", "3": "sand3", "4": "sand4", "b": "bone4", "B": "bone3",
              "t": "sand0", "n": "skin2", "m": "red1", "e": "ink2", "x": "ink2"}
    mountain = {**cougar, "1": "rust0", "2": "rust2", "3": "rust3", "4": "rust4", "B": "sand3",
                "b": "sand4", "t": "leather1"}
    lion = {**cougar, "1": "tent0", "2": "tent1", "3": "tent2", "4": "tent3", "b": "tent4",
            "B": "tent3", "t": "rust1", "M": "rust1", "N": "rust2"}
    cat = _cat_set(CAT_BODY, CAT_BODY_B, CAT_LUNGE, CAT_DEAD)
    maned = _cat_set(overlay(CAT_BODY, MANE, 7, 4), overlay(CAT_BODY_B, MANE, 7, 4),
                     overlay(CAT_LUNGE, MANE, 7, 3), overlay(CAT_DEAD, MANE_DEAD, 9, 10))
    for name, legend, frames, what in (
            ("cougar", cougar, cat, "tawny cougar"),
            ("mountain_lion", mountain, cat, "red-brown puma with dark ear and tail tips"),
            ("lion", lion, maned, "golden savannah lion with a dark mane")):
        _reg(f"{name}.idle", frames["idle"], legend, 2, f"{what}, tail flick")
        _reg(f"{name}.move", frames["move"], legend, 8, f"{what} prowl")
        _reg(f"{name}.attack", frames["attack"], legend, 8, f"{what}: crouch, pounce")
        _reg(f"{name}.dead", frames["dead"], legend, 0, f"{what}, dead")


_cats()


# ==========================================================================================
# Canines: prairie wolf (warm grey-brown, the plains wolves) and timber wolf (cool grey).
# Taller than the cats: upright ears, long muzzle, pale throat ruff, bushy hanging tail.
# ==========================================================================================

WOLF_BODY = grid("""
    ................
    ................
    ..........3.3...
    ..........4443..
    .........443e3n.
    .........3333bb.
    ..444444433b....
    .3333333333b....
    .3234333322.....
    .2..2BBBB2......
    .t..............
    ................
    ................
    ................
    ................
    ................
""")
# panting: tongue out, tail swings
WOLF_BODY_B = grid("""
    ................
    ................
    ..........3.3...
    ..........4443..
    .........443e3n.
    .........3333b..
    ..444444433b.m..
    .3333333333b....
    .3234333322.....
    ..2.2BBBB2......
    ..t.............
    ................
    ................
    ................
    ................
    ................
""")
# lunge-bite: head thrust forward, ears pinned, jaws gaping
WOLF_LUNGE = grid("""
    ................
    ................
    ................
    ...........33...
    ..........4443..
    .........443e3n.
    ..t......3333m..
    ...24444433bbbb.
    ...333333333b...
    ...34333322.....
    ....2BBBB2......
    ................
    ................
    ................
    ................
    ................
""")
WOLF_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...BBBBBBB......
    ..233333333..tt.
    .23333333333444.
    33233333333x33n.
    t2..2222222bbb..
    ................
    ................
""")
WOLF_DEAD_LEGS = (L("2", (4, 9), (2, 5), paw=0), L("2", (10, 9), (12, 5), paw=0),
                  L("3", (5, 9), (3, 5), (3, 4), paw=0), L("3", (9, 9), (11, 5), (11, 4), paw=0))


def _wolf_legs(off: tuple[int, int, int, int], lift: tuple[bool, ...] = (False,) * 4,
               hy: int = 9) -> tuple[Leg, ...]:
    """Far hind, far fore, near hind, near fore, each pair side by side."""
    return (hind("2", 5, hy, off[0], lift[0], paw=0), fore("2", 8, hy, off[1], lift[1], paw=0),
            hind("3", 4, hy, off[2], lift[2]), fore("3", 9, hy, off[3], lift[3]))


WOLF = {
    "idle": [_pose(16, 16, WOLF_BODY, _wolf_legs((0, 0, 0, 0))),
             _pose(16, 16, WOLF_BODY_B, _wolf_legs((0, 0, 0, 0)))],
    "move": [_pose(16, 16, WOLF_BODY, _wolf_legs(off, lift, hy=9 - (k % 2)), dy=-(k % 2))
             for k, (off, lift) in enumerate(zip(WALK, WALK_LIFT))],
    "attack": [
        # hackles up, head low, braced to spring
        _pose(16, 16, WOLF_BODY_B, (L("2", (4, 11), (5, 14), paw=0), L("2", (7, 11), (8, 14), paw=0),
                                    L("3", (3, 11), (2, 13), (3, 14)), L("3", (8, 11), (9, 14))),
              dx=-1, dy=2),
        # the lunge: forelegs reaching, hind legs driving off the ground
        _pose(16, 16, WOLF_LUNGE, (L("2", (6, 10), (4, 12), (3, 14), paw=0),
                                   L("2", (9, 10), (11, 12), (12, 13), paw=0),
                                   L("3", (5, 10), (3, 12), (2, 14), paw=1),
                                   L("3", (10, 10), (12, 11), (13, 12), paw=0))),
    ],
    "dead": [_fallen(WOLF_DEAD, WOLF_DEAD_LEGS, 2, 13)],
}


def _wolves() -> None:
    wolf = {"1": "azc_fur1", "2": "azc_fur2", "3": "azc_fur3", "4": "azc_fur4", "b": "azc_fur5",
            "B": "azc_fur4", "t": "azc_fur1", "n": "ink2", "m": "blush", "e": "ink2", "x": "ink2"}
    timber = {**wolf, "1": "grey0", "2": "grey1", "3": "grey2", "4": "grey3", "b": "grey4",
              "B": "grey3", "t": "grey0"}
    for name, legend, what, attack in (("wolf", wolf, "prairie wolf", True),
                                       ("timber_wolf", timber, "grey timber wolf", False)):
        _reg(f"{name}.idle", WOLF["idle"], legend, 2, f"{what}, panting")
        _reg(f"{name}.move", WOLF["move"], legend, 8, f"{what} lope")
        if attack:
            _reg(f"{name}.attack", WOLF["attack"], legend, 8, f"{what}: crouch, lunge-bite")
        _reg(f"{name}.dead", WOLF["dead"], legend, 0, f"{what}, dead")


_wolves()


# ==========================================================================================
# Boar: the battleboars of Red Cloud Mesa. A low barrel of dark red-brown hide, a bristly
# black mane over high shoulders, a pink snout disc and curved ivory tusks.
# ==========================================================================================

BOAR_BODY = grid("""
    ................
    ................
    ................
    .....N.N........
    ...NNMNMNN......
    ..4444MMMMt.....
    .43333333M44....
    .333333333e344..
    .3333333333334n.
    .23333333333wnn.
    .2222222222w....
    ..2111112.......
    ................
    ................
    ................
    ................
""")
# snuffling: ear pricks up, snout twitches
BOAR_BODY_B = grid("""
    ................
    ................
    ................
    .....N.N..t.....
    ...NNMNMNNt.....
    ..4444MMMM......
    .43333333M44....
    .333333333e344..
    .33333333333334.
    .23333333333wnn.
    .2222222222w.nn.
    ..2111112.......
    ................
    ................
    ................
    ................
""")
BOAR_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...11111111.....
    ..2333333333.t..
    .2333333333344n.
    .333333333x3wnn.
    ..NMNMNMNM.2w...
    ................
    ................
""")
BOAR_DEAD_LEGS = (L("2", (4, 9), (3, 7), paw=0, foot="h"), L("2", (10, 9), (11, 7), paw=0, foot="h"),
                  L("3", (5, 9), (4, 6), paw=0, foot="h"), L("3", (9, 9), (10, 6), paw=0, foot="h"))


def _boar_legs(off: tuple[int, int, int, int], lift: tuple[bool, ...] = (False,) * 4,
               hy: int = 11) -> tuple[Leg, ...]:
    return (hind("2", 4, hy, off[0], lift[0], paw=0, foot="h"),
            fore("2", 7, hy, off[1], lift[1], paw=0, foot="h"),
            hind("3", 2, hy, off[2], lift[2], paw=0, foot="h"),
            fore("3", 9, hy, off[3], lift[3], paw=0, foot="h"))


BOAR = {
    "idle": [_pose(16, 16, BOAR_BODY, _boar_legs((0, 0, 0, 0))),
             _pose(16, 16, BOAR_BODY_B, _boar_legs((0, 0, 0, 0)))],
    "move": [
        _pose(16, 16, BOAR_BODY, _boar_legs((-1, -1, 1, 1))),
        _pose(16, 16, BOAR_BODY, _boar_legs((0, 0, 0, 0), (_F, _T, _T, _F), hy=10), dy=-1),
        _pose(16, 16, BOAR_BODY, _boar_legs((1, 1, -1, -1))),
        _pose(16, 16, BOAR_BODY, _boar_legs((0, 0, 0, 0), (_T, _F, _F, _T), hy=10), dy=-1),
    ],
    "attack": [
        # head down, hind legs dug in
        _pose(16, 16, BOAR_BODY_B, (L("2", (3, 12), (3, 14), paw=0, foot="h"),
                                    L("2", (6, 12), (7, 14), paw=0, foot="h"),
                                    L("3", (1, 12), (1, 14), paw=0, foot="h"),
                                    L("3", (8, 12), (9, 14), paw=0, foot="h")), dx=-1, dy=1),
        # the charge: rammed forward tusks first, legs flung out
        _pose(16, 16, BOAR_BODY, (L("2", (4, 9), (3, 11), (2, 13), paw=0, foot="h"),
                                  L("2", (7, 9), (9, 11), (10, 12), paw=0, foot="h"),
                                  L("3", (2, 9), (1, 11), (1, 12), paw=0, foot="h"),
                                  L("3", (9, 9), (11, 10), (12, 11), paw=0, foot="h")),
              dy=-2),
    ],
    "dead": [_fallen(BOAR_DEAD, BOAR_DEAD_LEGS, 2, 13)],
}


def _boar() -> None:
    legend = {"1": "rust0", "2": "rust1", "3": "rust2", "4": "rust3", "M": "leather1",
              "N": "leather3", "t": "rust1", "e": "ink2", "n": "skin3", "o": "skin1",
              "w": "bone4", "h": "leather1", "x": "ink2"}
    _reg("boar.idle", BOAR["idle"], legend, 2, "battleboar, snuffling")
    _reg("boar.move", BOAR["move"], legend, 10, "battleboar trot")
    _reg("boar.attack", BOAR["attack"], legend, 8, "battleboar: head down, tusk charge")
    _reg("boar.dead", BOAR["dead"], legend, 0, "battleboar, dead")


_boar()


# ==========================================================================================
# Gazelle: small and slender, sandy back, dark flank stripe, white belly and chin, thin
# legs on black hooves, ringed lyre horns sweeping back.
# ==========================================================================================

GAZELLE_BODY = grid("""
    ...........H....
    ..........H.....
    ..........H.....
    .........r.H....
    ..........3444..
    ..........3e44n.
    .........333bb..
    .........33b....
    ..t44444433b....
    ..t3DDDDD33b....
    ...bbbbbbbb.....
    ................
    ................
    ................
    ................
    ................
""")
# ear and tail flick
GAZELLE_BODY_B = grid("""
    ...........H....
    ..........H.....
    .........rH.....
    ...........H....
    ..........3444..
    ..........3e44n.
    .........333bb..
    .........33b....
    ...44444433b....
    .tt3DDDDD33b....
    ...bbbbbbbb.....
    ................
    ................
    ................
    ................
    ................
""")
GAZELLE_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...bbbbbbb......
    ..3DDDDDDD3HH...
    .t4444444443r44.
    ..3333333333x3n.
    ...2222222..bb..
    ................
    ................
""")
GAZELLE_DEAD_LEGS = (L("2", (4, 9), (2, 5), paw=0, foot="h"), L("2", (9, 9), (11, 5), paw=0, foot="h"),
                     L("3", (5, 9), (3, 4), paw=0, foot="h"), L("3", (8, 9), (10, 4), paw=0, foot="h"))


def _gazelle_legs(off: tuple[int, int, int, int], lift: tuple[bool, ...] = (False,) * 4,
                  hy: int = 10) -> tuple[Leg, ...]:
    return (hind("2", 5, hy, off[0], lift[0], paw=0, foot="h"),
            fore("2", 8, hy, off[1], lift[1], paw=0, foot="h"),
            hind("3", 4, hy, off[2], lift[2], paw=0, foot="h"),
            fore("3", 10, hy, off[3], lift[3], paw=0, foot="h"))


def _gazelle() -> None:
    legend = {"2": "sand2", "3": "sand3", "4": "sand4", "D": "azc_fur1", "b": "bone4", "x": "ink2",
              "h": "leather1", "t": "leather2", "e": "ink2", "n": "leather2",
              "H": "bone1", "r": "sand2"}
    b = GAZELLE_BODY
    idle = [_pose(16, 16, b, _gazelle_legs((0, 0, 0, 0))),
            _pose(16, 16, GAZELLE_BODY_B, _gazelle_legs((0, 0, 0, 0)))]
    move = [  # a light springing trot: long reach, body lifted on the passing frames
        _pose(16, 16, b, _gazelle_legs((-2, -2, 2, 2))),
        _pose(16, 16, b, _gazelle_legs((0, 0, 0, 0), (_F, _T, _T, _F), hy=9), dy=-1),
        _pose(16, 16, b, _gazelle_legs((2, 2, -2, -2))),
        _pose(16, 16, b, _gazelle_legs((0, 0, 0, 0), (_T, _F, _F, _T), hy=9), dy=-1),
    ]
    _reg("gazelle.idle", idle, legend, 2, "gazelle, ear and tail flick")
    _reg("gazelle.move", move, legend, 10, "gazelle springing trot")
    _reg("gazelle.dead", [_fallen(GAZELLE_DEAD, GAZELLE_DEAD_LEGS, 2, 13)], legend, 0, "gazelle, dead")


_gazelle()


# ==========================================================================================
# Tallstrider (plainstrider): a tall flightless bird. Round grey-brown body with a folded
# slate wing and blue tail plumes, a long neck, a heavy hooked beak under a bony crest,
# a red wattle, and long tan legs that bend backwards at the ankle.
# ==========================================================================================

STRIDER_HEAD = grid("""
    .cc...
    c4443.
    344e3B
    3333BB
    .2r.B.
""")
STRIDER_PECK_HEAD = grid("""
    .cc...
    c4443.
    344e3B
    3333mB
    .2r3BB
""")
STRIDER_BODY = grid("""
    .F..............
    .FF..444443.....
    ..F344444433....
    ..F3WWWWW3333...
    ...23WWWW3332...
    ...2222222222...
    ....11111111....
""")


def _strider(head: tuple[int, int] = (9, 0), legs: tuple[Leg, ...] = (), dy: int = 0,
             hgrid: Grid = STRIDER_HEAD, dead: bool = False) -> Grid:
    """Body rows 7-13 (+dy); a 2px neck from the shoulders up to the head at ``head``."""
    c = Canvas(16, 24)
    for ch, pts, paw, lw, foot in legs:
        for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
            c.line(x0, y0, x1, y1, ch)
        fx, fy = pts[-1]
        for k in range(1, paw + 1):
            c.set(fx + k, fy, ch)
    hx, hy = head
    c.line(10, 9 + dy, hx + 1, hy + 4, "2")
    c.line(11, 9 + dy, hx + 2, hy + 4, "3")
    c.blit(STRIDER_BODY, 0, 7 + dy)
    h = hgrid if not dead else tuple(r.replace("e", "x") for r in hgrid)
    c.blit(h, hx, hy)
    return outline_grid(c.grid(), "k")


def _sleg(ch: str, hip: tuple[int, int], knee: tuple[int, int], ankle: tuple[int, int],
          foot: tuple[int, int], toes: int = 2) -> Leg:
    return L(ch, hip, knee, ankle, foot, paw=toes)


def _strider_step(near: str, far: str, dy: int = 0) -> tuple[Leg, ...]:
    """Leg states: 'fwd' reaching, 'back' pushing off, 'under' planted, 'up' swinging."""
    def leg(ch: str, hx: int, state: str) -> Leg:
        hy = 13 + dy
        if state == "fwd":
            return _sleg(ch, (hx, hy), (hx + 2, hy + 3), (hx + 2, hy + 6), (hx + 3, 22))
        if state == "back":
            return _sleg(ch, (hx, hy), (hx, hy + 3), (hx - 2, hy + 6), (hx - 3, 22))
        if state == "up":
            return _sleg(ch, (hx, hy), (hx + 2, hy + 2), (hx + 1, hy + 5), (hx + 2, hy + 6), toes=1)
        return _sleg(ch, (hx, hy), (hx + 1, hy + 3), (hx - 1, hy + 6), (hx, 22))
    return (leg("l", 9, far), leg("L", 5, near))


def _tallstrider() -> None:
    legend = {"1": "azc_fur0", "2": "azc_fur1", "3": "bone1", "4": "bone2", "W": "water1",
              "F": "water3", "c": "bone3", "B": "grey2", "r": "red2", "m": "red1",
              "L": "sand3", "l": "sand2", "e": "ink2", "x": "grey1"}
    idle = [_strider(legs=_strider_step("under", "under")),
            _strider(head=(9, 1), legs=_strider_step("under", "under"))]
    move = [
        _strider(legs=_strider_step("fwd", "back")),
        _strider(head=(9, -1), legs=_strider_step("under", "up", dy=-1), dy=-1),
        _strider(legs=_strider_step("back", "fwd")),
        _strider(head=(9, -1), legs=_strider_step("up", "under", dy=-1), dy=-1),
    ]
    attack = [
        # neck drawn back, rising on its toes
        _strider(head=(6, 0), legs=_strider_step("under", "back")),
        # the peck: neck thrust out and down, beak open
        _strider(head=(10, 5), legs=_strider_step("fwd", "back"), hgrid=STRIDER_PECK_HEAD),
    ]
    # dead: sprawled on the ground, long legs stiff in the air, neck laid out flat
    dead = _strider(head=(10, 18), dy=9, dead=True,
                    legs=(L("l", (7, 17), (5, 14), (6, 11), (4, 9), paw=0),
                          L("L", (5, 18), (3, 15), (3, 12), (1, 10), paw=0)))
    _reg("tallstrider.idle", idle, legend, 2, "plainstrider, head bob")
    _reg("tallstrider.move", move, legend, 8, "plainstrider stride")
    _reg("tallstrider.attack", attack, legend, 8, "plainstrider: rear back, peck")
    _reg("tallstrider.dead", [_shadow(dead, 2, 14, 22)], legend, 0, "plainstrider, dead")


_tallstrider()


# ==========================================================================================
# Kodo: a huge hunched beast two tiles long. Slate-grey hide, a high back armoured with
# brown plates fringed with shaggy hair, a low heavy head with a great curved nose horn,
# pillar legs on broad toed feet and a thick tapering tail. Built from shaded forms so all
# frames share one body.
# ==========================================================================================


def _ell(cx: float, cy: float, rx: float, ry: float, w: int = 32, h: int = 24) -> set:
    return {(x, y) for y in range(h) for x in range(w)
            if ((x + 0.5 - cx) / rx) ** 2 + ((y + 0.5 - cy) / ry) ** 2 <= 1.0}


def _shade(c: Canvas, pts: set, light: str, main: str, dark: str, deep: str = "") -> None:
    """Fill a form lit from the top-left: rim light on top/left, shadow on bottom/right."""
    for (x, y) in pts:
        if (x, y - 1) not in pts or (x - 1, y) not in pts and (x, y - 2) not in pts:
            ch = light
        elif (x, y + 1) not in pts or (x + 1, y) not in pts:
            ch = dark
        elif deep and (x, y + 2) not in pts:
            ch = dark
        else:
            ch = main
        c.set(x, y, ch)


def _kodo(dy: int = 0, head_dy: int = 0, fore: tuple[int, int] = (0, 0), hind: tuple[int, int] = (0, 0),
          lift: tuple[int, int, int, int] = (0, 0, 0, 0), dead: bool = False) -> Grid:
    """``fore``/``hind`` = (near, far) foot offsets; ``lift`` raises (near fore, far fore,
    near hind, far hind) feet off the ground."""
    c = Canvas(32, 24)
    g = 22  # ground row (the outline goes below it)
    by = dy + (4 if dead else 0)
    if not dead:
        # far legs (dark), then near legs: thick pillars on broad feet with pale toenails
        for x0, off, up in ((18, fore[1], lift[1]), (9, hind[1], lift[3])):
            leg = {(x0 + k + (off if y > 18 else 0), y) for y in range(14 + dy, g + 1 - up)
                   for k in range(3)}
            _shade(c, leg, "2", "1", "0")
            for k in range(3):
                c.set(x0 + k + off, g - up, "0")
        for x0, off, up in ((21, fore[0], lift[0]), (5, hind[0], lift[2])):
            leg = {(x0 + k + (off if y > 18 else 0), y) for y in range(14 + dy, g + 1 - up)
                   for k in range(4)}
            _shade(c, leg, "3", "2", "1")
            for k in range(4):
                c.set(x0 + k + off, g - up, "n" if k % 2 == 0 else "1")
    else:
        # collapsed: legs folded out from under the belly, front and back
        for pts, ch in ((((22, 18), (26, 21), (27, 22)), "2"), (((6, 18), (3, 21), (2, 22)), "2")):
            for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
                c.line(x0, y0, x1, y1, ch)
                c.line(x0 + 1, y0, x1 + 1, y1, ch)
    # tail, body barrel and the hump over the shoulders
    tail = {(x, y) for x in range(0, 6) for y in range(10 + by, 18 + by)
            if abs((y - 10 - by) - (6 - x) * 1.1) < 1.3 + (x - 1) * 0.25 and y - by < 18 - x // 3}
    _shade(c, tail, "3", "2", "1")
    body = _ell(14.5, 12.5 + by, 11.5, 5.6) | _ell(14.0, 9.5 + by, 8.5, 5.5) | _ell(20.0, 10.5 + by, 5.0, 4.0)
    body = {(x, y) for (x, y) in body if y <= g}
    _shade(c, body, "4", "3", "2", deep="1")
    for (x, y) in body:  # belly shade band
        if (x, y + 1) in body and (x, y + 2) not in body and y > 13 + by:
            c.set(x, y, "1")
    # armoured back: rows of staggered brown plates, dark seams, a shaggy fringe below
    top: dict[int, int] = {}
    for (x, y) in body:
        top[x] = min(top.get(x, 99), y)
    for (x, y) in body:
        depth = y - top[x]
        edge = 5 + ((x * 7) % 3 == 0) - (x < 7) - (x > 22) - (x < 5)
        if depth < edge:
            row = depth // 2
            col = (x + row * 2) % 4
            if depth % 2 == 1:
                ch = "P" if col in (0, 3) else "p"
            elif col == 0:
                ch = "P"
            else:
                ch = "s" if col == 1 else "p"
            c.set(x, y, ch)
        elif depth == edge:
            c.set(x, y, "P" if x % 2 == 0 else "p")  # shaggy hair hanging from the plates
        elif depth == edge + 1 and x % 2 == 0 and 8 < x < 24:
            c.set(x, y, "P")
    # head: low and heavy, a big curved nose horn and a short brow horn
    hx, hy = 26, 14 + by + head_dy
    for (x, y) in _ell(hx - 1.5, hy + 0.5, 1.5, 3.2):   # neck shadow behind the jaw
        if (x, y) in body:
            c.set(x, y, "1")
    head = _ell(hx + 0.5, hy + 0.5, 4.0, 3.6) | _ell(hx + 3.2, hy + 1.5, 2.3, 2.1)
    _shade(c, head, "4", "3", "2")
    c.set(hx, hy - 1, "x" if dead else "e")
    c.set(hx + 4, hy + 1, "1")          # nostril
    c.set(hx + 3, hy + 3, "1")          # mouth line
    c.set(hx + 2, hy + 3, "1")
    for (x, y, ch) in ((hx + 3, hy - 1, "N"), (hx + 4, hy - 1, "n"), (hx + 4, hy - 2, "n"),
                       (hx + 5, hy - 2, "N"), (hx + 5, hy - 3, "n"), (hx + 5, hy - 4, "N"),
                       (hx + 5, hy - 5, "n"), (hx + 4, hy - 6, "N"),
                       (hx - 1, hy - 3, "n"), (hx - 2, hy - 4, "n"), (hx - 3, hy - 5, "N")):
        c.set(x, y, ch)
    return outline_grid(c.grid(), "k")


def _kodo_dead() -> Grid:
    """Rolled onto its side with its back to the viewer: the plated hump rests on the
    ground, the four pillar legs stick stiffly out over the belly, the head lies on its cheek."""
    c = Canvas(32, 24)
    a = 26.5  # the standing body mirrored top-to-bottom about y = a / 2
    for (x0, x1, lean) in ((6, 3, -1), (9, 3, -1), (19, 3, 1), (22, 3, 1)):
        pts = {(x0 + k + (lean * (11 - y)) // 3, y) for y in range(4, 12) for k in range(x1)}
        near = x0 in (6, 22)
        _shade(c, pts, "3" if near else "2", "2" if near else "1", "1" if near else "0")
        tip = min(y for _, y in pts)
        for (x, y) in pts:
            if y == tip:
                c.set(x, y, "n" if x % 2 == 0 else "1")
    tail = {(x, y) for x in range(0, 6) for y in range(16, 22) if abs((a - y - 10) - (6 - x) * 1.1) < 1.6}
    _shade(c, tail, "3", "2", "1")
    body = _ell(14.5, a - 12.5, 11.5, 5.6) | _ell(14.0, a - 9.5, 8.5, 5.5) | _ell(20.0, a - 10.5, 5.0, 4.0)
    body = {(x, y) for (x, y) in body if y <= 22}
    _shade(c, body, "4", "3", "2", deep="1")
    for (x, y) in body:  # pale belly skin, now facing up
        if (x, y - 1) not in body:
            c.set(x, y, "5")
    bottom: dict[int, int] = {}
    for (x, y) in body:
        bottom[x] = max(bottom.get(x, -1), y)
    for (x, y) in body:  # the armoured back, now along the ground
        depth = bottom[x] - y
        if depth < 4:
            col = (x + (depth // 2) * 2) % 4
            c.set(x, y, "P" if col == 0 or depth % 2 == 1 and col == 3 else ("s" if col == 1 else "p"))
        elif depth == 4:
            c.set(x, y, "P" if x % 2 == 0 else "p")
    hx, hy = 26, 18
    head = _ell(hx + 0.5, hy + 0.5, 4.0, 3.6) | _ell(hx + 3.2, hy + 1.5, 2.3, 2.1)
    _shade(c, head, "4", "3", "2")
    c.set(hx, hy - 1, "x")
    c.set(hx + 4, hy + 1, "1")
    c.set(hx + 2, hy + 3, "1")
    c.set(hx + 3, hy + 3, "1")
    for (x, y, ch) in ((hx + 3, hy - 1, "N"), (hx + 4, hy - 1, "n"), (hx + 5, hy - 2, "n"),
                       (hx + 5, hy - 3, "N"), (hx + 5, hy - 4, "n"), (hx - 1, hy - 3, "n"),
                       (hx - 2, hy - 4, "N")):
        c.set(x, y, ch)
    return _shadow(outline_grid(c.grid(), "k"), 2, 30, 22)


def _kodo_sprites() -> None:
    legend = {"0": "azc_kodo0", "1": "azc_kodo1", "2": "azc_kodo2", "3": "azc_kodo3",
              "4": "azc_kodo4", "p": "azc_fur2", "s": "azc_fur3", "P": "azc_fur1",
              "n": "bone3", "N": "bone2", "e": "ink2", "x": "azc_kodo0", "5": "azc_kodo5"}
    idle = [_kodo(), _kodo(head_dy=1)]
    move = [  # a heavy, rolling walk: diagonal pairs, the body sagging onto each contact
        _kodo(dy=1, fore=(2, -1), hind=(-1, 2)),
        _kodo(fore=(0, 0), hind=(0, 0), lift=(0, 2, 2, 0), head_dy=-1),
        _kodo(dy=1, fore=(-1, 2), hind=(2, -1)),
        _kodo(fore=(0, 0), hind=(0, 0), lift=(2, 0, 0, 2), head_dy=-1),
    ]
    _reg("kodo.idle", idle, legend, 1.5, "kodo, slow head sway")
    _reg("kodo.move", move, legend, 6, "kodo heavy walk")
    _reg("kodo.dead", [_kodo_dead()], legend, 0, "kodo, fallen on its side")


_kodo_sprites()


# ==========================================================================================
# Birds of prey: vulture (the Swoops: slate-blue plumage, bald red head over a white ruff, pale
# hooked beak) and eagle (brown with a white head and tail, yellow beak and feet). One bird
# body: perched and hunched when idle, flapping in the air (with a ground shadow) on the move.
# ==========================================================================================

BIRD_FLY = grid("""
    ................
    ................
    ................
    ................
    ................
    ..........rrr...
    .........RrreBB.
    .TT4444RRRr..B..
    .TT33333333.....
    ..T222222.......
    ................
    ................
    ................
    ................
    ................
    ................
""")
# wing poses: near wing (W, pale feather edge V) over the body, far wing (X) behind it
NEAR_UP = grid("""
    V.V.V....
    VWVWV....
    .VWWWW...
    ..VWWWW..
    ...VWWWW.
    ....VWWWW
    ......WWW
""")
FAR_UP = grid("""
    ..X.X.
    .XXXX.
    ..XXXX
    ...XXX
    ....XX
""")
FAR_SPREAD = grid("""
    XX......
    XXXX....
    .XXXXX..
    ..XXXXXX
    ....XXXX
""")
NEAR_SPREAD = grid("""
    ....VWWWW
    ...VWWWW.
    ..VWWWW..
    .VWWWV...
    VWVWV....
    V.V.V....
""")
NEAR_DOWN = grid("""
    ...VWWWW
    ...VWWWW
    ..VWWWV.
    ..VWWV..
    .VWVV...
    .V.V....
""")
FAR_DOWN = grid("""
    XXX.
    XXX.
    .XX.
    .X..
""")
TALONS = grid("""
    f..
    .ff
""")
BIRD_PERCH = grid("""
    ................
    ................
    ................
    ................
    ..........rrr...
    ..........rreBB.
    .........RRrr.B.
    ........RRR.....
    ......4WW3......
    .....44WWW3.....
    ....433WWVW3....
    ...TT33WWVW2....
    ..TT..2222......
    ................
    ................
    ................
""")
BIRD_PERCH_B = grid("""
    ................
    ................
    ................
    ................
    ................
    ...........rrr..
    .........RRrreB.
    ........RRR.rBB.
    ......4WW3......
    .....44WWW3.....
    ....433WWVW3....
    ...TT33WWVW2....
    ..TT..2222......
    ................
    ................
    ................
""")
BIRD_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..........rrr...
    ...VWWWWWRRrxBB.
    .TT3333333RR..B.
    ..VVWWW..f.f....
    ................
""")


def _bird(body: Grid, near: tuple[Grid, int, int] | None = None, far: tuple[Grid, int, int] | None = None,
          dx: int = 0, dy: int = 0, feet: tuple[int, ...] = (), talons: bool = False,
          shadow: bool = False) -> Grid:
    """Far wing behind the body, near wing over it (both placed relative to the body's
    (dx, dy)); perched birds stand on 'f' legs; flying birds cast a small ground shadow."""
    c = Canvas(16, 16)
    if far:
        c.blit(far[0], far[1] + dx, far[2] + dy)
    for fx in feet:
        c.set(fx, 13, "f")
        c.set(fx, 14, "f")
        c.set(fx + 1, 14, "f")
    if talons:
        c.blit(TALONS, 10 + dx, 9 + dy)
    c.blit(shift(body, dx, dy))
    if near:
        c.blit(near[0], near[1] + dx, near[2] + dy)
    g = outline_grid(c.grid(), "k")
    return _shadow(g, 5, 11, 14) if shadow else g


def _birds() -> None:
    vulture = {"2": "steel1", "3": "steel2", "4": "steel3", "W": "steel2", "V": "steel4",
               "X": "steel1", "T": "steel3", "R": "bone4", "r": "red2", "e": "ink2",
               "B": "bone3", "f": "bone2", "x": "red1", "S": "ink:60"}
    eagle = {**vulture, "2": "azc_fur1", "3": "azc_fur2", "4": "azc_fur3", "W": "azc_fur2",
             "V": "azc_fur4", "X": "azc_fur1", "T": "white", "R": "white", "r": "bone4",
             "B": "gold2", "f": "gold1", "x": "bone2"}
    up = {"near": (NEAR_UP, 0, 0), "far": (FAR_UP, 6, 0)}
    spread = {"near": (NEAR_SPREAD, 0, 8), "far": (FAR_SPREAD, 2, 2)}
    down = {"near": (NEAR_DOWN, 1, 8), "far": (FAR_DOWN, 8, 9)}
    idle = [_bird(BIRD_PERCH, feet=(5, 8)), _bird(BIRD_PERCH_B, feet=(5, 8))]
    move = [  # wings up, spread in a glide (far wing up, near wing down), down-stroke, spread
        _bird(BIRD_FLY, **up, dy=0, shadow=True),
        _bird(BIRD_FLY, **spread, dy=-1, shadow=True),
        _bird(BIRD_FLY, **down, dy=-2, shadow=True),
        _bird(BIRD_FLY, **spread, dy=-1, shadow=True),
    ]
    attack = [  # wings thrown up and back, then the dive: talons and beak first
        _bird(BIRD_FLY, **up, dx=-1, dy=-1, shadow=True),
        _bird(BIRD_FLY, **spread, dx=1, dy=1, talons=True, shadow=True),
    ]
    dead = [_shadow(outline_grid(BIRD_DEAD, "k"), 2, 13, 14)]
    _reg("vulture.idle", idle, vulture, 2, "swoop (vulture) perched, head turn")
    _reg("vulture.move", move, vulture, 8, "swoop flapping flight")
    _reg("vulture.attack", attack, vulture, 8, "swoop: rise, dive with talons")
    _reg("vulture.dead", dead, vulture, 0, "swoop, dead")
    _reg("eagle.idle", idle, eagle, 2, "white-headed eagle perched")
    _reg("eagle.move", move, eagle, 8, "eagle flapping flight")
    _reg("eagle.dead", dead, eagle, 0, "eagle, dead")


_birds()


# ==========================================================================================
# Critters (12x12): rabbit, mouse, prairie dog (ground squirrel), crawdad and Kyle the dog.
# Two-frame loops: an idle twitch and a quick scurry or hop.
# ==========================================================================================

# mountain cottontail: grey-brown, long ears laid back, white puff tail, long hind feet
RABBIT = [
    _ol("""
        ............
        ....44......
        .....4p.....
        ......43....
        ......3443..
        ...44333e3n.
        ..43333333..
        .T33333332..
        .T3333322...
        ..22222.2...
        ..2222..22..
        ............
    """),
    # ear flick, nose twitch
    _ol("""
        ............
        ............
        ....444.....
        ......p3....
        ......3443..
        ...44333e3n.
        ..43333333..
        .T33333332..
        .T3333322...
        ..22222.2...
        ..2222..22..
        ............
    """),
]
RABBIT_HOP = [
    # gathered: haunches tucked, ready to spring
    _ol("""
        ............
        ............
        ....44......
        .....4p.....
        ......43....
        ...44443e...
        ..4333333n..
        .T33333332..
        .T33333322..
        ..222222.2..
        ..22222..2..
        ............
    """),
    # airborne: stretched out, hind feet kicked back, forepaws reaching
    _ol("""
        ............
        ...44.......
        ....4p......
        .....43.....
        .....3443...
        ..444333e3n.
        .T43333333..
        .T3333333...
        22..2222.22.
        ............
        ............
        ............
    """),
]
RABBIT_DEAD = _ol("""
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    .......44...
    ...44444p4..
    .T433333x3n.
    ..2222222...
    ...22.22....
""")

# mouse: tiny and grey, a round pink-lined ear, pink nose, feet and a long bare tail
MOUSE = [
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ............
        ......4p....
        ....44443e..
        ..t333333n..
        .t.222222...
        .t..p..p....
        ............
    """),
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ............
        ......4p....
        ....44443e..
        ..t3333333n.
        ..t222222...
        .t..p..p....
        ............
    """),
]
MOUSE_RUN = [
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ............
        ......4p....
        ...444443e..
        .tt3333333n.
        t...22222...
        ...p....p...
        ............
    """),
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ............
        .......4p...
        ...444443e..
        ..t33333333n
        .t..22222...
        t.....pp....
        ............
    """),
]
MOUSE_DEAD = _ol("""
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ......4p....
    ...44443x...
    .tt333333n..
    t...p.p.p...
""")

# prairie dog: sandy ground squirrel standing up on its haunches to keep watch
SQUIRREL = [
    _ol("""
        ............
        ............
        ......444...
        .....p43e3..
        .....33333n.
        ......3bb...
        .....33bbp..
        ....333bb3..
        ....333bb3..
        ...3333bb3..
        .t.22222222.
        ............
    """),
    # a chirp: head thrown up, tail flick
    _ol("""
        ............
        ......444...
        .....p43e3..
        .....33333n.
        ......3bb...
        ......3bb...
        .....33bbp..
        ....333bb3..
        ....333bb3..
        ...3333bb3..
        t..22222222.
        ............
    """),
]
SQUIRREL_RUN = [
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ............
        .......44...
        ...44443e...
        .t33333333n.
        t...bbb2....
        ..2.2..2.2..
        ............
    """),
    _ol("""
        ............
        ............
        ............
        ............
        ............
        .......44...
        ...44443e...
        tt33333333n.
        ....bbb2....
        ...22..22...
        ............
        ............
    """),
]
SQUIRREL_DEAD = _ol("""
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    .......44...
    ..t444443x..
    .t.3333333n.
    ...bbbbb2...
""")

# Stonebull crayfish: a red-brown crawdad with a segmented tail fan, raised pincers and
# long antennae swept back
CRAWDAD = [
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ...aaa......
        ......aa.CC.
        .4.44444eC..
        434333333CC.
        .3.222222...
        ...l.l.l....
        ............
    """),
    # pincers snip open and closed
    _ol("""
        ............
        ............
        ............
        ............
        ....aaa.....
        .......a.C.C
        ......a..CC.
        .4.44444e...
        434333333CC.
        .3.222222...
        ...l.l.l....
        ............
    """),
]
CRAWDAD_MOVE = [
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ...aaa......
        ......aa.CC.
        .4.44444eC..
        434333333CC.
        .3.222222...
        ..l.l.l.....
        ............
    """),
    _ol("""
        ............
        ............
        ............
        ............
        ............
        ..aaa.......
        .....aa..CC.
        .4.44444eC..
        434333333CC.
        .3.222222...
        ...l.l.l....
        ............
    """),
]
CRAWDAD_DEAD = _ol("""
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ...l.l.l....
    .3.222222...
    434333333CC.
    .4.44444xC..
""")

# Kyle the Friendly: a stocky brown dog with floppy dark ears and a wagging tail
DOG_BODY = grid("""
    ............
    ............
    ......433...
    .t...E433e3.
    ..t..E3333n.
    ..44444333b.
    ..3333333b..
    ..32BBBB2...
    ............
    ............
    ............
    ............
""")
DOG_BODY_B = grid("""
    ............
    ............
    ......433...
    .....E433e3.
    tt...E3333n.
    ..44444333m.
    ..3333333b..
    ..32BBBB2...
    ............
    ............
    ............
    ............
""")
DOG_DEAD = _ol("""
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ............
    ......E333..
    .t4444E3x3n.
    ..3BBBB333b.
    ...3.3..3...
""")


def _dog_legs(off: tuple[int, int, int, int], lift: tuple[bool, ...] = (False,) * 4,
              hy: int = 7) -> tuple[Leg, ...]:
    # short straight legs in adjacent pairs: at this size a hock or a gap only adds ink
    return (fore("2", 4, hy, off[0], lift[0], ground=10), fore("2", 8, hy, off[1], lift[1], ground=10),
            fore("3", 3, hy, off[2], lift[2], ground=10), fore("3", 7, hy, off[3], lift[3], ground=10))


def _critters() -> None:
    rabbit = {"2": "azc_fur2", "3": "azc_fur3", "4": "azc_fur4", "T": "white", "p": "blush",
              "e": "ink2", "n": "blush", "x": "azc_fur1"}
    mouse = {"2": "grey2", "3": "grey3", "4": "grey4", "p": "blush", "e": "ink2", "n": "blush",
             "t": "skin3", "x": "grey1"}
    squirrel = {"2": "sand2", "3": "sand3", "4": "sand4", "b": "bone4", "p": "sand2",
                "e": "ink2", "n": "leather2", "t": "sand1", "x": "sand1"}
    crawdad = {"2": "dust2", "3": "dust3", "4": "dust4", "C": "red2", "a": "dust5",
               "l": "dust2", "e": "ink2", "x": "dust1"}
    dog = {"2": "azc_fur2", "3": "azc_fur3", "4": "azc_fur4", "B": "azc_fur5", "b": "azc_fur5",
           "E": "azc_fur1", "t": "azc_fur3", "e": "ink2", "n": "ink2", "m": "blush", "x": "azc_fur1"}
    _reg("rabbit.idle", RABBIT, rabbit, 2, "cottontail, ear and nose twitch")
    _reg("rabbit.move", RABBIT_HOP, rabbit, 6, "cottontail hop")
    _reg("rabbit.dead", [RABBIT_DEAD], rabbit, 0, "cottontail, dead")
    _reg("mouse.idle", MOUSE, mouse, 3, "mouse, sniffing")
    _reg("mouse.move", MOUSE_RUN, mouse, 10, "mouse scurry")
    _reg("mouse.dead", [MOUSE_DEAD], mouse, 0, "mouse, dead")
    _reg("ground_squirrel.idle", SQUIRREL, squirrel, 2, "prairie dog on watch, chirping")
    _reg("ground_squirrel.move", SQUIRREL_RUN, squirrel, 8, "prairie dog scamper")
    _reg("ground_squirrel.dead", [SQUIRREL_DEAD], squirrel, 0, "prairie dog, dead")
    _reg("crawdad.idle", CRAWDAD, crawdad, 2, "Stonebull crayfish, snipping pincers")
    _reg("crawdad.move", CRAWDAD_MOVE, crawdad, 6, "crayfish scuttle")
    _reg("crawdad.dead", [CRAWDAD_DEAD], crawdad, 0, "crayfish, belly up")
    dog_idle = [_pose(12, 12, DOG_BODY, _dog_legs((0, 0, 0, 0))),
                _pose(12, 12, DOG_BODY_B, _dog_legs((0, 0, 0, 0)))]
    dog_move = [_pose(12, 12, DOG_BODY, _dog_legs((-1, -1, 1, 1))),
                _pose(12, 12, DOG_BODY_B, _dog_legs((1, 1, -1, -1), hy=6), dy=-1)]
    _reg("dog.idle", dog_idle, dog, 3, "Kyle the dog, tail wag and panting")
    _reg("dog.move", dog_move, dog, 8, "Kyle the dog trotting")
    _reg("dog.dead", [DOG_DEAD], dog, 0, "dog, dead")


_critters()
