"""Azeroth / Mulgore art: items. Must satisfy
``wilds.azeroth.manifest.required()["items"]`` (see docs/azeroth/mulgore-art-manifest.md).

28 item-icon families stand in for the ~120 quest rewards of Mulgore (hide and boar-skin
belts, prairie-wolf cloaks, bone and stone tomahawks, Bloodhoof war shields, totems,
talismans, bread and water, Darkmoon Faire prize tickets). Every family has four looks,
``az.item.<family>@0..3``, which are four material tiers so the game can pick one by
item quality:

    @0 rough hide      pale untanned hide, sinew lacing, flint and raw wood
    @1 leather         tanned brown leather, pale stitching, iron and brass
    @2 bone-and-stone  smoked dark hide, bone plates and studs, bone blades
    @3 tribal ornate   Horde-red dyed hide, gold trim, turquoise beads, feathers

Each family is ONE shape drawn with *material roles* (characters, below); a tier is a
legend that maps the roles to that tier's colours, plus a few shared ornaments (a
feather, a bone tusk, a fur tuft, beads) layered on for the higher tiers. So the four
looks of a family always share their silhouette. Consumables and oddities (food,
reagents, quest items) are four different small objects that follow the same order
(plain -> fine). Icons sit on a transparent background with the auto 1px ``ink``
outline, lit from the top-left, content within the 14x14 middle of the tile.
"""

from __future__ import annotations

from ..palette import _ramp
from ..pixelart import Grid, art, grid, overlay, recolor
from ..registry import register

# --- colours of this module ------------------------------------------------------------
_ramp("azi_hide", "#3b2d24", "#5f4a3a", "#8a7058", "#b39a7a", "#d8c4a0")    # untanned rawhide
_ramp("azi_leath", "#2c160e", "#512a17", "#7c4424", "#a86434", "#cf8a4e")   # tanned leather
_ramp("azi_smoke", "#1f191c", "#352b2c", "#4f423d", "#6b5a4f", "#8a7664")   # smoked dark hide
_ramp("azi_stone", "#25221f", "#433d37", "#655d54", "#8c8377", "#b8afa0")   # flint / grey stone
_ramp("azi_wood", "#2e1c10", "#4f311b", "#76502c", "#9c7040", "#c49a60")    # timber, handles

# --- material roles ----------------------------------------------------------------------
# 4 3 2 1  primary material (hide / leather / smoked hide / red dyed hide), light -> dark
# 7 6 5    trim, lacing, stitching, bands
# a b c d  hard material: blades, heads, buckles (flint / iron / bone / polished steel)
# x y z    wood
# g G      bead / stud / gem accent
# f F      fur or fleece trim
ROLES = "4321765abcdxyzgGfF"
TIER_NAMES = ("rough hide", "leather", "bone-and-stone", "tribal ornate")
TIERS: tuple[dict[str, str], ...] = (
    {"4": "azi_hide4", "3": "azi_hide3", "2": "azi_hide2", "1": "azi_hide1",
     "7": "bone3", "6": "bone2", "5": "bone1",
     "a": "azi_stone4", "b": "azi_stone3", "c": "azi_stone2", "d": "azi_stone1",
     "x": "azi_wood3", "y": "azi_wood2", "z": "azi_wood1",
     "g": "bone3", "G": "bone1", "f": "azi_hide4", "F": "azi_hide2"},
    {"4": "azi_leath4", "3": "azi_leath3", "2": "azi_leath2", "1": "azi_leath1",
     "7": "azi_hide4", "6": "azi_hide3", "5": "azi_hide1",
     "a": "steel5", "b": "steel4", "c": "steel3", "d": "steel2",
     "x": "azi_wood4", "y": "azi_wood2", "z": "azi_wood1",
     "g": "gold2", "G": "gold0", "f": "bone4", "F": "bone2"},
    {"4": "azi_smoke4", "3": "azi_smoke3", "2": "azi_smoke2", "1": "azi_smoke1",
     "7": "bone4", "6": "bone3", "5": "bone2",
     "a": "bone4", "b": "bone3", "c": "bone2", "d": "bone1",
     "x": "azi_wood3", "y": "azi_wood2", "z": "azi_wood1",
     "g": "azi_stone4", "G": "azi_stone1", "f": "azi_smoke4", "F": "azi_smoke2"},
    {"4": "red3", "3": "red2", "2": "red1", "1": "red0",
     "7": "gold2", "6": "gold1", "5": "gold0",
     "a": "chrome3", "b": "chrome2", "c": "chrome1", "d": "chrome0",
     "x": "azi_wood4", "y": "azi_wood3", "z": "azi_wood1",
     "g": "cryst1", "G": "cryst0", "f": "white", "F": "bone3"},
)
# jewellery and idols are gold, not polished steel, at the ornate tier
GOLD_HARD = {"a": "gold3", "b": "gold2", "c": "gold1", "d": "gold0"}

# Fixed-colour characters for the shared ornaments (same in every tier).
ORN = {"W": "white", "V": "bone3", "e": "red2", "E": "red0", "q": "cryst1", "Q": "cryst0",
       "u": "bone4", "U": "bone2", "h": "bone4", "H": "bone2", "j": "gold2", "J": "gold0"}

# --- shared ornaments ---------------------------------------------------------------------
FEATHER = """
    .K.
    .W.
    WWV
    WVV
    WVV
    eVE
    .E.
"""
BEADS = """
    K
    q
    j
    q
"""
TUSK = """
    u.
    uU
    uU
    .U
"""
STUD = """
    uu
    uU
"""


def _put(piece: str, x: int, y: int) -> tuple[Grid, int, int]:
    return grid(piece), x, y


def _compose(base: str | Grid, pieces=()) -> Grid:
    g = grid(base) if isinstance(base, str) else base
    for piece, x, y in pieces:
        g = overlay(g, piece, x, y)
    return g


def _reg(family: str, look: int, g: Grid, legend: dict[str, str], note: str) -> None:
    register(f"az.item.{family}@{look}", art(g, legend=legend, outline="ink", note=note))


def family(name: str, base: str, *, orn: dict[int, list] | None = None,
           over: dict[int, dict[str, str]] | None = None, shapes: dict[int, str] | None = None,
           what: str = "") -> None:
    """Register the four tier looks of one shape: ``orn[t]`` ornaments layered on tier
    ``t``, ``over[t]`` role colours overridden for tier ``t``, ``shapes[t]`` a different
    shape (same roles) for tier ``t``."""
    orn, over, shapes = orn or {}, over or {}, shapes or {}
    for t in range(4):
        g = _compose(grid(shapes.get(t, base)), orn.get(t, ()))
        legend = {**ORN, **TIERS[t], **over.get(t, {})}
        _reg(name, t, g, legend, f"{TIER_NAMES[t]} {what or name}")


def looks(name: str, *items: tuple[str | Grid, dict[str, str], str]) -> None:
    """Register four different objects (consumables, oddities) as looks @0..3."""
    for t, (g, legend, note) in enumerate(items):
        _reg(name, t, grid(g) if isinstance(g, str) else g, {**ORN, **legend}, note)


# =========================================================================================
# Armour
# =========================================================================================

# --- belt: a closed belt seen from above-front, buckle at the front, tail tucked -----------------
BELT = """
    ................
    ................
    ................
    ....22222222....
    ..221111111122..
    .21..........12.
    .3............2.
    .3...abbc.....2.
    .43..bkkc....21.
    .443.b7kc..3321.
    ..4436bkc63322..
    ...443ddd3322...
    .....43322211...
    .........21.....
    ................
    ................
"""
family("belt", BELT, what="belt (hide / boar-skin / scale / Sunwalker cord)",
       orn={2: [_put(STUD, 11, 8), _put(STUD, 2, 7)],
            3: [_put(BEADS, 11, 11), _put(BEADS, 13, 10)]})

# --- boots: one boot, toe to the right, fur cuff ------------------------------------------------
BOOTS = """
    ................
    ...fffffff......
    ..fFfFfFfFf.....
    ...43333321.....
    ...4373321......
    ...4333221......
    ...4373221......
    ...4333221......
    ...43732211.....
    ...433322221....
    ...43333222211..
    ..4433333222221.
    ..4333333322221.
    ..555555555555..
    ................
    ................
"""
family("boots", BOOTS, what="boots (sandals / cliff runner / rainwalker)",
       orn={2: [_put(STUD, 11, 10)], 3: [_put(FEATHER, 10, 1)]})

# --- bracers: a laced wrist cuff standing on end, opening on top -----------------------------------
BRACERS = """
    ................
    ................
    .....666666.....
    ....6KKKKKK6....
    ....76666665....
    ....43333221....
    ...4433K33221...
    ...4337K73221...
    ...4333K33221...
    ...4337K73221...
    ...4433K33221...
    ...4333333221...
    ...7666666665...
    ....55555555....
    ................
    ................
"""
family("bracers", BRACERS, what="bracers (wristwraps / wristguards / armbands)",
       orn={2: [_put(STUD, 4, 8), _put(STUD, 10, 8)], 3: [_put(BEADS, 13, 9), _put(BEADS, 2, 9)]})

# --- chest: a laced tunic with short sleeves and a fringed hem ----------------------------------------
CHEST = """
    ................
    ....443..221....
    ..4443k..k2221..
    .44433k77k32221.
    .443333kk332221.
    .43333377332221.
    .43k333333332k1.
    ...4333333322...
    ...4333333222...
    ...4333333222...
    ...4333332221...
    ...6666666665...
    ...7676767665...
    ...7.7.7.7.6....
    ................
    ................
"""
family("chest", CHEST, what="chest (vest / breastplate / robe)",
       orn={2: [_put(STUD, 4, 7), _put(STUD, 9, 7)],
            3: [_put(BEADS, 4, 7), _put(BEADS, 10, 7)]})

# --- gloves: open hand, fingers up, thumb out, cuff ----------------------------------------------------
GLOVES = """
    ................
    .......42.......
    .....424231.....
    .....42423121...
    .....42423121...
    ...4.42423121...
    ...4342423121...
    ...4333333221...
    ...4333333221...
    ....433333221...
    ....433332221...
    ...7766666665...
    ...7666666665...
    ...5555555555...
    ................
    ................
"""
family("gloves", GLOVES, what="gloves (handguards / handwraps)",
       orn={0: [_put("ff\nFf", 3, 11)], 2: [_put("uuuuuuuU", 4, 7)],
            3: [_put(BEADS, 12, 11)]})

# --- helm: a horned cap with brow band, nasal and cheek guards ---------------------------------------
HELM = """
    ................
    ................
    .h............H.
    .hV...4332...VH.
    .hVH44333221VVH.
    ..hH43333221VH..
    ...H43333221H...
    ...4777777775...
    ...43K3ab3K21...
    ...43KKbcKK21...
    ...43..cd..21...
    ...43.......1...
    ...44......21...
    ....4......1....
    ................
    ................
"""
family("helm", HELM, what="helm (cap / barbut / horned helm)",
       orn={3: [_put(FEATHER, 7, 1)]})

# --- legs: trousers, front view -----------------------------------------------------------------------
LEGS = """
    ................
    ...7777666665...
    ...4333333221...
    ...4333333221...
    ...4333333221...
    ...43332.3221...
    ...4333..3221...
    ...4332..3221...
    ...4362..3621...
    ...4332..3221...
    ..44332..32221..
    ..43322..32221..
    ..76665..76665..
    ................
    ................
    ................
"""
family("legs", LEGS, what="leggings (trousers / greaves / leg armor)",
       orn={2: [_put(STUD, 4, 8), _put(STUD, 10, 8)], 3: [_put(BEADS, 2, 1), _put(BEADS, 13, 1)]})

# --- shoulders: one broad pauldron with a lower lame ---------------------------------------------------
SHOULDERS = """
    ................
    ................
    .....444332.....
    ...44433333221..
    ..4433333332221.
    .44333333322221.
    .43g333g33g2221.
    .43333333222211.
    .77777777766665.
    ..433333222221..
    ..766666666655..
    ...4333322221...
    ...7666666655...
    ................
    ................
    ................
"""
family("shoulders", SHOULDERS, what="shoulders (pauldron / spaulders)",
       orn={0: [_put("f.f.f\nFfFfF", 4, 1)], 2: [_put(TUSK, 3, 1), _put(TUSK, 9, 0)],
            3: [_put(FEATHER, 12, 7)]})

# --- cloak: a cape hanging from a clasp, fur collar, folds, trimmed hem -----------------------------------
CLOAK = """
    ................
    ....ffffffff....
    ...fFfFgGfFfF...
    ....43332221....
    ....43332221....
    ...4433322211...
    ...4343322121...
    ..443433221211..
    ..433433221221..
    ..433433221221..
    .44334332212211.
    .43334332212221.
    .43334332212221.
    .77677677657655.
    ................
    ................
"""
family("cloak", CLOAK, what="cloak (prairie-wolf / sun-beaten / Thunderhorn)",
       orn={3: [_put(BEADS, 5, 11), _put(BEADS, 10, 11)]})

# --- shield: round war shield, hide face on a timber hoop, painted sun cross, boss ----------------------------
SHIELD = """
    ................
    .....xxxxxy.....
    ...xx444333yz...
    ..x4443333322z..
    ..x4433333322z..
    .x443333333222z.
    .x433333333222z.
    .x43333ab33222z.
    .x33333cd32222z.
    .x333333322221z.
    .x332222222211z.
    ..x3222222211z..
    ..x2222221111z..
    ...y22221111zz..
    .....yzzzzz.....
    ................
"""
LASHING = """
    z........z
    .z......z.
    ..z....z..
    ...z..z...
    ....zz....
    ....zz....
    ...z..z...
    ..z....z..
    .z......z.
    z........z
"""
SUN_CROSS = """
    .....gG.....
    .....gG.....
    .....gG.....
    .....gG.....
    .....gG.....
    gggggggggggg
    GGGGGGGGGGGG
    .....gG.....
    .....gG.....
    .....gG.....
    .....gG.....
    .....gG.....
"""
BONE_RING = """
    ...uuuu...
    ..uu..uU..
    .uu....UU.
    uu......UU
    u........U
    u........U
    uU......UU
    .UU....UU.
    ..UU..UU..
    ...UUUU...
"""
DIAMOND = """
    ....jj....
    ...jqqj...
    ..jqqqqJ..
    .jqqqqQQJ.
    jqqqqQQQQJ
    jqqqQQQQQJ
    .jqQQQQQJ.
    ..JQQQQJ..
    ...JQQJ...
    ....JJ....
"""
BOSS = "ab\ncd"
family("shield", SHIELD, what="shield (buckler / Bloodhoof war shield)",
       orn={0: [_put(LASHING, 3, 3), _put(BOSS, 7, 7)],
            1: [_put(SUN_CROSS, 2, 2), _put(BOSS, 7, 7)],
            2: [_put(BONE_RING, 3, 3), _put(BOSS, 7, 7)],
            3: [_put(DIAMOND, 3, 3), _put(BOSS, 7, 7), _put(FEATHER, 0, 9), _put(FEATHER, 13, 9)]})

# =========================================================================================
# Weapons (all point to the top-right, grip bottom-left)
# =========================================================================================

SWORD = """
    ................
    .............ab.
    ............abc.
    ...........abc..
    ..........abc...
    .........abc....
    ........abc.....
    .......abc......
    ...7..abc.......
    ...67abc........
    ....56c.........
    ...4356.........
    ..432..5........
    .432............
    .gG.............
    ................
"""
family("sword", SWORD, what="sword (gladius / blade)",
       orn={3: [_put("..j\n.jJ\njJ.", 3, 8)]})

AXE = """
    ................
    ...ab...........
    ...abb..........
    ...abbbc....xy..
    ...abbbbcc7yz...
    ...abbbbccd6z...
    ...abbccd.yz....
    ...acd...yz.....
    ...d....yz......
    .......yz.......
    ......43........
    .....432........
    ....yz..........
    ...yz...........
    ................
    ................
"""
family("axe", AXE, what="axe (stone / bone / ceremonial tomahawk)",
       orn={3: [_put(FEATHER, 11, 6)]})

MACE = """
    ................
    .........abb....
    ........abgbc...
    .......abbbbcc..
    .......gbbbccg..
    ........bbccdd..
    ........7ccdd...
    .......x6.dd....
    ......xyz.......
    .....xyz........
    ....xyz.........
    ...43z..........
    ..432...........
    ..32............
    ................
    ................
"""
family("mace", MACE, what="mace (rock mace / kodo mallet / hammer)",
       orn={3: [_put(FEATHER, 3, 3)]})

DAGGER = """
    ................
    ................
    ................
    ............a...
    ...........abc..
    ..........abbc..
    .........abbc...
    ........abbc....
    .....7.abbc.....
    .....67bcc......
    ......56c.......
    .....436........
    ....432.5.......
    ...gG...........
    ................
    ................
"""
family("dagger", DAGGER, what="dagger (fighting knife / ceremonial dagger)",
       orn={3: [_put(BEADS, 9, 11)]})

STAFF = """
    ................
    ........xxy.....
    .......xy.yz....
    ......xy.ggyz...
    ......7..gGyz...
    ......f....yz...
    .....fF...xy....
    .....fF..xy.....
    ......F.xy......
    .......xy.......
    ......43........
    .....432........
    ....xy..........
    ...xy...........
    ..yz............
    ................
"""
family("staff", STAFF, what="staff (crook with a set stone and a hanging feather)",
       orn={2: [_put(STUD, 2, 11)], 3: [_put(BEADS, 13, 5)]})

BOW = """
    ................
    ..........ab....
    ........xy.V....
    ......xy...V....
    .....xy....V....
    ....xy.....V....
    ....xy.....V....
    .W.43......V.a..
    .Ve43yyyyyyyyab.
    .e.43......V.c..
    ....yz.....V....
    .....yz....V....
    ......yz...V....
    ........yz.V....
    ..........cd....
    ................
"""
RIFLE = """
    ................
    ................
    ................
    ................
    ................
    ................
    ..............a.
    ......aabbbbbbb.
    .xxxxxy6ccccccd.
    .xyyyyz43k......
    .xyz...32.......
    .xyz............
    .yzz............
    ................
    ................
    ................
"""
family("ranged", BOW, what="ranged (hunting bow; the @2 look is a rifle)",
       shapes={2: RIFLE}, over={2: {"a": "grey4", "b": "grey3", "c": "grey2", "d": "grey1"}},
       orn={2: [_put(STUD, 2, 8)], 3: [_put(BEADS, 12, 1), _put(BEADS, 12, 11)]})

# =========================================================================================
# Totems, relics, jewellery
# =========================================================================================

TOTEM = """
    ................
    ..44........21..
    ..433......321..
    ...4336..6321...
    ....43xyyy21....
    .....xyyyz......
    .....xKyKz......
    .....xyyyz......
    .....xKKKz......
    .....7666655....
    .....xyyyz......
    .....xgyGz......
    .....xyyyz......
    ....x7666655....
    ....xyyyyzz.....
    ................
"""
family("totem", TOTEM, what="totem (earth totem / carved pole)",
       orn={3: [_put(FEATHER, 1, 5), _put(FEATHER, 12, 5)]})

RELIC = """
    ................
    ................
    .a..........c...
    .ab........cd...
    ..abb....bcd....
    ...abbbbbbcd....
    ....abbbbcc.....
    ....aKbbKcc.....
    ....abbbbcd.....
    .....abbcd......
    .....abbcd......
    ......bcd.......
    ......767.......
    ......434.......
    .......2........
    ................
"""
family("relic", RELIC, what="relic (kodo-skull talisman / idol)",
       over={1: {"a": "azi_wood4", "b": "azi_wood3", "c": "azi_wood2", "d": "azi_wood1"}, 3: GOLD_HARD},
       orn={3: [_put(BEADS, 3, 9), _put(BEADS, 11, 9)]})

RING = """
    ................
    ................
    ................
    ......gGG.......
    .....gggGG......
    ....abgGGcd.....
    ...ab.ccc.cd....
    ..ab.......cd...
    ..a.........d...
    ..ab.......cd...
    ...ab.....cd....
    ....abbccdd.....
    ......cdd.......
    ................
    ................
    ................
"""
family("ring", RING, what="ring (band / signet)",
       over={0: {"a": "azi_wood4", "b": "azi_wood3", "c": "azi_wood2", "d": "azi_wood1"},
             3: GOLD_HARD})

AMULET = """
    ................
    ..6..........6..
    ..6..........5..
    ...6........5...
    ...6........5...
    ....6......5....
    .....6....5.....
    ......6gG5......
    ......abbc......
    ......abbc......
    ......abcd......
    .......bd.......
    .......cd.......
    ........d.......
    ................
    ................
"""
family("amulet", AMULET, what="amulet (claw talisman / coin of ancestry)",
       over={3: GOLD_HARD}, orn={3: [_put("q\nQ", 5, 7), _put("q\nQ", 10, 7)]})

# =========================================================================================
# Consumables and containers
# =========================================================================================

BREAD = """
    ................
    ................
    ................
    ................
    ................
    ......4443......
    ....44333332....
    ...4337332731...
    ..433373327321..
    ..433337332221..
    ..333333322221..
    ..222222222211..
    ...1111111111...
    ................
    ................
    ................
"""
MUTTON = """
    ................
    ................
    ..........uu....
    .........uuUU...
    ..........uU....
    .........ua.....
    .....4443ab.....
    ...44333322.....
    ..4333332221....
    ..43333222211...
    ..3332222211....
    ..222222111.....
    ...2211111......
    ................
    ................
    ................
"""
RIBS = """
    ................
    ................
    ................
    ................
    ..u.u.u.u.......
    ..uUuUuUuU......
    ..44433333322...
    .4333333332221..
    .433333322221...
    .33333222222211.
    .22222221111111.
    ..11111111111...
    ................
    ................
    ................
    ................
"""
MARZIPAN = """
    ................
    ................
    ................
    ......e.........
    .....eEj........
    ....44j43.......
    ...443333322....
    ...77777776.....
    ..4333333332....
    ..43333333221...
    ..77777777765...
    ..44333333221...
    ...333322221....
    ....22221111....
    ................
    ................
"""
BREAD_C = {"4": "tent4", "3": "tent3", "2": "tent2", "1": "tent1", "7": "bone4"}
MEAT_C = {"4": "brute4", "3": "brute3", "2": "brute2", "1": "brute1", "a": "red2", "b": "red1"}
RIBS_C = {"4": "brute4", "3": "brute3", "2": "brute2", "1": "brute1"}
CAKE_C = {"4": "bone4", "3": "sand4", "2": "sand3", "1": "sand2", "7": "spore4", "6": "spore3",
          "5": "spore2"}
looks("food",
      (BREAD, BREAD_C, "tough hunk of bread"),
      (MUTTON, MEAT_C, "roast mutton on the bone"),
      (RIBS, RIBS_C, "kodo ribs"),
      (MARZIPAN, CAKE_C, "Thunder Bluff marzipan cake"))

# --- drink: a hide waterskin with a wooden stopper and a carry strap -------------------------------------
DRINK = """
    ................
    ....77..........
    ...7..7.xy......
    ..7....7zy......
    ..6....433......
    ..6...43322.....
    ..6..4333322....
    ...6433333221...
    ...4333333221...
    ...43333332221..
    ...43333322221..
    ...33333222211..
    ....322222211...
    .....1111111....
    ................
    ................
"""
family("drink", DRINK, what="drink (spring water in a skin)",
       orn={2: [_put(STUD, 5, 8)], 3: [_put(BEADS, 11, 4)]})

# --- potion: round glass flask, corked, tied with a cord; the liquid colour rises with tier -------------------
POTION = """
    ................
    ................
    .......xy.......
    ......xyyz......
    ......6776......
    ......wlLl......
    .....wlllLl.....
    ....wllllLLl....
    ...wlmmmmmmmL...
    ...lmmmmmmmnL...
    ...lmmmmmmnnL...
    ...lmmmmmnnnL...
    ....mmmnnnnL....
    .....LLLLLL.....
    ................
    ................
"""
_GLASS = {"w": "white", "l": "glass4", "L": "glass2"}
_LIQUID = ({"m": "moss4", "n": "moss3"}, {"m": "red3", "n": "red2"},
           {"m": "water4", "n": "water3"}, {"m": "flora4", "n": "flora3"})
_potion = art(grid(POTION), legend={**ORN, **TIERS[1], **_GLASS, **_LIQUID[1]}, outline="ink")
for _t in range(4):
    _p = recolor(_potion, {**{TIERS[1][r]: TIERS[_t][r] for r in "765xyz"},
                           "red3": _LIQUID[_t]["m"], "red2": _LIQUID[_t]["n"]},
                 note=f"{TIER_NAMES[_t]} potion")
    register(f"az.item.potion@{_t}", _p)

# --- bag: a drawstring sack --------------------------------------------------------------------------------
BAG = """
    ................
    ................
    ......7..7......
    .....6.66.5.....
    ......4332......
    ......6776......
    .....433321.....
    ...4433333221...
    ..443333333221..
    ..433333332221..
    ..433333332221..
    ..433333322221..
    ..333333222211..
    ...3322222211...
    ....11111111....
    ................
"""
family("bag", BAG, what="bag (kodo hide bag / saddlebag)",
       orn={2: [_put(TUSK, 12, 3)], 3: [_put(BEADS, 4, 4), _put(BEADS, 10, 4)]})

# --- reagents: a hide scrap, a tied herb bundle, bone shards, a dyed feather bundle ---------------------------
HIDE_SCRAP = """
    ................
    ................
    ................
    ................
    ....4.....4.....
    ...44333332.....
    ....433332221...
    ...4333332221...
    ..433323322211..
    ...33332222211..
    ....322222111...
    ...3.2222.11....
    ..........1.....
    ................
    ................
    ................
"""
HERBS = """
    ................
    ................
    .......WW.......
    ......WjjV......
    .......VV.......
    ...44...3..44...
    ..4433..3.4332..
    ...4333.33332...
    .....3332322....
    ......7676......
    ......3232......
    ......3.22......
    .....3...2......
    ................
    ................
    ................
"""
BONES = """
    ................
    ................
    ................
    ................
    ..........a.....
    .........abc....
    ........abc.....
    ...ab..abc......
    ..abbcabc.......
    ...abbcc..gg....
    ....bccd.gGGG...
    .....cd..GGGG...
    ..........GG....
    ................
    ................
    ................
"""
PLUMES = """
    ................
    ................
    ..W.......e.....
    ..WV.....ee.....
    ..WV....eE......
    ...WV..eE.......
    ...WVWeE........
    ....WWE.........
    .....77.........
    .....7j.........
    ....6q..........
    ....5Q..........
    ................
    ................
    ................
    ................
"""
looks("reagent",
      (HIDE_SCRAP, TIERS[0], "reagent: scrap of rough hide"),
      (HERBS, {**TIERS[1], "4": "moss5", "3": "moss4", "2": "moss3", "5": "hound3"},
       "reagent: bundle of prairie herbs tied with leather"),
      (BONES, TIERS[2], "reagent: bone shards and a flint"),
      (PLUMES, TIERS[3], "reagent: dyed feathers on a beaded cord"))

# --- quest items: a wolf paw, an ambercorn, a kodo horn, a painted well stone ------------------------------------
PAW = """
    ................
    ................
    .....fF..fF.....
    ....fppffppF....
    ..fFfppffppFfF..
    .fppfffffffFppF.
    .fppffffffFFppF.
    ..fFffffffFFfF..
    ...fffppppFFF...
    ...ffppppppFF...
    ...ffppppppFF...
    ....ffppppFF....
    .....fFFFFF.....
    ................
    ................
    ................
"""
AMBERCORN = """
    ................
    ................
    ................
    .......x........
    .....7766.......
    ....7766665.....
    ....6666555.....
    .....43321......
    ....4w33321.....
    ....4433321.....
    ....4333221.....
    .....33221......
    ......221.......
    .......1........
    ................
    ................
"""
HORN = """
    ................
    ................
    ................
    ............a...
    ...........ab...
    ..........abc...
    .........abc....
    ........abcc....
    ......aabccd....
    ....aabbccd.....
    ...abbbccdd.....
    ..6abbccdd......
    ..76bcddd.......
    ...756dd........
    ................
    ................
"""
WELLSTONE = """
    ................
    ................
    ................
    .....aabbb......
    ....abbbbbbc....
    ...abbgbbbbcc...
    ...abggGbbccc...
    ..abbbgbbgbccd..
    ..abbbbbggGccd..
    ..abbbbbbgbccd..
    ..bbbbbbbbcccd..
    ...bbbbcccccd...
    ....cccccddd....
    ................
    ................
    ................
"""
looks("quest_item",
      (PAW, {"f": "azi_hide3", "F": "azi_hide2", "p": "azi_smoke1"}, "quest item: prairie wolf paw"),
      (AMBERCORN, {"7": "brute2", "6": "brute1", "5": "leather3", "x": "azi_wood2",
                   "4": "ore2", "3": "ore1", "2": "tent2", "1": "tent1"}, "quest item: ambercorn"),
      (HORN, TIERS[2], "quest item: kodo horn"),
      (WELLSTONE, {**TIERS[0], **TIERS[3], "a": "azi_stone4", "b": "azi_stone3", "c": "azi_stone2",
                   "d": "azi_stone1"}, "quest item: well stone painted with a turquoise glyph"))

# --- ticket: a Darkmoon Faire prize ticket, notched ends, moon stamp --------------------------------------------
TICKET = """
    ................
    ................
    ................
    ................
    ..444444444433..
    .k43gg3333332k..
    ..4g33333GGG21..
    ..4g3333333321..
    ..4g33333GGG21..
    ..43gg33333321..
    .k43333333332k..
    ..332222222211..
    ................
    ................
    ................
    ................
"""
_TICKET = (
    {"4": "bone4", "3": "bone3", "2": "bone2", "1": "bone1", "g": "bone1", "G": "bone0"},
    {"4": "sand4", "3": "sand3", "2": "sand2", "1": "sand1", "g": "flora2", "G": "flora1"},
    {"4": "flora5", "3": "flora4", "2": "flora3", "1": "flora2", "g": "bone4", "G": "bone3"},
    {"4": "flora4", "3": "flora3", "2": "flora2", "1": "flora1", "g": "gold2", "G": "gold1"},
)
_ticket = grid(TICKET)
_edged = overlay(overlay(_ticket, grid("jjjjjjjjj"), 3, 4), grid("JJJJJJJJJ"), 3, 11)
looks("ticket",
      (_ticket, _TICKET[0], "Darkmoon Faire prize ticket (single)"),
      (_ticket, _TICKET[1], "Darkmoon Faire prize ticket (bundle)"),
      (_ticket, _TICKET[2], "Darkmoon Faire game token ticket"),
      (_edged, _TICKET[3], "Darkmoon Faire greater prize ticket, gilt edge"))

# --- book: a bound journal / pattern book, clasp on the fore-edge ---------------------------------------------------
BOOK = """
    ................
    ................
    ....4444444443..
    ...43333333332..
    ...433337333321.
    ...43337773332k.
    ...433337333321.
    ...43333333332a.
    ...4333333333bc.
    ...43333333332k.
    ...433333333321.
    ...4333333333221
    ...6wwwwwwwwwk1.
    ....55555555551.
    ................
    ................
"""
family("book", BOOK, what="book (pattern / schematic / journal)",
       orn={2: [_put(STUD, 4, 2), _put(STUD, 4, 10)], 3: [_put(BEADS, 12, 11)]})
