"""Azeroth / Mulgore art: monsters. Must satisfy
``wilds.azeroth.manifest.required()["monsters"]`` (see docs/azeroth/mulgore-art-manifest.md)."""

from __future__ import annotations

import math

from ..palette import _named, _ramp
from ..pixelart import Grid, art, blank, grid, outline_grid, overlay
from ..procgen import Canvas
from ..registry import register

_named(azm_snout="#f09a98", azm_snout2="#c46a70")
_ramp("azm_pig", "#4a2228", "#7e4038", "#b0674e", "#d6936c", "#f2c19a")
_ramp("azm_ogre", "#3a261e", "#6b4a36", "#9a6e4c", "#c09468", "#e0bc8c")


def _ol(text: str) -> Grid:
    """Fill-only grid -> grid with the 1px ink outline baked in."""
    return outline_grid(grid(text), "k")


# --- quilboar -------------------------------------------------------------------
# Bristleback quilboar: short, hunched boar-men, tan-pink hide, a huge crest of
# dark quills with bone tips over head and back, pink snout and curled tusks,
# hide loincloth, a spiked club.

QB = {"p": "azm_pig3", "P": "azm_pig2", "Q": "azm_pig1", "n": "azm_snout", "N": "azm_snout2", "q": "azm_pig1",
      "m": "dust1", "M": "dust2", "s": "bone4", "S": "bone2", "t": "tusk", "e": "red1",
      "l": "tent1", "L": "tent0", "h": "rock1", "o": "tent1", "O": "tent0", "x": "white:150"}

QB_UPPER = grid("""
    ................
    ..s..s..........
    ..Ms.Ms.s.......
    .sMm.MmsMmPp....
    .MmmMmmMmPPppp..
    .QmmmmmmmPpeppn.
    .QPmmmmmPPppppN.
    .QPPmmmPPQqtt...
    .QPPPPPPPP......
    .QPPPPPPPP......
    ..QlllLlll......
    ..LlllLLL.......
""")
QB_LEGS = {
    "stand": grid("""
        ...QQ.PP........
        ...QQ.PP........
        ...QQ.QP........
        ...hh.hh........
    """),
    "reach": grid("""
        ...QQ.PP........
        ..QQ...PP.......
        .QQ.....QP......
        .hh......hh.....
    """),
    "pass": grid("""
        ....QQPP........
        ...QQ.PP........
        ...hh.QP........
        ......hh........
    """),
    "reach2": grid("""
        ...PPQQ.........
        ..PP...QQ.......
        .PQ.....QQ......
        .hh......hh.....
    """),
    "pass2": grid("""
        ....PPQQ........
        ....PP.QQ.......
        ....QP.hh.......
        ....hh..........
    """),
    "brace": grid("""
        ...QQ..PP.......
        ..QQ....PP......
        .QQ......QP.....
        .hh.......hh....
    """),
}
# the near arm and club: hanging forward (idle/walk), raised (wind-up), smashed down
QB_ARM_DOWN = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ........pp......
    .......pppP.....
    ........PPpp....
    ..........pp....
""")
QB_ARM_BACK = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ......ppp.......
    ....ppPP........
    ..ppp...........
    ..o.............
    .SOS............
    ..S.............
""")
QB_ARM_SWING = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ........pp...S..
    .......ppppoOOS.
    .............S..
    ................
""")
QB_CLUB = grid("""
    .............S..
    ...........oOOS.
    .............S..
""")
QB_SMEAR = grid("""
    ................
    ..........x.....
    ...........xx...
""")
QB_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ....s.s.s.......
    ...sMsMsMm.Pp...
    ..hQPPPPPmPpkpn.
    .hhQlllPPPPpppN.
    ..QQLllQQPPqtt..
    ........S.oOS...
    ................
""")


def _qb(legs="stand", bob=0, arm="down", dx=0) -> Grid:
    g = overlay(blank(16, 16), QB_LEGS[legs], 0, 11)
    up = overlay(QB_UPPER, {"back": QB_ARM_BACK[:12], "swing": QB_ARM_SWING}.get(arm, QB_ARM_DOWN))
    g = overlay(g, up, dx, bob)
    if arm == "down":
        g = overlay(g, QB_CLUB, dx, 10 + bob)
    elif arm == "back":
        g = overlay(g, QB_ARM_BACK[12:], dx, 12 + bob)
    g = outline_grid(g, "k")
    if arm == "swing":
        g = overlay(g, QB_SMEAR, dx, 9 + bob)
    return g


QB_IDLE = [_qb(), _qb(bob=1)]
QB_MOVE = [_qb("reach"), _qb("pass", bob=-1), _qb("reach2"), _qb("pass2", bob=-1)]
QB_ATTACK = [_qb("stand", arm="back"), _qb("brace", bob=1, arm="swing")]
register("az.creature.quilboar.idle", art(*QB_IDLE, legend=QB, fps=2, note="Bristleback quilboar, breathing"))
register("az.creature.quilboar.move", art(*QB_MOVE, legend=QB, fps=8, note="quilboar trot"))
register("az.creature.quilboar.attack", art(*QB_ATTACK, legend=QB, fps=8, note="quilboar: club swung back, upswing strike"))
register("az.creature.quilboar.dead", art(QB_DEAD, legend=QB, note="quilboar fallen on its side"))


# --- gnoll ------------------------------------------------------------------------
# Palemane gnoll: lean, hunched hyena-man with pale blue-grey spotted fur, a dark
# bristly mane, long muzzle and round ears, yellow eyes, brown leather harness,
# a tall spear.

GN = {"f": "grey4", "F": "grey3", "g": "grey2", "d": "grey1", "m": "rock1", "M": "rock2",
      "e": "hazard", "z": "grey2", "Z": "rock1", "t": "bone4",
      "l": "rust3", "L": "rust2", "b": "rust1",
      "o": "tent2", "O": "tent1", "i": "steel5", "I": "steel3", "x": "white:150"}

GN_UPPER = grid("""
    ................
    .....ff.........
    ....MfFf........
    ...MMfFfff......
    ..MmmFfefffff...
    ..MmFFffFFFFzZ..
    ..mmgFFggtgt....
    .MmdFFgFF.......
    .mFFldlFFg......
    ..gFFdllFg......
    ..gdFFgLbg......
    ...gFFggg.......
""")
GN_LEGS = {
    "stand": grid("""
        ...ggg.FFf......
        ...dg..Ff.......
        ....dg..Ff......
        ...ddd.FFf......
    """),
    "reach": grid("""
        ...ggg.FFf......
        ..dg....Ff......
        .dg......Ff.....
        .dd.....FFf.....
    """),
    "pass": grid("""
        ...gggFFf.......
        ....dgFf........
        .....ddFf.......
        ......FFf.......
    """),
    "reach2": grid("""
        ...FFf.ggg......
        ..Ff....dg......
        .Ff......dg.....
        .Ff.....ddd.....
    """),
    "pass2": grid("""
        ...FFfggg.......
        ....Ff.dg.......
        .....Ff.dg......
        .......ddd......
    """),
    "brace": grid("""
        ...ggg..FFf.....
        ..dg.....Ff.....
        .dg.......Ff....
        .dd......FFf....
    """),
}
GN_ARM_HOLD = grid("""
    ..............i.
    .............iI.
    ..............o.
    ..............o.
    ..............o.
    ..............o.
    ..............o.
    ..............o.
    .........FFFFfo.
    ..........gggfo.
    ..............O.
    ..............O.
    ..............O.
    ..............O.
    ..............O.
""")
GN_ARM_BACK = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ......FFgf......
    OOoooooooofiI...
    ................
""")
GN_ARM_THRUST = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ........FFgf....
    ....OOoooooooiI.
    ................
""")
GN_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...MmMmMff......
    .dFFlldFFfFfff..
    .dgFFdLbgFFkffZ.
    .ddgFFgggFgzzZ..
    ..OOooooooiI....
    ................
""")


def _gn(legs="stand", bob=0, arm="hold", dx=0) -> Grid:
    g = overlay(blank(16, 16), GN_LEGS[legs], 0, 11)
    g = overlay(g, GN_UPPER, dx, bob)
    g = overlay(g, {"back": GN_ARM_BACK, "thrust": GN_ARM_THRUST}.get(arm, GN_ARM_HOLD), dx, bob)
    return outline_grid(g, "k")


GN_IDLE = [_gn(), _gn(bob=1)]
GN_MOVE = [_gn("reach"), _gn("pass", bob=-1), _gn("reach2"), _gn("pass2", bob=-1)]
GN_ATTACK = [_gn("stand", arm="back", dx=-1), _gn("brace", bob=1, arm="thrust", dx=1)]
register("az.creature.gnoll.idle", art(*GN_IDLE, legend=GN, fps=2, note="Palemane gnoll with a spear"))
register("az.creature.gnoll.move", art(*GN_MOVE, legend=GN, fps=8, note="gnoll lope"))
register("az.creature.gnoll.attack", art(*GN_ATTACK, legend=GN, fps=8, note="gnoll: draw back, spear thrust"))
register("az.creature.gnoll.dead", art(GN_DEAD, legend=GN, note="gnoll fallen, spear dropped"))


# --- harpy ------------------------------------------------------------------------
# Windfury harpy: a slender blue-skinned woman whose arms are great blue wings,
# wild dark-blue hair, a feathered skirt, and thin bird legs ending in black
# talons. She hovers on beating wings.

HP = {"s": "water5", "S": "glass4", "e": "hazard", "h": "flora3", "H": "flora2",
      "W": "water4", "w": "water3", "v": "water2", "V": "water1",
      "l": "grey2", "c": "rock1", "C": "bone4", "x": "white:150"}

HP_BODY = grid("""
    ................
    ................
    ........hhh.....
    .......hhsss....
    .......hssesS...
    .......hHsss....
    ......hH.sS.....
    ........sSs.....
    ........ssS.....
    ........wWw.....
    ........vwwv....
    ........vv.v....
    ........l..l....
    ........l..l....
    .......cc..cc...
    ................
""")
HP_WING_FAR = {
    "up": grid("""
        .W..............
        .WW.............
        .wWW............
        ..wWW...........
        ..vwWW..........
        ...vwWWW........
        ....vwWWW.......
        .....vwww.......
    """),
    "mid": grid("""
        ................
        ................
        ................
        ................
        WWWW............
        wwWWWWWW........
        vvwwwWWWW.......
        .vvwwwww........
    """),
    "down": grid("""
        ................
        ................
        ................
        ................
        ................
        .....WWWWW......
        ...WWWwwwWW.....
        .WWwwwvvv.......
        Wwwvvv..........
        vvv.............
    """),
}
HP_WING_NEAR = {
    "up": grid("""
        ..............W.
        ..............W.
        .............WW.
        .............Ww.
        ............WWv.
        ...........WWv..
        ..........WWv...
        .........Wwv....
    """),
    "mid": grid("""
        ................
        ................
        ................
        ................
        ................
        .........WWWWW..
        ........WWWwwwW.
        .........wwvvv..
    """),
    "down": grid("""
        ................
        ................
        ................
        ................
        ................
        ................
        ........WWW.....
        .........WwWW...
        ..........wwWW..
        ...........vwwW.
        .............vv.
    """),
}


HP_KICK = grid("""
    .........ll.....
    ..........lll...
    ...........cCc..
    ............c...
""")
HP_TUCK = grid("""
    ........ll.l....
    .........lcc....
    ........cc......
    ................
""")
HP_SMEAR = grid("""
    ..............x.
    ...............x
    ...............x
    ..............x.
""")
HP_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .W.........hhh..
    WWWw.....hhssss.
    wwWWwvwwWsSsksS.
    .vvwWWwvwwSss...
    ...vvwwWWWw.lcc.
    ................
""")


def _hp(wings="mid", lift=0, legs=None, dx=0) -> Grid:
    g = blank(16, 16)
    g = overlay(g, HP_WING_FAR[wings], dx, -lift)
    body = HP_BODY if legs is None else overlay(HP_BODY[:12] + blank(16, 4), legs, 0, 12)
    g = overlay(g, body, dx, -lift)
    g = overlay(g, HP_WING_NEAR[wings], dx, -lift)
    return outline_grid(g, "k")


HP_IDLE = [_hp("up"), _hp("mid", lift=1)]
HP_MOVE = [_hp("up", lift=1), _hp("mid", lift=2), _hp("down", lift=2), _hp("mid", lift=1)]
HP_ATTACK = [_hp("up", lift=2, legs=HP_TUCK, dx=-1),
             overlay(_hp("down", lift=0, legs=HP_KICK, dx=1), HP_SMEAR, 0, 10)]
register("az.creature.harpy.idle", art(*HP_IDLE, legend=HP, fps=3, note="Windfury harpy, wings beating"))
register("az.creature.harpy.move", art(*HP_MOVE, legend=HP, fps=8, note="harpy flying: full wingbeat"))
register("az.creature.harpy.attack", art(*HP_ATTACK, legend=HP, fps=8,
                                         note="harpy: rise with talons tucked, dive and rake"))
register("az.creature.harpy.dead", art(HP_DEAD, legend=HP, note="harpy fallen, wings sprawled"))


# --- ogre -------------------------------------------------------------------------
# Enforcer ogre: a hulking, hunched brute (two tiles tall) with olive-tan hide,
# a small head with a topknot and tusks, iron shoulder plate, hide loincloth and
# a studded wooden club.

OG = {"o": "azm_ogre4", "O": "azm_ogre3", "Q": "azm_ogre2", "q": "azm_ogre1",
      "b": "azm_ogre4", "e": "bone4", "K": "azm_ogre0", "t": "tusk", "h": "hair_black", "H": "leather2",
      "a": "steel4", "A": "steel3", "z": "steel2",
      "l": "tent1", "L": "tent0", "f": "leather2", "F": "leather1",
      "c": "brute2", "C": "brute1", "n": "brute0", "i": "grey4", "x": "white:150"}

OG_UPPER = grid("""
    ................
    ..........h.....
    .........hH.....
    ........oOOOo...
    .......oOOOOOo..
    .......QOKKKKO..
    ...aAa.QOOOeOOn.
    ..aAaaaQOtOOtO..
    ..aazaAqQOOOOO..
    ..QOOOOOqQQQQ...
    .QOOOOOOOOOOO...
    .QOOOOOObbbOOO..
    .QOOOOObbbbbOO..
    .qQOOOObbbbbOO..
    .qQQOOOObbbOO...
    ..lllLllllllL...
    ..LlllLllllL....
""")
OG_LEGS = {
    "stand": grid("""
        ....QQO..OOO....
        ....qQO..QOO....
        ....qQQ..QOO....
        ....qQQ..QQO....
        ...ffff.fFFf....
        ...FFFF.FFFF....
    """),
    "reach": grid("""
        ...QQO....OOO...
        ...qQO....QOO...
        ..qQQ......QOO..
        ..qQQ......QQO..
        .ffff.....fFFf..
        .FFFF.....FFFF..
    """),
    "pass": grid("""
        .....QQOOO......
        .....qQOQO......
        ....qQQ.QO......
        ....ffffQQO.....
        ....FFFfFFf.....
        ........FFFF....
    """),
    "reach2": grid("""
        ...OOO....QQO...
        ...QOO....qQO...
        ..QOO......qQQ..
        ..QQO......qQQ..
        .fFFf.....ffff..
        .FFFF.....FFFF..
    """),
    "pass2": grid("""
        .....OOOQQ......
        .....QOQqQ......
        ....QOO.qQQ.....
        ....QQO.ffff....
        ....fFFfFFFF....
        ....FFFF........
    """),
    "brace": grid("""
        ...QQO.....OOO..
        ...qQO.....QOO..
        ..qQQ.......QOO.
        ..qQQ.......QQO.
        .ffff......fFFf.
        .FFFF......FFFF.
    """),
}
OG_ARM = {
    "down": grid("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ........kOOO....
        .......kOOOOO...
        .......kQOOOO...
        ........kQOOO...
        ........kQOOO..i
        .........kOOoci.
        .........kooCcC.
        ..........kQCci.
        ...........iCcC.
        ............icCi
        .............nC.
    """),
    "up": grid("""
        ..i.............
        .cCci...........
        .CccC...........
        ..nCcc..........
        ....CcO.........
        .....OOO........
        ......OOO.......
        .......OO.......
        .......OO.......
        ........O.......
    """),
    "slam": grid("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .........OOO....
        ........OOOOOO..
        ........QQOOOO..
        ............OOc.
        ............Qcc.
        .............Cc.
        ............iCcC
        .............cCc
        .............nCi
    """),
}
OG_SMEAR = grid("""
    ..........x.....
    ............x...
    .............x..
    ..............x.
    ..............x.
""")
OG_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ........aa......
    ..ff...aAzaOOo..
    .fFQQQOOOOOOOOoh
    .FFqQQllObbOOkOH
    ..FFQQLlObbbOtt.
    ...ffQQllOOOOO..
    ...FF.ccCcC.....
    .....icCccCi....
    ................
""")


def _og(legs="stand", bob=0, arm="down", dx=0) -> Grid:
    g = overlay(blank(16, 24), OG_LEGS[legs], 0, 17)
    if arm == "up":
        g = overlay(g, OG_ARM["up"], dx - 1, bob)
    g = overlay(g, OG_UPPER, dx, bob)
    if arm != "up":
        g = overlay(g, OG_ARM[arm], dx, bob)
    g = outline_grid(g, "k")
    if arm == "slam":
        g = overlay(g, OG_SMEAR, 0, 9)
    return g


OG_IDLE = [_og(), _og(bob=1)]
OG_MOVE = [_og("reach", bob=1), _og("pass"), _og("reach2", bob=1), _og("pass2")]
OG_ATTACK = [_og("stand", bob=-1, arm="up", dx=-1), _og("brace", bob=2, arm="slam")]
register("az.creature.ogre.idle", art(*OG_IDLE, legend=OG, fps=1.5, note="ogre enforcer, heavy breathing"))
register("az.creature.ogre.move", art(*OG_MOVE, legend=OG, fps=6, note="ogre stomp"))
register("az.creature.ogre.attack", art(*OG_ATTACK, legend=OG, fps=6, note="ogre: club overhead, slam"))
register("az.creature.ogre.dead", art(OG_DEAD, legend=OG, note="ogre fallen on its back"))


# --- restless spirits ---------------------------------------------------------------
# Translucent undead that float a pixel or two above the grass: the outline and
# every fill carry alpha, eyes glow. ghost = pale cyan tortured spirit reaching
# out; wraith = hooded violet shade with long claws; haunt = smoky black-green
# skull-faced fiend trailing a wisp.


def _spirit(upper: Grid, tail: Grid, bob: int = 0, h: int = 24, ty: int = 15) -> Grid:
    g = overlay(blank(16, h), tail, 0, ty + bob)
    g = overlay(g, upper, 0, bob)
    return outline_grid(g, "k")


def _fade(g: Grid, keep: str) -> Grid:
    """Dissolve: only the characters in ``keep`` survive (for dead frames)."""
    return tuple("".join(c if c in keep else "." for c in row) for row in g)


GH = {"k": "water2:190", "l": "water5:170", "L": "water4:160", "h": "white:200",
      "e": "glowcyan", "m": "water2:200", "d": "water4:90", "D": "water5:70"}

GH_UPPER = grid("""
    ................
    ................
    ................
    ................
    ......hhh.......
    .....hhlll......
    .....hlllll.....
    .....lllelel....
    .....llllll.....
    ......lmlL......
    .....hlllL......
    ...hhlllllll....
    ..hl.llllL.lll..
    ..l..llllL...ll.
    ..l..lllll....l.
    .....lllll......
""")
GH_TAILS = [grid(t) for t in ("""
    .....lllL.......
    .....llL........
    ....llL.........
    ...llL..........
    ...lL...........
    ....L...........
    ................
""", """
    .....lllL.......
    ......llL.......
    ......lL........
    .....lL.........
    ....lL..........
    ...lL...........
    ...L............
""", """
    .....lllL.......
    .....llL........
    .....lL.........
    ......lL........
    .....lL.........
    ....lL..........
    ....L...........
""", """
    .....lllL.......
    ....lllL........
    ...llL..........
    ..lL............
    ..lL............
    ...L............
    ................
""")]
GH_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ......D.........
    ........d.......
    .....d....D.....
    ...D..hdd.......
    .......D..d.....
    ....dddhhd......
    ...dhhhhhhd..D..
    ..dhDdddDhhd....
    ...dhhhhhhd.....
    ....ddhhdd......
    ......dd........
    ................
    ................
""")
register("az.creature.ghost.idle", art(_spirit(GH_UPPER, GH_TAILS[0], 1), _spirit(GH_UPPER, GH_TAILS[2], 0),
                                       legend=GH, fps=2, note="malicious spirit, hovering"))
register("az.creature.ghost.move", art(*(_spirit(GH_UPPER, t, b) for t, b in zip(GH_TAILS, (1, 0, 0, 1))),
                                       legend=GH, fps=6, note="ghost drifting, tail streaming"))
register("az.creature.ghost.dead", art(GH_DEAD, legend=GH, note="ghost dispersed: a fading wisp"))

WR = {"k": "flora0:210", "r": "flora2:190", "R": "flora1:200", "q": "flora3:180", "s": "hive0:220",
      "e": "glowviolet", "c": "bone3:220", "d": "flora2:110", "D": "flora3:80"}

WR_UPPER = grid("""
    ................
    ................
    ................
    .......qqq......
    ......qrrrq.....
    .....qrrsssr....
    .....qrsseser...
    .....rrsssss....
    .....rrrssr.....
    ....qrrrrrR.....
    ...qrrrrqrrR....
    ..qrrrRrqqqrr...
    ..rrRRRrrRrrcc..
    .rrR.RrrrR..c.c.
    .rR..rrrrR......
    .r...RrrrR......
""")
WR_UPPER_CLAW = grid("""
    ................
    ................
    ................
    .......qqq......
    ......qrrrq.....
    .....qrrsssr....
    .....qrsseser...
    .....rrsssss...c
    .....rrrssr...cc
    ....qrrrrrR..rc.
    ...qrrrrqrrRrr..
    ..qrrrRrqqqrr...
    ..rrRRRrrRrR....
    .rrR.RrrrR......
    .rR..rrrrR......
    .r...RrrrR......
""")
WR_UPPER_SLASH = grid("""
    ................
    ................
    ................
    ................
    .......qqq......
    ......qrrrq.....
    .....qrrsssr....
    .....qrsseser...
    .....rrsssss....
    ....qrrrrrr.....
    ...qrrrrqrrrr...
    ..qrrrRrqqqrrrr.
    ..rrRRRrrRrR.ccc
    .rrR.RrrrR....c.
    .rR..rrrrR......
    .r...RrrrR......
""")
WR_SMEAR = grid("""
    ..............x.
    ...............x
    ...............x
    ..............x.
""")
WR["x"] = "glowviolet:120"
WR_TAILS = [grid(t) for t in ("""
    ....RrrrrR......
    ...RrrRrrrR.....
    ...rR.rRrrR.....
    ..rR..R.rR......
    ..R.....R.......
    ................
    ................
""", """
    ....RrrrrR......
    ...RrrrRrrR.....
    ..RrR.rRrR......
    ..r..rR.rR......
    .....R..R.......
    ................
    ................
""", """
    ....RrrrrR......
    ...RrRrrrrR.....
    ...R.rRrR.R.....
    ....rR.rR.......
    ....R...R.......
    ................
    ................
""", """
    ....RrrrrR......
    ...RrrRrrR......
    ..RrR.rrR.R.....
    ..R..rR.rR......
    ....R...R.......
    ................
    ................
""")]
WR_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .......D........
    .....d...D......
    ...D...d........
    ......d..d......
    ....dd.D........
    ...drrd..d......
    ..drRRrrrd.D....
    .drRssrRrrd.....
    ..drrsesrrdd....
    ...ddrrrrdd.....
    .....dddd.......
    ................
""")
register("az.creature.wraith.idle", art(_spirit(WR_UPPER, WR_TAILS[0], 1), _spirit(WR_UPPER, WR_TAILS[2], 0),
                                        legend=WR, fps=2, note="wraith, hooded shade, hovering"))
register("az.creature.wraith.move", art(*(_spirit(WR_UPPER, t, b) for t, b in zip(WR_TAILS, (1, 0, 0, 1))),
                                        legend=WR, fps=6, note="wraith gliding, tattered robe streaming"))
register("az.creature.wraith.attack", art(_spirit(WR_UPPER_CLAW, WR_TAILS[1], 0),
                                          overlay(_spirit(WR_UPPER_SLASH, WR_TAILS[3], 1), WR_SMEAR, 0, 9),
                                          legend=WR, fps=8, note="wraith: claws raised, raking slash"))
register("az.creature.wraith.dead", art(WR_DEAD, legend=WR, note="wraith collapsed into a dissolving robe"))

HN = {"k": "hive0:220", "s": "hive1:200", "S": "hive2:180", "b": "bone3:230", "B": "bone2:230",
      "e": "hivegl", "t": "bone4:230", "d": "hive2:100", "D": "hive3:70"}

HN_UPPER = grid("""
    ................
    ................
    ................
    ................
    ................
    ......SSS.......
    ....SSsssS......
    ...SssSbbbb.....
    ..SsssbbebbB....
    ..sssSbBbbbb....
    ..SsssSBtBtB....
    ...ssssSt.t.....
    ...sssssbBbB....
    ....sssssSs.....
    ...SssSsssSs....
    ...ss.sssS.ss...
""")
HN_TAILS = [grid(t) for t in ("""
    ....sssSs.......
    ...sssSs........
    ..ssSs..........
    .sSs............
    .ss.............
    ..S.............
    ................
""", """
    ....sssSs.......
    ....ssSs........
    ...ssS..........
    ..sSs...........
    ..sS............
    .sS.............
    .S..............
""", """
    ....sssSs.......
    ...sssS.........
    ...sSs..........
    ...sS...........
    ..sS............
    ..S.............
    ................
""", """
    ....sssSs.......
    ...ssSs.........
    ..sss...........
    .sS.............
    .S..............
    .S..............
    ................
""")]
HN_DEAD = grid("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...D....d.......
    .....d.....D....
    ..d...D..d......
    ....dd...D......
    ...dssd.........
    ..dsSsbbbbd.....
    .dsssbbkbbBd....
    ..ddsSBtBtBd....
    ....ddddddd.....
    ................
""")
register("az.creature.haunt.idle", art(_spirit(HN_UPPER, HN_TAILS[0], 1), _spirit(HN_UPPER, HN_TAILS[2], 0),
                                       legend=HN, fps=2, note="haunt: smoky skull-faced shade"))
register("az.creature.haunt.move", art(*(_spirit(HN_UPPER, t, b) for t, b in zip(HN_TAILS, (1, 0, 0, 1))),
                                       legend=HN, fps=6, note="haunt streaking, smoke trailing"))
register("az.creature.haunt.dead", art(HN_DEAD, legend=HN, note="haunt: a fallen skull in fading smoke"))


# --- shaded forms (rock, bark, hide) ----------------------------------------------


def _ell(cx: float, cy: float, rx: float, ry: float) -> set:
    return {(x, y) for y in range(int(cy - ry) - 1, int(cy + ry) + 2)
            for x in range(int(cx - rx) - 1, int(cx + rx) + 2)
            if ((x + 0.5 - cx) / rx) ** 2 + ((y + 0.5 - cy) / ry) ** 2 <= 1.0}


def _box(x0: int, y0: int, x1: int, y1: int) -> set:
    return {(x, y) for y in range(y0, y1 + 1) for x in range(x0, x1 + 1)}


def _shade(c: Canvas, pts: set, light: str, main: str, dark: str) -> None:
    """One form lit from the top-left: top/left rim light, bottom/right rim dark."""
    for (x, y) in pts:
        if not (0 <= x < c.w and 0 <= y < c.h):
            continue
        if (x, y - 1) not in pts or (x - 1, y) not in pts and (x - 1, y - 1) not in pts:
            ch = light
        elif (x, y + 1) not in pts or (x + 1, y) not in pts:
            ch = dark
        else:
            ch = main
        c.set(x, y, ch)


# --- earth elemental -----------------------------------------------------------------
# Agitated earth spirit: a lumbering golem of Mulgore's red-brown stone, boulder
# fists hovering at its sides, molten-gold eyes and a glowing crack in its chest.

EE = {"4": "dust5", "3": "dust4", "2": "dust3", "1": "dust2", "0": "dust1",
      "e": "fire4", "g": "fire3", "G": "ore1"}


def _stack(w: int, h: int, forms) -> Grid:
    """Separately outlined shaded forms, back to front: (pts, light, main, dark)."""
    g = blank(w, h)
    for pts, light, main, dark in forms:
        c = Canvas(w, h)
        _shade(c, pts, light, main, dark)
        g = overlay(g, outline_grid(c.grid(), "k"))
    return g


def _earth(bob: int = 0, step: int = 0, swing: int = 0, dead: bool = False) -> Grid:
    b = bob
    if dead:
        g = _stack(16, 24, [(_ell(cx, cy, rx, ry), "3", "2", "1") for (cx, cy, rx, ry) in (
            (4.5, 20.5, 3.2, 2.2), (10.5, 20.8, 3.6, 2.4), (13.8, 21.5, 1.6, 1.3), (1.8, 21.6, 1.4, 1.2),
            (7.5, 18.0, 2.6, 2.0))])
        return overlay(g, grid("G"), 7, 18)
    g = _stack(16, 24, [
        (_ell(3.0 - swing, 16.5 + b, 1.9, 1.9), "2", "1", "0"),                   # far fist
        (_box(4, 18 + b - (step > 0), 6, 22 - (step > 0)), "2", "1", "0"),        # far leg
        (_ell(3.8, 10.8 + b, 2.3, 2.1), "2", "1", "0"),                           # far shoulder
        (_ell(8.0, 13.6 + b, 4.4, 5.0), "3", "2", "1"),                           # torso
        (_box(9, 18 + b - (step < 0), 11, 22 - (step < 0)), "3", "2", "1"),       # near leg
        (_ell(9.2, 6.8 + b, 2.6, 2.3), "4", "3", "1"),                            # head
        (_ell(12.0, 10.2 + b, 2.4, 2.2), "4", "3", "1"),                          # near shoulder
        (_ell(12.8 + swing, 16.4 + b, 2.2, 2.0), "4", "3", "1"),                  # near fist
    ])
    glow = blank(16, 24)
    for (x, y, ch) in ((10, 6, "e"), (11, 6, "e"), (7, 12, "g"), (8, 13, "g"), (7, 14, "g"),
                       (8, 15, "G"), (6, 11, "G")):
        glow = overlay(glow, grid(ch), x, y + b)
    return overlay(g, glow)


register("az.creature.earth_elemental.idle", art(_earth(), _earth(bob=1), legend=EE, fps=1.5,
                                                 note="earth spirit, grinding breath"))
register("az.creature.earth_elemental.move",
         art(_earth(step=1, swing=1), _earth(bob=-1), _earth(step=-1, swing=-1), _earth(bob=-1),
             legend=EE, fps=6, note="earth spirit lumbering"))
register("az.creature.earth_elemental.dead", art(_earth(dead=True), legend=EE, note="a heap of stones"))


# --- skeleton -----------------------------------------------------------------------
# A risen adventurer's bones: yellowed skull with dark sockets, rib cage, a rusty
# sword still in hand.

SK = {"b": "bone4", "B": "bone3", "d": "bone2", "D": "bone1", "e": "fire3",
      "s": "rust3", "S": "rust2", "g": "grey4"}

SK_UPPER = grid("""
    ................
    ................
    .......bbbb.....
    ......bbbbbb....
    ......bBbKbK....
    ......Bbbbbd....
    .......dbBd.....
    ........B.......
    ......bbBbb.....
    .....d.dBd.b....
    .....d.bDb..b...
    .....B.dBd..bg..
    ......ddBdd..g..
""")
SK_SWORD = grid("""
    .............g..
    .............g..
    .............g..
    .............g..
    ............sSs.
""")
SK_LEGS = {
    "stand": grid("""
        .......d.b......
        .......d.b......
        ......dd.bb.....
    """),
    "reach": grid("""
        ......d...b.....
        .....d.....b....
        ....dd.....bb...
    """),
    "pass": grid("""
        .......db.......
        .......d.b......
        ......dd.bb.....
    """),
    "reach2": grid("""
        ......b...d.....
        .....b.....d....
        ....bb.....dd...
    """),
}


def _sk(legs="stand", bob=0) -> Grid:
    g = overlay(blank(16, 16), SK_LEGS[legs], 0, 12)
    g = overlay(g, SK_UPPER, 0, bob)
    g = overlay(g, SK_SWORD, 0, 6 + bob)
    return outline_grid(g, "k")


SK_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ............bbb.
    ..b.d.dBd..bdbd.
    .bd..BdBdB.Bbbb.
    ..b.d.dBd..gggg.
    ................
""")
register("az.creature.skeleton.idle", art(_sk(), _sk(bob=1), legend=SK, fps=1.5, note="risen skeleton, rattling"))
register("az.creature.skeleton.move", art(_sk("reach"), _sk("pass", bob=-1), _sk("reach2"), _sk("pass", bob=-1),
                                          legend=SK, fps=7, note="skeleton shambling"))
register("az.creature.skeleton.dead", art(SK_DEAD, legend=SK, note="a heap of bones and a rusty blade"))


# --- homunculus ----------------------------------------------------------------------
# A Legion-made homunculus: a squat, stitched little fiend of blood-red flesh,
# big fel-green eyes, stubby horns, bat ears and long clawed arms.

HM = {"o": "red2", "O": "red1", "Q": "red0", "e": "glowlime", "h": "bone3", "H": "bone2",
      "m": "ink2", "c": "bone4", "s": "fire2"}

HM_UPPER = grid("""
    ................
    ................
    ................
    ..........h.....
    .......O.hH.....
    ......OOoooo....
    ......QOoeoeo...
    ......QOoooooo..
    .......QOmsmO...
    .....OoOQOOO....
    ....QOoooOo.....
    ...QOsoooOOo....
    ...c.QoOoO.Oo...
    .....QQOOQ..cc..
""")
HM_LEGS = {
    "stand": grid("""
        .....QQ.OO......
        ....QQ..OOo.....
    """),
    "reach": grid("""
        ....QQ...OO.....
        ...QQ.....OOo...
    """),
    "pass": grid("""
        ......QQOO......
        ......QOOo......
    """),
    "reach2": grid("""
        ....OO...QQ.....
        ...OOo....QQ....
    """),
}


def _hm(legs="stand", bob=0) -> Grid:
    g = overlay(blank(16, 16), HM_LEGS[legs], 0, 13)
    g = overlay(g, HM_UPPER, 0, bob)
    return outline_grid(g, "k")


HM_DEAD = _ol("""
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..........h.....
    ...cQO...OoooH..
    ..QOoooOOQokokO.
    .QQOsooOOQOmsmO.
    ................
""")
register("az.creature.homunculus.idle", art(_hm(), _hm(bob=1), legend=HM, fps=2, note="homunculus, twitching"))
register("az.creature.homunculus.move", art(_hm("reach"), _hm("pass", bob=-1), _hm("reach2"), _hm("pass", bob=-1),
                                            legend=HM, fps=8, note="homunculus scuttling"))
register("az.creature.homunculus.dead", art(HM_DEAD, legend=HM, note="homunculus sprawled, eyes dark"))


# --- tentacle ------------------------------------------------------------------------
# Dark tendril: a void tentacle thrashing up out of a black-violet rift, pale
# pink suckers along its inner curve.

TN = {"3": "hive4", "2": "hive3", "1": "hive2", "0": "hive1", "v": "hive0", "V": "ink2",
      "s": "spore4", "g": "glowviolet"}


def _tentacle(sway: float, lift: float = 0.0, dead: bool = False) -> Grid:
    pool = _ell(8.0, 14.3, 5.2, 1.5)
    body, suck = set(), []
    n = 26
    x, y = 7.5, 13.8
    for i in range(n):
        t = i / (n - 1)
        if dead:
            x, y, r = 8.0 + t * 7.0, 13.2 - math.sin(t * math.pi) * 1.2, 1.9 - 1.3 * t
        else:
            heading = -math.pi / 2 + sway * (0.35 * math.sin(t * math.pi) + 1.6 * t ** 3)
            step = (12.0 + lift) / n
            x, y = x + math.cos(heading) * step, y + math.sin(heading) * step
            r = 1.9 - 1.4 * t
        body |= _ell(x, y, r, r)
        if i % 5 == 2:
            suck.append((int(x + r * 0.5 * (1 if sway >= 0 else -1)), int(y)))
    g = _stack(16, 16, [(pool, "0", "v", "V"), (body - pool if not dead else body, "3", "2", "1")])
    for (x, y) in suck:
        if 0 <= x < 16 and 0 <= y < 16 and g[y][x] in "123":
            g = overlay(g, grid("s"), x, y)
    for (x, y) in ((5, 14), (10, 14)):
        g = overlay(g, grid("g"), x, y)
    return g


register("az.creature.tentacle.idle", art(_tentacle(-0.5), _tentacle(0.6), legend=TN, fps=2,
                                          note="dark tendril swaying over its rift"))
register("az.creature.tentacle.move", art(_tentacle(-0.9), _tentacle(-0.2, 1.0), _tentacle(0.9),
                                          _tentacle(0.2, -1.0), legend=TN, fps=6, note="dark tendril thrashing"))
register("az.creature.tentacle.dead", art(_tentacle(0, dead=True), legend=TN, note="tendril slumped from its rift"))


# --- n'raqi ---------------------------------------------------------------------------
# N'raqi: a hulking, hunched servant of the Old Gods, deep indigo hide, a knot of
# violet feelers hanging where its mouth should be, a cluster of glowing eyes and
# long taloned arms.

NQ = {"3": "denim3", "2": "denim2", "1": "denim1", "0": "denim0",
      "t": "spore3", "T": "spore2", "e": "glowcyan", "c": "bone3"}


def _nraqi(bob: int = 0, step: int = 0, swing: int = 0) -> Grid:
    b = bob
    g = _stack(16, 24, [
        (_ell(3.2 - swing * 0.5, 15.0 + b, 1.6, 2.6), "1", "0", "0"),              # far arm
        (_box(4, 17 + b - (step > 0), 6, 22 - (step > 0)), "1", "0", "0"),        # far leg
        (_ell(7.2, 12.8 + b, 4.9, 5.4), "3", "2", "1"),                           # torso + hump
        (_box(8, 17 + b - (step < 0), 10, 22 - (step < 0)), "2", "1", "0"),       # near leg
        (_ell(11.2, 7.0 + b, 2.7, 2.5), "3", "2", "1"),                           # head
        (_ell(11.2 + swing * 0.5, 11.8 + b, 1.8, 2.2), "3", "2", "1"),            # near upper arm
        (_ell(12.6 + swing, 15.2 + b, 1.5, 2.0), "3", "2", "1"),                  # near forearm
    ])
    extra = blank(16, 24)
    feel = ((11, 9, "t"), (11, 10, "T"), (11, 11, "t"), (12, 9, "t"), (12, 10, "t"), (12, 11, "T"),
            (12, 12, "t"), (13, 9, "t"), (13, 10, "T"), (14, 11, "t"), (10, 10, "T"), (10, 11, "t"))
    for (x, y, ch) in feel:
        extra = overlay(extra, grid(ch), x, y + b)
    for (x, y) in ((11, 6), (13, 6), (12, 5), (10, 7)):
        extra = overlay(extra, grid("e"), x, y + b)
    fx = int(12.6 + swing)
    extra = overlay(extra, grid(("c.c", ".c.")), fx - 1, 17 + b)
    return outline_grid(overlay(g, extra), "k")


NQ_DEAD = _stack(16, 24, [
    (_ell(5.0, 20.5, 4.6, 2.2), "3", "2", "1"),
    (_ell(11.5, 20.8, 2.6, 2.0), "3", "2", "1"),
    (_box(1, 21, 3, 22), "1", "0", "0"),
])
NQ_DEAD = overlay(NQ_DEAD, grid(("tT.", "TtT")), 13, 20)
register("az.creature.nraqi.idle", art(_nraqi(), _nraqi(bob=1), legend=NQ, fps=1.5,
                                       note="n'raqi, feelers twitching"))
register("az.creature.nraqi.move", art(_nraqi(step=1, swing=1), _nraqi(bob=-1), _nraqi(step=-1, swing=-1),
                                       _nraqi(bob=-1), legend=NQ, fps=6, note="n'raqi lurching"))
register("az.creature.nraqi.dead", art(NQ_DEAD, legend=NQ, note="n'raqi slumped, eyes dark"))


# --- treant and ancient ------------------------------------------------------------------
# Tree-folk of the prairie groves: bark-brown bodies, root feet, branch arms with
# twig fingers, a crown of Mulgore-green leaves and softly glowing green eyes.

TR = {"b": "rust4", "B": "rust3", "c": "rust2", "C": "rust1", "d": "rust0",
      "l": "ork4", "L": "ork3", "m": "ork2", "M": "ork1",
      "e": "glowlime", "o": "ink2", "f": "spore4", "x": "white:150"}


def _seg(x0: float, y0: float, x1: float, y1: float, r0: float, r1: float | None = None) -> set:
    """A thick tapered line: circles from (x0, y0) r0 to (x1, y1) r1."""
    r1 = r0 if r1 is None else r1
    n = max(2, int(math.hypot(x1 - x0, y1 - y0) * 2) + 1)
    pts: set = set()
    for i in range(n):
        t = i / (n - 1)
        r = r0 + (r1 - r0) * t
        pts |= _ell(x0 + (x1 - x0) * t, y0 + (y1 - y0) * t, max(r, 0.55), max(r, 0.55))
    return pts


def _treant(bob: int = 0, step: int = 0, arm: str = "down") -> Grid:
    b = bob
    far_arm = _seg(12, 10 + b, 7, 14 + b, 1.3, 0.8) | _seg(7, 14 + b, 5, 17 + b, 0.8, 0.6)
    fingers_far = _seg(5, 17 + b, 3, 18 + b, 0.55) | _seg(5, 17 + b, 5, 19 + b, 0.55)
    if arm == "up":
        near = _seg(19, 9 + b, 23, 4 + b, 1.4, 1.0) | _seg(23, 4 + b, 26, 1 + b, 1.0, 0.7)
        tips = _seg(26, 1 + b, 28, 0, 0.55) | _seg(26, 1 + b, 28, 2 + b, 0.55)
        tuft = (26.0, 2.5 + b)
    elif arm == "slam":
        near = _seg(19, 10 + b, 24, 13 + b, 1.4, 1.0) | _seg(24, 13 + b, 28, 18, 1.0, 0.8)
        tips = _seg(28, 18, 30, 20, 0.55) | _seg(28, 18, 27, 21, 0.55) | _seg(28, 18, 30, 17, 0.55)
        tuft = (26.0, 14.0 + b)
    else:
        near = _seg(19, 10 + b, 24, 13 + b, 1.4, 1.0) | _seg(24, 13 + b, 26, 17 + b, 1.0, 0.7)
        tips = _seg(26, 17 + b, 28, 18 + b, 0.55) | _seg(26, 17 + b, 26, 19 + b, 0.55)
        tuft = (24.5, 12.0 + b)
    lf, ln = (-step if step < 0 else 0), (step if step > 0 else 0)
    forms = [
        (_seg(11 - ln, 22, 13, 16 + b, 1.0, 1.4) | _seg(9 - ln, 22, 13 - ln, 22, 0.6), "c", "C", "d"),
        (far_arm | fingers_far, "c", "C", "d"),
        (_ell(10.5, 5.5 + b, 4.5, 3.6), "L", "m", "M"),                           # back leaves
        (_ell(15.5, 12.5 + b, 4.4, 7.0), "b", "B", "C"),                          # trunk body
        (_seg(18 + lf, 22 - (step < 0), 17, 16 + b, 1.0, 1.4)
         | _seg(16 + lf, 22 - (step < 0), 21 + lf, 22 - (step < 0), 0.6), "B", "c", "C"),
        (_ell(16.5, 3.8 + b, 5.6, 3.6) | _ell(21.5, 5.2 + b, 3.6, 2.8), "l", "L", "m"),  # crown
        (near | tips, "b", "B", "C"),
        (_ell(tuft[0], tuft[1], 1.8, 1.4), "l", "L", "m"),
    ]
    g = _stack(32, 24, forms)
    face = blank(32, 24)
    for (x, y, ch) in ((16, 9, "e"), (19, 9, "e"), (17, 12, "o"), (18, 12, "o"), (17, 13, "o"),
                       (14, 11, "c"), (15, 15, "c"), (13, 14, "c"), (20, 3, "f"), (13, 4, "f")):
        face = overlay(face, grid(ch), x, y + b)
    g = overlay(g, face)
    if arm == "slam":
        g = overlay(g, grid(("x.....", ".xx...", "...x..", "....x.")), 26, 5)
    return g


TR_DEAD = _stack(32, 24, [
    (_seg(4, 20, 22, 20, 2.2, 1.8), "b", "B", "C"),
    (_seg(20, 19, 26, 16, 0.8), "c", "C", "d"),
    (_seg(8, 21, 12, 23, 0.7), "c", "C", "d"),
    (_ell(26.0, 19.5, 4.2, 3.0) | _ell(29.0, 21.0, 2.4, 1.8), "L", "m", "M"),
])
TR_DEAD = overlay(TR_DEAD, grid(("o.o",)), 10, 19)
register("az.creature.treant.idle", art(_treant(), _treant(bob=1), legend=TR, fps=1.5,
                                        note="treant, leaves stirring"))
register("az.creature.treant.move", art(_treant(step=1), _treant(bob=-1), _treant(step=-1), _treant(bob=-1),
                                        legend=TR, fps=5, note="treant striding on its roots"))
register("az.creature.treant.attack", art(_treant(bob=-1, arm="up"), _treant(bob=1, arm="slam"),
                                          legend=TR, fps=6, note="treant: branch raised, crushing slam"))
register("az.creature.treant.dead", art(TR_DEAD, legend=TR, note="treant toppled like a felled tree"))


# ancient: a towering tree giant (five yards tall) - a thick trunk body on two root
# legs, antler boughs with leaf clusters and pink blossoms, a mossy beard, long
# branch arms hanging to its knees.


def _ancient(bob: int = 0, step: int = 0) -> Grid:
    b = bob
    lf, ln = (-step if step < 0 else 0), (step if step > 0 else 0)
    fy, ny = 38 - (step < 0), 38 - (step > 0)
    forms = [
        # far leg, far arm, far boughs (dark)
        (_seg(12 - ln, ny, 13, 27 + b, 1.6, 2.2) | _seg(9 - ln, ny, 14 - ln, ny, 0.8), "c", "C", "d"),
        (_seg(10, 17 + b, 6, 25 + b, 1.8, 1.3) | _seg(6, 25 + b, 5, 31 + b, 1.3, 0.8)
         | _seg(5, 31 + b, 3, 33 + b, 0.6) | _seg(5, 31 + b, 6, 34 + b, 0.6), "c", "C", "d"),
        (_seg(12, 10 + b, 7, 4 + b, 1.2, 0.7) | _seg(8, 5 + b, 4, 3 + b, 0.6), "c", "C", "d"),
        (_ell(5.5, 4.5 + b, 3.4, 2.6) | _ell(9.0, 8.0 + b, 3.0, 2.2), "L", "m", "M"),
        # trunk body
        (_ell(16.0, 21.0 + b, 6.6, 10.5), "b", "B", "C"),
        # near leg
        (_seg(19 + lf, fy, 18, 27 + b, 1.6, 2.4) | _seg(16 + lf, fy, 23 + lf, fy, 0.8), "B", "c", "C"),
        # head and near boughs
        (_ell(18.5, 11.0 + b, 4.4, 4.2), "b", "B", "C"),
        (_seg(19, 8 + b, 22, 2 + b, 1.2, 0.7) | _seg(22, 3 + b, 26, 1 + b, 0.6)
         | _seg(21, 5 + b, 25, 6 + b, 0.6), "b", "B", "C"),
        (_ell(25.5, 4.0 + b, 3.6, 2.5) | _ell(18.0, 4.0 + b, 3.0, 2.3), "l", "L", "m"),
        # mossy beard
        (_seg(18, 15 + b, 19, 20 + b, 1.6, 0.6) | _seg(20, 15 + b, 21, 18 + b, 1.1, 0.5), "L", "m", "M"),
        # near arm to the knee, leafy shoulder
        (_seg(22, 16 + b, 25, 24 + b, 1.8, 1.3) | _seg(25, 24 + b, 26, 31 + b, 1.3, 0.8)
         | _seg(26, 31 + b, 28, 33 + b, 0.6) | _seg(26, 31 + b, 25, 34 + b, 0.6)
         | _seg(26, 31 + b, 28, 30 + b, 0.55), "b", "B", "C"),
        (_ell(22.5, 15.5 + b, 2.6, 2.0), "l", "L", "m"),
    ]
    g = _stack(32, 40, forms)
    dots = blank(32, 40)
    for (x, y, ch) in ((18, 10, "e"), (21, 10, "e"), (17, 9, "C"), (20, 9, "C"),
                       (14, 20, "C"), (13, 23, "C"), (15, 26, "C"), (12, 18, "c"), (16, 24, "c"),
                       (26, 3, "f"), (24, 5, "f"), (17, 3, "f"), (5, 4, "f"), (9, 7, "f"), (23, 15, "f")):
        dots = overlay(dots, grid(ch), x, y + b)
    return overlay(g, dots)


AN_DEAD = _stack(32, 40, [
    (_seg(2, 35, 23, 35, 3.0, 2.4), "b", "B", "C"),
    (_seg(8, 33, 6, 29, 0.8) | _seg(14, 33, 17, 29, 0.8), "c", "C", "d"),
    (_seg(22, 34, 27, 31, 1.0), "c", "C", "d"),
    (_ell(27.0, 33.5, 4.4, 3.4) | _ell(6.0, 29.0, 2.4, 1.8) | _ell(17.5, 28.5, 2.4, 1.8), "L", "m", "M"),
])
AN_DEAD = overlay(AN_DEAD, grid(("f...f", "..f..")), 25, 32)
register("az.creature.ancient.idle", art(_ancient(), _ancient(bob=1), legend=TR, fps=1,
                                         note="ancient, a towering tree giant, boughs swaying"))
register("az.creature.ancient.move", art(_ancient(step=1), _ancient(bob=-1), _ancient(step=-1), _ancient(bob=-1),
                                         legend=TR, fps=4, note="ancient's slow, earth-shaking stride"))
register("az.creature.ancient.dead", art(AN_DEAD, legend=TR, note="ancient fallen, a great trunk in the grass"))


# --- pink elekk ----------------------------------------------------------------------
# The Brewfest pink elekk, only visible to the very drunk: a see-through bubblegum
# elephant with flapping ears, a curled trunk and four little tusks.

PE = {"k": "spore1:190", "3": "spore5:170", "2": "spore4:170", "1": "spore3:170", "0": "spore2:170",
      "t": "bone4:210", "T": "bone3:210", "e": "ink2:220", "h": "white:190"}


def _elekk(bob: int = 0, step: int = 0, ear: int = 0, dead: bool = False) -> Grid:
    b = bob
    if dead:
        g = _stack(32, 24, [
            (_box(8, 13, 10, 17) | _box(12, 13, 14, 17), "1", "0", "0"),
            (_ell(14.0, 18.5, 10.0, 4.2), "3", "2", "1"),
            (_ell(25.0, 19.0, 4.0, 3.4), "3", "2", "1"),
            (_seg(28, 20, 30, 22, 1.0, 0.7), "3", "2", "1"),
            (_ell(22.0, 17.5, 2.6, 3.0), "2", "1", "0"),
        ])
        return overlay(g, grid(("e.e", ".e.", "e.e")), 25, 16)
    fl = 1 if step > 0 else 0          # near-front and far-back legs lifted
    fr = 1 if step < 0 else 0          # far-front and near-back legs lifted
    fwd = step
    forms = [
        (_seg(6, 10 + b, 3, 15 + b, 0.6), "1", "0", "0"),                                   # tail
        (_box(8 - fwd, 16, 10 - fwd, 22 - fl), "1", "0", "0"),                              # far back leg
        (_box(20 + fwd, 16, 22 + fwd, 22 - fr), "1", "0", "0"),                             # far front leg
        (_ell(14.5, 12.5 + b, 10.0, 6.4), "3", "2", "1"),                                   # body
        (_box(10 + fwd, 15, 13 + fwd, 22 - fr), "2", "1", "0"),                             # near back leg
        (_box(18 - fwd, 15, 21 - fwd, 22 - fl), "2", "1", "0"),                             # near front leg
        (_seg(27, 11 + b, 29, 16 + b, 1.3, 1.0) | _seg(29, 16 + b, 30, 19 + b, 1.0, 0.7)
         | _seg(30, 19 + b, 29, 20 + b, 0.6), "3", "2", "1"),                               # trunk
        (_ell(24.8, 9.0 + b, 4.2, 4.0), "3", "2", "1"),                                     # head
        (_ell(21.5 - ear * 0.5, 9.5 + b + ear * 0.5, 2.8 + ear * 0.4, 3.8), "2", "1", "0"),  # ear
    ]
    g = _stack(32, 24, forms)
    tusks = blank(32, 24)
    for (x, y, ch) in ((27, 13, "t"), (28, 14, "t"), (29, 14, "T"), (26, 14, "T"), (27, 15, "T"),
                       (26, 8, "e"), (25, 7, "h"), (12, 8, "h"), (13, 7, "h"), (16, 7, "h")):
        tusks = overlay(tusks, grid(ch), x, y + b)
    return overlay(g, tusks)


register("az.creature.pink_elekk.idle", art(_elekk(), _elekk(bob=1, ear=1), legend=PE, fps=2,
                                            note="pink elekk (Brewfest), ears flapping"))
register("az.creature.pink_elekk.move", art(_elekk(step=1), _elekk(bob=-1, ear=1), _elekk(step=-1),
                                            _elekk(bob=-1, ear=1), legend=PE, fps=6, note="pink elekk parading"))
register("az.creature.pink_elekk.dead", art(_elekk(dead=True), legend=PE, note="pink elekk keeled over"))
