"""Azeroth / Mulgore art: people tauren. Must satisfy
``wilds.azeroth.manifest.required()["people_tauren"]`` (see docs/azeroth/mulgore-art-manifest.md).

Tauren are tall (16x24 at real scale: 1 yard = 8 px), face RIGHT in a 3/4 side
view and stand with their hooves on the bottom row.

How the art is built
--------------------
Like ``city_people`` each body (male, female) is a *rig* of fill-only parts
written in *slot* characters; a frame is a list of parts layered in order and
the 1px ``ink`` outline is added after composing, so any gear that changes the
silhouette (a totem staff, antlers, an axe) gets a clean outline for free.
An outfit is a :class:`Look` (which garment / gear parts) plus a slot ->
palette mapping, so eleven outfits share one male and one female base.

Slot characters::

    q s S   fur light / mid / shadow        d D   hands (fur) mid / shadow
    j h H   hair / mane light / mid / dark   n N   horn light / dark
    u U     muzzle / nose + nostril          e o   eye, open mouth
    y t T   top garment light / mid / shadow p P   kilt / skirt mid / shadow
    a A     accent (belt, bracer, trim)      x X   second garment (apron, shawl, quiver)
    c C     metal light / dark               g G   wood light / dark
    r       war paint / red feather tip      f F   feather light / dark
    l L     leaf light / dark                b     bead (turquoise)
    z Z     spell glow bright / dim          v V   hoof light / dark
    m       string (bow)                     k K w ink, ink2, white (always available)
"""

from __future__ import annotations

from dataclasses import dataclass

from ..palette import _ramp
from ..pixelart import Grid, art, blank, grid, outline_grid, overlay, swap
from ..registry import register

# warm tauren fur browns (the existing skin / rust ramps are too pink or too red)
_ramp("azp_fur", "#2a1812", "#4a2c1e", "#6b432c", "#8f5f3c", "#b3814f", "#d5a771")

W, H = 16, 24


# --- parts and composition ------------------------------------------------------------


@dataclass(frozen=True)
class Part:
    """A fill-only piece of a figure: full-width rows placed at (x, y)."""

    rows: Grid
    x: int = 0
    y: int = 0

    def at(self, dx: int = 0, dy: int = 0) -> "Part":
        return Part(self.rows, self.x + dx, self.y + dy)


def part(y: int, text: str, x: int = 0) -> Part:
    return Part(grid(text), x, y)


def dot(x: int, y: int, ch: str) -> Part:
    return Part((ch,), x, y)


def compose(parts, post=(), size=(W, H)) -> Grid:
    """Layer parts in order, outline the silhouette, then add unoutlined extras."""
    out = blank(*size)
    for p in parts:
        out = overlay(out, p.rows, p.x, p.y)
    out = outline_grid(out, "k")
    for p in post:
        out = overlay(out, p.rows, p.x, p.y)
    return out


def masked(p: Part, shape: Part) -> Part:
    """``p`` kept only where ``shape`` is opaque (a male garment fitted to a female torso)."""
    base = overlay(blank(W, H), p.rows, p.x, p.y)
    mask = overlay(blank(W, H), shape.rows, shape.x, shape.y)
    rows = tuple("".join(c if m != "." else "." for c, m in zip(r, mr)) for r, mr in zip(base, mask))
    return Part(rows)


# --- the male body ----------------------------------------------------------------------
# heavy shoulder hump, head carried low and forward, wide horns, big hands, hooves

MALE = {
    "head": part(1, """
        .....n......n...
        .....nN....nN...
        ......NNhhhN....
        .....hhjqqsq....
        ....hhjqssssq...
        ...hhjjssesuu...
        ...hjjhsssuuuu..
        ...hjhhSssuuuU..
        ...hhHHKSSSUU...
        ....HH.KKKK.....
        ....H...........
    """),
    "torso": part(4, """
        ..qqq...........
        .qqsss..........
        .qssss..........
        .qsssssss.......
        .qsssssssss.....
        .qssssssssS.....
        .qssssssssS.....
        .qssssssssS.....
        ..sssssssSS.....
        ..ssssssSSS.....
        ...SSSSSSSS.....
    """),
    # legs: the far leg (left, shaded) and the near leg (right)
    "legs.stand": part(15, """
        ...ssssssssS....
        ...SSSSs.sssS...
        ....SSS..sssS...
        ....SSS..sssS...
        ....SSS..sssS...
        ....VV....vvv...
        ...VVVV.vvvvv...
        ...VVKV.vvKvv...
    """),
    "legs.w0": part(15, """
        ...SSSSsssss....
        ...SSSS..sssS...
        ..SSS.....sssS..
        ..SSS......sss..
        ..SSS......sss..
        ..VV.......vvv..
        .VVVV.....vvvvv.
        .VVKV.....vvKvv.
    """),
    "legs.w1": part(15, """
        ...SSSSssss.....
        ...SSSS.sssS....
        ..SSS...sssS....
        .SSS....sssS....
        .VV.....sssS....
        ........vvv.....
        .......vvvvv....
        .......vvKvv....
    """),
    "legs.w2": part(15, """
        ...sssssSSSS....
        ...ssss..SSSS...
        ..sss.....SSS...
        ..sss......SSS..
        ..sss......SSS..
        ..vv.......VVV..
        .vvvv.....VVVVV.
        .vvKv.....VVKVV.
    """),
    "legs.w3": part(15, """
        ...ssssSSSS.....
        ...ssss.SSSS....
        ..sss...SSSS....
        .sss....SSSS....
        .vv.....SSSS....
        ........VVV.....
        .......VVVVV....
        .......VVKVV....
    """),
    "legs.hurt": part(15, """
        ...SSSSsssss....
        ..SSSS..sssS....
        ..SSS....sssS...
        ..SSS.....sss...
        ..SS......sss...
        .VVV.....vvv....
        .VVVV...vvvvv...
        .VVKV...vvKvv...
    """),
    # the near arm
    "arm.down": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.....
        .....kqsssS.....
        ......kqssS.....
        ......kaaaA.....
        ......kqssS.....
        ......kqssS.....
        ......kddDD.....
        ......kdddD.....
        .......dDD......
    """),
    "arm.back": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.....
        ....kqsssS......
        ....kqssS.......
        ...kaaaA........
        ...kqssS........
        ..kqssS.........
        ..kddDD.........
        ..kdddD.........
        ...dDD..........
    """),
    "arm.fwd": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.....
        ......kqsssS....
        .......kqssS....
        .......kaaaA....
        ........kqssS...
        ........kqssS...
        ........kddDD...
        ........kdddD...
        .........dDD....
    """),
    "arm.talk0": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.....
        .....kqsssS.....
        ......kqssS.dd..
        ......kqsssaddD.
        .......kSSSaAD..
    """),
    "arm.talk1": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.dd..
        .....kqsssSddD..
        ......kqssaAD...
        ......kqssSS....
        .......kSSS.....
    """),
    "arm.hurt": part(5, """
        ..........dd....
        .........ddD....
        ......qqsaA.....
        .....kqssS......
        .....kqssS......
        .....kqsSS......
        ......kSS.......
    """),
    # attack: backswing (hand behind the hip), strike (arm level, weapon up), follow-through
    "atk.raise": part(3, """
        ...dd...........
        ..kddD..........
        ...aA...........
        ...kqsS.........
        ....kqss........
        .....kqsss......
        .....kqsssS.....
        ......kSSS......
    """),
    "atk.fwd": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.dd..
        ......kqsssaddD.
        .......kSSSAdD..
    """),
    "atk.strike": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssS.....
        ......kqsssS....
        .......kqsssS...
        ........kqssS...
        .........kaaA...
        .........kddD...
        .........kdddD..
        ..........dDD...
    """),
    "atk.cast": part(7, """
        ......qqs.......
        .....kqsss......
        .....kqsssSs....
        ......kqsssaadd.
        .......kSSSAAdD.
    """),
    # outfit pieces --------------------------------------------------------
    "tunic": part(7, """
        .yyyttt.........
        .ytttttts.......
        .yttttttsS......
        .yttttttsS......
        .ytttttttT......
        ..tttttTTT......
        ..tttttTTT......
    """),
    "plate": part(7, """
        .yyyttt.........
        .yyttttty.......
        .ytttttttT......
        .aaaaaaaaA......
        .ytttttttT......
        ..tttttTTT......
        ..tttttTTT......
    """),
    "kilt": part(14, """
        ..aaaaaaaaA.....
        ..ppppppppPP....
        ..ppppppppPP....
        ...pPpPpPpP.....
    """),
    "loin": part(14, """
        ..aaaaaaaaA.....
        ..PP....ppppP...
        ..P......pppP...
        .........pPp....
    """),
    "robe.top": part(7, """
        .yyyttt.........
        .ytttttt........
        .yttttttT.......
        .yttttttT.......
        .yttttttT.......
        ..ttttttTT......
        ..tttttTTT......
    """),
    "robe.skirt": part(14, """
        ..aaaaaaaaA.....
        ..ytttttttTT....
        ..ytttttttTT....
        ..yttttttttTT...
        .ytttttttttTT...
        .yttttttttttTT..
        .aaaaaaaaaaaaA..
    """),
    "apron": part(14, """
        ..aaaaaaaaA.....
        ........xxxX....
        ........xxxX....
        ........xxxX....
        ........xxxX....
        ........XXX.....
    """),
    "satchel": part(8, """
        ........a.......
        .......a........
        ......a.........
        .....a..........
        ..gga...........
        .gggGG..........
        .ggcgG..........
        .gggGG..........
        ..GGG...........
    """),
    "shawl": part(6, """
        ..xxx...........
        .xxxxxxx........
        .rrrrrrrr.......
        .xxxxxxxxX......
        .XXXXXXXXX......
        .X.X.X.X.X......
    """),
    "sash": part(7, """
        .a..............
        .aa.............
        ..aa............
        ...aa...........
        ....aa..........
        .....aa.........
        ......aa........
    """),
    "pauldron": part(9, """
        .....cccc.......
        ....ccccCC......
        .....CCCC.......
    """),    "bracer": part(12, """
        ......kaaaA.....
    """),
    # head gear
    "feathers": part(1, """
        ..f.f...........
        .fF.fF..........
        ..fFf...........
        ...rr...........
        ....b...........
    """),
    "paint.shaman": part(4, """
        ........w.......
        .......w........
        ........w.......
    """),
    "scarf": part(6, """
        ..x.............
        .xX.............
        .xX.............
        ..X.............
    """),
    "scarf.knot": part(10, """
        ........xxX.....
        .........X......
    """),
    "feather": part(1, """
        ................
        ..f.............
        ..ff............
        ...F............
    """),
    "antlers": part(0, """
        ................
        ...n.n..........
        ...nnN.l........
        ....nNlL........
        ......l.........
    """),
    "headband": part(4, """
        ......aaaA......
    """),
    "beard": part(9, """
        ................
        .......jhhH.....
        ........hH......
    """),
    "paint": part(5, """
        ......r.........
        ........r.......
        .......r.r......
        ................
    """),
    "paint.body": part(10, """
        .rr.............
        ................
        ..rr............
    """),
    # carried on the back (hidden while that weapon is swung)
    "back.bow": part(2, """
        ..f.f...........
        ..fFf...........
        ..xx............
        .xxX............
        .xxX............
        .xX.............
        .xX.............
        .xX.............
        .XX.............
    """),
    "back.axe": part(1, """
        ..c.............
        .cCc............
        .ccC............
        ..g.............
        ..g.............
        .gG.............
        .gG.............
        .g..............
        .G..............
    """),
    "back.hammer": part(1, """
        .ccc............
        .cCC............
        ..g.............
        ..g.............
        .gG.............
        .g..............
        .G..............
    """),
    "back.club": part(1, """
        ..c.............
        .ggc............
        .gGg............
        ..gG............
        .gG.............
        .g..............
        .G..............
    """),
    # held upright in the far hand, in front of the chest
    "far.totem": part(1, """
        ............f.f.
        ............rrr.
        ............brb.
        ............gGg.
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        ............ddD.
        ............dDD.
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
    """),
    "far.druid": part(1, """
        ............l.l.
        ...........lLgl.
        ............gG..
        .............gl.
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        ............ddD.
        ............dDD.
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
    """),
    "far.cane": part(11, """
        ............gg..
        ...........ddgG.
        ...........dDDG.
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
    """),
    "far.halberd": part(1, """
        .............c..
        .............cc.
        ............cCc.
        .............gc.
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        ............ddD.
        ............dDD.
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
        .............g..
        .............g..
        .............G..
    """),
}

def _sleeved(p: Part) -> Part:
    """Upper arm (every row above the bracer) in sleeve slots 7 8 9, which default to fur
    and take the garment colours in outfits with sleeves or armoured shoulders."""
    cut = next((i for i, r in enumerate(p.rows) if "a" in r), 0)
    sw = {"q": "7", "s": "8", "S": "9"}
    rows = tuple("".join(sw.get(c, c) for c in r) if i < cut else r for i, r in enumerate(p.rows))
    return Part(rows, p.x, p.y)


for _n in [n for n in MALE if n.startswith(("arm.", "atk."))]:
    MALE[_n] = _sleeved(MALE[_n])


# weapons for the three attack frames: raised over the head (top-left corner), mid-swing
# (up in front, top-right corner), strike (driven down to the ground in front). Drawn over
# the head, under the near arm, so the silhouette sweeps across the whole frame.
WEAPONS = {
    "axe": (
        part(0, """
            ................
            .cc.cc..........
            .cCgCc..........
            .cc.cc..........
        """),
        part(1, """
            ................
            ...........cgc..
            ..........ccgcc.
            ..........cCgCc.
            ...........cgc..
            ............g...
            ............G...
            ............g...
        """),
        part(17, """
            ............G...
            ............g...
            ...........cgc..
            ..........ccgcc.
            ..........cCCCc.
            ...........cCc..
        """),
    ),
    "hammer": (
        part(0, """
            ................
            .ccccc..........
            .cCCCC..........
            ...g............
        """),
        part(2, """
            ...........ccc..
            ..........cccC..
            ..........cCCC..
            ............g...
            ............g...
            ............G...
            ............g...
        """),
        part(17, """
            ............G...
            ............g...
            ...........ccc..
            ..........ccccC.
            ..........cCCCC.
            ..........CCCCC.
        """),
    ),
    "club": (
        part(0, """
            ..c.c...........
            .cgggc..........
            ..gGG...........
            ...g............
        """),
        part(2, """
            ............c...
            ...........ggg..
            ..........cgGGc.
            ...........gGG..
            ............gG..
            ............g...
            ............G...
        """),
        part(17, """
            ............g...
            ............G...
            ...........cgc..
            ..........cggGc.
            ...........gGG..
            ..........c.GG..
        """),
    ),
    "halberd": (
        part(0, """
            ...c............
            .ccCcc..........
            .cCgCc..........
            ...g............
            ................
            ................
            ...g............
            ...G............
            ...g............
            ...g............
            ...G............
        """),
        part(1, """
            ............c...
            ............Cc..
            ...........cgcc.
            ...........cgCc.
            ............gc..
            ............g...
            ............G...
            ............g...
            ................
            ................
            ............g...
            ............G...
            ............g...
            ............g...
            ............G...
        """),
        part(10, """
            ........g.......
            .........g......
            ..........g.....
            ................
            ................
            ................
            ............g...
            ............G...
            ...........cgc..
            ...........cCcc.
            ............cC..
            ............c...
        """),
    ),
    "bow": (
        part(3, """
            ............g...
            ............mg..
            ............m.g.
            ............m.g.
            ............m..g
            ............m..g
            ................
            ................
            ............m..g
            ............m..g
            ............m.g.
            ............m.g.
            ............mg..
            ............g...
        """),
        part(3, """
            ............g...
            ...........m.g..
            ..........m...g.
            ..........m...g.
            .........m.....g
            ........mcccccc.
            ................
            ................
            .........m.....g
            ..........m....g
            ..........m...g.
            ...........m..g.
            ............mg..
            ............g...
        """),
        part(3, """
            ............g...
            .............g..
            .............mg.
            .............mg.
            .............m.g
            .............m.g
            ................
            ................
            .............m.g
            .............m.g
            .............mg.
            .............mg.
            .............g..
            ............g...
        """),
    ),
}

# spell glow for casters (after the outline, so it shines), one per attack frame
CAST_GLOW = (
    part(0, """
        ...z............
        ..zZz...........
        .zZzZz..........
        ..zZz...........
    """),
    part(6, """
        .............Z..
        ............ZzZ.
        ...........Zzzz.
        ............ZzZ.
        .............Z..
    """),
    part(5, """
        ...........z..z.
        ............Z.Z.
        ..........zZzzz.
        ...........zzzz.
        ..........zZzzZ.
        ............Z.Z.
        ...........z..z.
    """),
)
ARROW = part(8, """
    ..............ww
""")


# --- the female body ---------------------------------------------------------------------
# smaller curled horns, long braided hair, a slimmer back; everything the female rig does
# not redraw is the male part moved down a pixel (garments fitted to her torso)

FEMALE_OWN = {
    "head": part(2, """
        ......n....n....
        ......nN..Nn....
        ......hhhhhh....
        .....hjjqqsq....
        ....hhjqssssq...
        ...hhjjssesu....
        ...hjjhsssuuu...
        ...hjhhSSsuuU...
        ...hhHHKSSKK....
        ..hhHHb.KK......
        ..hHH...........
        ..hH............
        ..HH............
        ..H.............
    """),
    # women wear the kilt long, to the shins
    "kilt": part(14, """
        ..aaaaaaaaA.....
        ..ppppppppPP....
        ..ppppppppPP....
        ..pppppppppP....
        .ppppppppppPP...
        .ppppppppppPP...
        ..pPpPpPpPpP....
    """),
    "torso": part(6, """
        ..qq............
        .qqsss..........
        .qssss..........
        .qssssss........
        .qsssssss.......
        .qsssssss.......
        ..sssssSS.......
        ..ssssSSS.......
        ...SSSSSS.......
    """),
}
_FEMALE_STATIC = ("legs.", "kilt", "loin", "robe.skirt", "apron", "far.")
_FEMALE_FITTED = ("tunic", "plate", "robe.top")


class Rig:
    def __init__(self, name: str, parts: dict[str, Part], mouth: tuple[int, int],
                 base: "Rig | None" = None, drop: int = 0) -> None:
        self.name, self.own, self.mouth, self.base, self.drop = name, parts, mouth, base, drop

    def __getitem__(self, name: str) -> Part:
        if name in self.own:
            return self.own[name]
        if self.base is None:
            raise KeyError(f"{self.name} rig has no part {name!r}")
        p = self.base[name]
        if name.startswith(_FEMALE_STATIC):
            return p
        p = p.at(0, self.drop)
        if name in _FEMALE_FITTED:
            p = masked(p, self["torso"])
        return p

    def weapon(self, style: str, i: int) -> Part:
        # the bow's belly would touch the canvas edge: keep it inside the outline margin
        return WEAPONS[style][i].at(-1 if style == "bow" else 0, self.drop)

    def glow(self, i: int) -> Part:
        return CAST_GLOW[i].at(0, self.drop)


MALE_RIG = Rig("tauren_m", MALE, mouth=(10, 9))
FEMALE_RIG = Rig("tauren_f", FEMALE_OWN, mouth=(10, 10), base=MALE_RIG, drop=1)


@dataclass(frozen=True)
class Look:
    """What a tauren wears. ``skirt`` hangs from the hips and does not breathe;
    ``wear`` sits on the torso; ``gear`` on the head; ``back`` is slung behind;
    ``far`` is held upright in the far hand; ``over`` covers the near arm;
    ``paint`` goes on after the outline."""

    skirt: tuple[str, ...] = ()
    wear: tuple[str, ...] = ()
    gear: tuple[str, ...] = ()
    back: tuple[str, ...] = ()
    far: tuple[str, ...] = ()
    over: tuple[str, ...] = ()
    paint: tuple[str, ...] = ()
    weapon: str = ""                # attack style: axe, hammer, club, halberd, bow, cast
    hunch: int = 0                  # elders carry the head a pixel lower


def figure(rig: Rig, look: Look, legs: str = "legs.stand", arm: str = "arm.down", *,
           dx: int = 0, dy: int = 0, mouth: bool = False, blink: bool = False,
           weapon: Part | None = None, glow: Part | None = None, armed: bool = False) -> Grid:
    """One frame: legs and skirt stay put, the rest moves by (dx, dy). ``armed``
    hides the slung / far-hand weapon while it is being swung."""
    up = lambda n: rig[n].at(dx, dy)  # noqa: E731
    hy = dy + look.hunch
    parts = [up(n) for n in look.far if not (armed and look.weapon == "halberd")]
    parts += [rig[legs], up("torso")]
    parts += [up(n) for n in look.wear]
    parts += [up(n) for n in look.back if not armed]
    parts += [rig[n] for n in look.skirt]
    parts += [rig["head"].at(dx, hy)] + [rig[n].at(dx, hy) for n in look.gear]
    if mouth:
        parts.append(dot(*rig.mouth, "o").at(dx, hy))
    if weapon is not None:
        parts.append(weapon.at(dx, dy))
    parts += [up(arm)] + [up(n) for n in look.over]
    post = [rig[n].at(dx, hy) for n in look.paint]
    if glow is not None:
        post.append(glow.at(dx, dy))
    g = compose(parts, post)
    return swap(g, {"e": "s"}) if blink else g


WALK = (("legs.w0", "arm.back", 1), ("legs.w1", "arm.down", 0),
        ("legs.w2", "arm.fwd", 1), ("legs.w3", "arm.down", 0))


def idle_frames(rig: Rig, look: Look) -> list[Grid]:
    return [figure(rig, look), figure(rig, look, dy=1)]


def walk_frames(rig: Rig, look: Look) -> list[Grid]:
    return [figure(rig, look, legs, arm, dy=dy) for legs, arm, dy in WALK]


def talk_frames(rig: Rig, look: Look) -> list[Grid]:
    return [figure(rig, look, arm="arm.talk0"), figure(rig, look, arm="arm.talk1", mouth=True)]


def attack_frames(rig: Rig, look: Look) -> list[Grid]:
    style = look.weapon
    if style == "cast":
        arms = ("atk.raise", "atk.cast", "atk.cast")
        return [figure(rig, look, arm=a, glow=rig.glow(i), dx=i // 2) for i, a in enumerate(arms)]
    if style == "bow":
        out = [figure(rig, look, arm="atk.cast", weapon=rig.weapon("bow", i), armed=True) for i in range(3)]
        return out
    arms = ("atk.raise", "atk.fwd", "atk.strike")
    return [figure(rig, look, arm=a, weapon=rig.weapon(style, i), armed=True, dx=i // 2, dy=i // 2)
            for i, a in enumerate(arms)]


def hurt_frame(rig: Rig, look: Look) -> Grid:
    return figure(rig, look, "legs.hurt", "arm.hurt", dx=-1, dy=1)


# --- colours --------------------------------------------------------------------------------

FUR = {  # light, mid, shadow, hand, hand shadow
    "brown": ("azp_fur4", "azp_fur3", "azp_fur2", "azp_fur2", "azp_fur1"),
    "dark": ("azp_fur3", "azp_fur2", "azp_fur1", "azp_fur1", "azp_fur0"),
    "tan": ("sand4", "sand3", "sand2", "azp_fur2", "azp_fur1"),
    "fawn": ("azp_fur5", "azp_fur4", "azp_fur3", "azp_fur2", "azp_fur1"),
    "rust": ("rust4", "rust3", "rust2", "azp_fur1", "azp_fur0"),
    "grey": ("bone3", "bone2", "bone1", "bone1", "bone0"),
    "pale": ("bone4", "bone3", "bone2", "bone1", "bone0"),
}
HAIR = {  # light, mid, dark
    "black": ("leather3", "leather2", "leather1"),
    "brown": ("azp_fur2", "azp_fur1", "azp_fur0"),
    "white": ("bone4", "bone3", "bone2"),
    "grey": ("bone2", "bone1", "bone0"),
    "red": ("rust3", "rust2", "rust1"),
}


def legend(fur: str, hair: str, sleeves: bool = False, **slots: str) -> dict[str, str]:
    q, s, S, d, D = FUR[fur]
    j, h, Hh = HAIR[hair]
    base = {
        "q": q, "s": s, "S": S, "d": d, "D": D, "j": j, "h": h, "H": Hh, "7": q, "8": s, "9": S,
        "n": "bone4", "N": "bone2", "u": "bone2", "U": "bone0", "e": "ink2", "o": "red0",
        "I": "bone3", "i": "bone1",
        "v": "bone1", "V": "bone0", "b": "cryst1", "m": "bone3",
        "y": "sand3", "t": "sand2", "T": "sand1", "p": "tent1", "P": "tent0",
        "a": "red2", "A": "red1", "x": "sand4", "X": "sand3",
        "c": "chrome2", "C": "chrome1", "g": "dust4", "G": "dust3",
        "r": "red2", "f": "bone4", "F": "red2", "l": "hound3", "L": "hound2",
        "z": "glowcyan", "Z": "water4",
    }
    if fur in ("grey", "pale"):
        base.update(u="elf1", I="elf2", i="elf0")
    base.update(slots)
    if sleeves:
        base.update({"7": base["y"], "8": base["t"], "9": base["T"]})
    return base


@dataclass(frozen=True)
class Outfit:
    look: Look
    male: dict[str, str]
    female: dict[str, str]
    note: str


def _outfit(look: Look, note: str, fur=("brown", "brown"), hair=("black", "black"), sleeves=False,
            female: dict[str, str] | None = None, **slots: str) -> Outfit:
    """Male and female legends; ``female`` overrides a few slots for her."""
    return Outfit(look, legend(fur[0], hair[0], sleeves, **slots),
                  legend(fur[1], hair[1], sleeves, **{**slots, **(female or {})}), note)


# each outfit owns one strong colour (and most a silhouette piece) so a crowd reads at x1
OUTFITS = {
    "civilian": _outfit(Look(skirt=("kilt",), wear=("tunic",)), "villager in a buckskin tunic",
                        fur=("brown", "dark"), hair=("black", "black"),
                        y="sand4", t="sand3", T="sand2", p="tent2", P="tent1",
                        female={"p": "rust3", "P": "rust2"}),
    "hunter": _outfit(Look(skirt=("kilt",), wear=("tunic",), gear=("feather",), back=("back.bow",),
                           weapon="bow"), "hunter: green jerkin, leather kilt, bow and quiver",
                      fur=("tan", "brown"), hair=("black", "red"), sleeves=True,
                      y="hound2", t="olive2", T="olive1", p="dust3", P="dust2", a="dust4", A="dust3",
                      x="dust2", X="dust1", g="tent2", G="tent1"),
    "shaman": _outfit(Look(skirt=("kilt",), wear=("tunic",), gear=("feathers",), far=("far.totem",),
                           paint=("paint.shaman",), weapon="cast"),
                      "shaman: teal mail, feather crest, white face paint, carved totem staff",
                      fur=("dark", "brown"), hair=("black", "black"), sleeves=True,
                      y="moss5", t="moss4", T="moss3", p="leather3", P="leather2", a="bone4", A="bone2",
                      g="dust3", G="dust2", r="red3", z="glowcyan", Z="water4"),
    "druid": _outfit(Look(skirt=("kilt",), wear=("tunic",), gear=("antlers",), far=("far.druid",),
                          weapon="cast"), "druid: leaf-green hide, antler-and-leaf headdress, leafy staff",
                     fur=("brown", "fawn"), hair=("brown", "red"),
                     y="hound3", t="hound2", T="hound1", p="dust2", P="dust1", a="tent3", A="tent2",
                     l="hound4", L="hound2", g="dust3", G="dust2", z="glowlime", Z="hound3"),
    "warrior": _outfit(Look(skirt=("kilt",), wear=("plate",), back=("back.axe",), over=("pauldron",),
                            weapon="axe"), "warrior: steel plate, pauldron, double-bit axe",
                       fur=("dark", "brown"), hair=("black", "black"), sleeves=True,
                       y="steel5", t="steel4", T="steel3", p="leather3", P="leather2", a="red3", A="red2",
                       c="chrome3", C="chrome1", g="dust3", G="dust2"),
    "priest": _outfit(Look(skirt=("robe.skirt",), wear=("robe.top",)), "priest: pale hide robe",
                      fur=("brown", "fawn"), hair=("black", "white"), sleeves=True,
                      y="white", t="bone4", T="bone3", a="gold2", A="gold1"),
    "merchant": _outfit(Look(skirt=("apron",), wear=("tunic", "satchel"), gear=("headband",)),
                        "merchant: red tunic, white apron, satchel", fur=("fawn", "brown"),
                        hair=("black", "black"),
                        y="red3", t="red2", T="red1", x="white", X="bone3", a="gold2", A="gold1",
                        g="dust3", G="dust2", c="gold2"),
    "trainer": _outfit(Look(skirt=("kilt",), wear=("tunic", "sash"), gear=("feather",)),
                       "trainer: blue tunic, gold sash, feather", fur=("brown", "tan"), hair=("black", "black"),
                       sleeves=True, y="water4", t="water3", T="water2", p="leather3", P="leather2",
                       a="gold2", A="gold1", F="water4"),
    "elder": _outfit(Look(skirt=("kilt",), wear=("tunic", "shawl"), gear=("beard",), far=("far.cane",),
                          hunch=1), "elder: white mane and beard, red blanket shawl, cane",
                     fur=("grey", "grey"), hair=("white", "white"),
                     y="bone4", t="bone3", T="bone2", p="leather3", P="leather2",
                     x="red3", X="red2", r="white", g="dust3", G="dust2"),
    "guard": _outfit(Look(skirt=("kilt",), wear=("tunic",), gear=("feather",), far=("far.halberd",),
                          over=("pauldron",), weapon="halberd"), "Bloodhoof brave: red kilt, steel pauldron, halberd",
                     fur=("brown", "dark"), hair=("black", "black"), sleeves=True,
                     y="leather3", t="leather2", T="leather1", p="red3", P="red2", a="gold2", A="gold1",
                     c="chrome3", C="chrome1", g="dust3", G="dust2", f="white", F="red3"),
    "palemane": _outfit(Look(skirt=("loin",), back=("back.club",), paint=("paint", "paint.body"), weapon="club"),
                        "Palemane raider: pale fur, red war paint, spiked club",
                        fur=("pale", "pale"), hair=("black", "black"),
                        p="leather2", P="leather1", a="bone3", A="bone1", g="dust3", G="dust2", c="bone4",
                        r="red3"),
}
COMBAT = ("hunter", "shaman", "druid", "warrior", "guard", "palemane")


# fallen: flat on the back with the hooves in the air (left), the head to the right with
# the muzzle up and the horns sideways, the near arm limp on the ground
DEAD = {
    "tauren_m": part(12, """
        ..VV.vv.........
        ..VKVvKv........
        ..SS.ss.........
        ..SS.sS......n..
        .pSSpssp..UunN..
        .pppppPPP.uuqN..
        .aaaaaaaAhIuuss.
        .ytttttttTjsSSq.
        .yttttttThjsSSN.
        ..tTTTTTThhHSnN.
        ...ddDSSSHH.K...
    """),
    "tauren_f": part(12, """
        ................
        ..VV.vv.........
        ..VKVvKv........
        ..SS.sS.........
        .pSSpssp..Uu.n..
        .pppppPPP.uuqN..
        .aaaaaaaAhIuuss.
        .ytttttttTjsSSq.
        .yttttttThjsSSN.
        ..tTTTTTThhHSsn.
        ...ddDSSShHhHh..
    """),
}


def _register_bodies() -> None:
    for rig in (MALE_RIG, FEMALE_RIG):
        body = rig.name
        for name, o in OUTFITS.items():
            lg = o.male if rig is MALE_RIG else o.female
            key = f"az.person.{body}.{name}"
            register(f"{key}.idle", art(*idle_frames(rig, o.look), legend=lg, fps=2, note=o.note))
            register(f"{key}.walk", art(*walk_frames(rig, o.look), legend=lg, fps=8, note=o.note))
            register(f"{key}.talk", art(*talk_frames(rig, o.look), legend=lg, fps=3,
                                        note=o.note + ", gesturing mid-conversation"))
            if name in COMBAT:
                register(f"{key}.attack", art(*attack_frames(rig, o.look), legend=lg, fps=8, note=o.note))
        civ = OUTFITS["civilian"]
        lg = civ.male if rig is MALE_RIG else civ.female
        register(f"az.person.{body}.hurt", art(hurt_frame(rig, civ.look), legend=lg, note="recoiling"))
        register(f"az.person.{body}.dead", art(compose([DEAD[body]]), legend=lg, note="fallen on its side"))


_register_bodies()


# --- the hero ------------------------------------------------------------------------------
# a young tauren adventurer, the one figure in the crowd dressed in sunflower yellow with a
# turquoise scarf trailing from the neck (no NPC wears either), a white-and-turquoise
# feather and a stone-headed hammer slung on the back (swung to fight, work, gather, build)

HERO_LOOK = Look(skirt=("kilt",), wear=("tunic", "scarf"), gear=("feather",), back=("back.hammer",),
                 over=("scarf.knot",), weapon="hammer")
HERO_LEGEND = legend("brown", "black", True, y="jacket3", t="jacket2", T="jacket1", p="leather3", P="leather2",
                     a="cryst1", A="cryst0", x="cryst1", X="cryst0", c="rock4", C="rock3", g="dust4",
                     G="dust3", f="white", F="cryst1")


def _register_hero() -> None:
    lg, look, note = HERO_LEGEND, HERO_LOOK, "the hero: a young tauren adventurer"
    register("az.person.hero.idle", art(*idle_frames(MALE_RIG, look), legend=lg, fps=2, note=note))
    register("az.person.hero.walk", art(*walk_frames(MALE_RIG, look), legend=lg, fps=8, note=note))
    register("az.person.hero.attack", art(*attack_frames(MALE_RIG, look), legend=lg, fps=8, note=note))
    work = [figure(MALE_RIG, look, arm="atk.fwd", weapon=MALE_RIG.weapon("hammer", 1), armed=True),
            figure(MALE_RIG, look, arm="atk.strike", weapon=MALE_RIG.weapon("hammer", 2), armed=True, dy=1)]
    register("az.person.hero.work", art(*work, legend=lg, fps=4, note="gather / craft / build: hammer blows"))


_register_hero()


# --- portraits (24x24) -----------------------------------------------------------------------
# head and shoulders in the same 3/4 view (facing right); one male and one female head,
# every quest giver is a recolour plus a few overlays taken from the NPC's record

PW = 24


def pp(y: int, text: str) -> Part:
    """A portrait part: rows are padded to the 24 px width."""
    return Part(tuple(r.ljust(PW, ".") for r in grid(text)), 0, y)


PORTRAIT = {
    "male": pp(1, """
        ..n..................n..
        ..nn................nN..
        ...nN..............nN...
        ...NNN...jjjjj....nNN...
        ....NNNjjqqqqqq.NNN.....
        ......jjqqqqqssss.......
        .....hjqqqsssssss.......
        ....hhjqqssssssssq......
        ....hjjqssSSSsssqqs.....
        ...hhjqssSwesssqqsss....
        ...hjjqsssssssqqssssI...
        ...hjhSssssssqsssssIuu..
        ...hjhSssssssssssssuuu..
        ..hhhHSSssssssssssuUuu..
        ..hhhHSSSsssSSssssiuuu..
        ..hhHHSSSSSSSSSSSSSiiu..
        ..hHHH.SSSSSSKKSSSSSi...
        ..hHH...SSSSSSSSSSS.....
        .hHH..ttttttttttttt.....
        .hH.yytttttttttttttt....
        .yyyyttttttttttttttttt..
        yyyytttttttttttttttttTT.
        yyytttttttttttttttttTTTT
    """),
    "female": pp(1, """
        ........................
        .....n..........n.......
        .....nN........Nn.......
        ......NN.jjjj.NN........
        .......hjjqqqqqh........
        ......hjjqqqsssss.......
        .....hjjqqssssssss......
        ....hhjqqssssssssq......
        ....hjjqsssSSKssqs......
        ...hhjqssSwesssqsss.....
        ...hjjqsssssssqssssI....
        ...hjhSssssssqssssIuu...
        ..hhjhSsssssssssssuuu...
        ..hjhHSSsssssssssuUu....
        ..hjhHSSSsssKKSSSSiu....
        ..hjHHbSSSSSSSSSSS......
        ..hHHHb.SSSSSSSSS.......
        ..hHH..ttttttttt........
        ..hH.yttttttttttttt.....
        .hH.yyttttttttttttttt...
        .hyyyyttttttttttttttttt.
        yyyytttttttttttttttttTT.
        yyytttttttttttttttttTTTT
    """),
    "ring": pp(16, """
        ....................c...
        ...................cC...
    """),
    # overlays
    "stripe": pp(10, """
        .............rrr........
        ..............rrr.......
    """),
    "cheek": pp(12, """
        ........r...............
        .......r.r..............
    """),
    "feather": pp(5, """
        ..f.....................
        .ff.....................
        .fF.....................
        .fF.....................
        ..F.....................
    """),
    "bonnet": pp(0, """
        ......F.F.F.F.F.........
        .....FfFfFfFfFfF........
        .....ffffffffffff.......
        ......aAaAaAaAaA........
    """),
    "hood": pp(3, """
        ......xxxxxxx...........
        .....xxxxxxxxx..........
        ....xxxxxxxxxxx.........
        ...xxxxxxxxxxxxX........
        ...xxxxXXXXXXXXX........
        ...xxX..................
        ..xxX...................
        ..xxX...................
        ..xxX...................
        ..xXX...................
        ..xXX...................
        ..xXX...................
        ..XXX...................
    """),
    "mask": pp(12, """
        .............xxxxxxxx...
        ............xxxxxxxxx...
        ............xXXXXXXXX...
        .............XXXXXXX....
    """),
    "hat": pp(0, """
        ........xxxxxx..........
        .......xxxxxxxx.........
        ......xxxxxxxxxx........
        ......aaaaaaaaaaA.......
        ..xxxxxxxxxxxxxxxxxxX...
        .XXXXXXXXXXXXXXXXXXXXX..
    """),
    "scarf": pp(3, """
        .........xxxxxx.........
        .......xxxxxxxxX........
        ......xXXXXXXXXX........
        .....xX.................
        ....xxX.................
    """),
    "beard": pp(16, """
        ..........jhhhhh........
        ..........jhhhhH........
        ...........jhhH.........
        ...........hhH..........
        ............H...........
    """),
    "bands": pp(2, """
        ..cC....................
        ....cC..............cC..
        ...................Cc...
    """),
    "moons": pp(6, """
        .........w...w..........
        ..........w...w.........
        .........w...w..........
    """),
    "beads": pp(13, """
        ..b.....................
        ........................
        ..b.....................
        ........................
        .b......................
    """),
    "leaves": pp(3, """
        ........l.l.............
        .......lLlLl............
        ......l.................
    """),
    "spikes": pp(0, """
        ........j...j...........
        .......jh..jh.j.........
        ......jhhjjhhjh.........
        .....hhhhhhhhh..........
    """),
    "flower": pp(3, """
        ........r.r.............
        .........a..............
        ........r.r.............
    """),
    "pauldrons": pp(17, """
        ....ccccc.......ccccc...
        ...ccccccCa....ccccccC..
        ..cccCCCCCa...cccCCCCCC.
        ..cCCCCCCa....cCCCCCCCC.
        .CCCCCCCa.....CCCCCCCCCC
    """),
    "hide": pp(18, """
        .....aaaaaaa............
        ....aAAAAAAAa...........
        ...aa.......aa..........
    """),
    "necklace": pp(18, """
        ........a.a.a.a.........
        .........a.b.a..........
    """),
    "strap": pp(17, """
        ................g.......
        ...............g........
        ..............g.........
        .............g..........
        ............g...........
        ...........g............
    """),
    "spear": pp(4, """
        ......................c.
        .....................cC.
        .....................cC.
        ......................g.
        ......................g.
        ......................G.
        ......................g.
        ......................g.
        ......................G.
        ......................g.
        ......................g.
        ......................G.
        ......................g.
        ......................G.
    """),
}


@dataclass(frozen=True)
class Portrait:
    body: str                       # "male" / "female"
    over: tuple[str, ...]           # overlays drawn before the outline
    legend: dict[str, str]
    note: str
    post: tuple[str, ...] = ()      # overlays after the outline (paint, moons)
    glow: bool = False              # spirit eyes


def _p(body: str, over: tuple[str, ...], note: str, fur: str, hair: str, post=(), glow=False, **slots) -> Portrait:
    return Portrait(body, over, legend(fur, hair, **slots), note, tuple(post), glow)


PORTRAITS = {
    "adana_thunderhorn": _p("female", ("hide", "beads"), "Thunderhorn brave leader: war paint, hide mantle",
                            "brown", "black", post=("stripe",), y="tent2", t="tent1", T="tent0",
                            a="bone4", A="bone2", r="red2"),
    "ahmo_thunderhorn": _p("male", ("feather", "pauldrons", "ring"), "Bloodhoof Village warrior: steel pauldrons",
                           "dark", "black", y="red2", t="red1", T="red0", c="steel4", C="steel3", a="gold1",
                           f="white", F="red2"),
    "aska_mistrunner": _p("female", ("scarf", "flower", "strap"), "cooking trainer: headscarf and apron",
                          "fawn", "brown", y="sand4", t="sand3", T="sand2", x="red3", X="red2",
                          a="gold2", r="white", g="sand2"),
    "baine_bloodhoof": _p("male", ("bands", "pauldrons", "necklace", "ring"),
                          "the young high chieftain: dark fur, gold horn bands, bronze armour",
                          "dark", "black", y="leather3", t="leather2", T="leather1", c="gold1", C="gold0",
                          a="gold2", b="red3", n="bone4"),
    "boarton_shadetotem": _p("male", ("hood", "mask"), "rogue trainer: dark hood and face mask",
                             "brown", "black", y="leather3", t="leather2", T="leather1", x="grey1", X="grey0"),
    "chief_hawkwind": _p("male", ("bonnet", "beard"), "old chieftain: white mane, hawk-feather war bonnet",
                         "grey", "white", y="tent2", t="tent1", T="tent0", f="white", F="azp_fur2",
                         a="red2", A="red1"),
    "grull_hawkwind": _p("male", ("feather", "hide"), "the chief's son, a young brave",
                         "brown", "black", y="sand3", t="sand2", T="sand1", f="azp_fur4", F="azp_fur1",
                         a="red2", A="red1"),
    "kah_mistrunner": _p("male", ("hat",), "fishing trainer: straw hat", "fawn", "brown",
                         y="water3", t="water2", T="water1", x="sand4", X="sand3", a="water2", A="water1"),
    "morin_cloudstalker": _p("male", ("scarf", "spear"), "outrunner of the Mulgore road: sky-blue scarf, spear",
                             "rust", "black", y="olive3", t="olive2", T="olive1", x="water4", X="water3",
                             c="chrome2", C="chrome1", g="dust4", G="dust3"),
    "mull_thunderhorn": _p("male", ("beard", "necklace", "beads"), "keeper of the sacred wells: turquoise beads",
                           "brown", "grey", y="water3", t="water2", T="water1", a="bone4", b="cryst1"),
    "spiritwalker_ussoh": _p("male", ("necklace",), "spiritwalker: pale fur, spirit-lit eyes",
                             "pale", "white", post=("cheek",), glow=True, y="water2", t="water1", T="water0",
                             a="bone4", b="glowcyan", r="water4", z="glowcyan"),
    "una_wildmane": _p("female", ("leaves", "beads", "necklace"), "wild white mane, turquoise beads, leaves",
                       "brown", "white", y="olive3", t="olive2", T="olive1", a="bone4", b="cryst1"),
    "yaw_sharpmane": _p("male", ("spikes", "strap"), "hunter trainer: spiked mane, bow strap",
                        "tan", "black", y="olive2", t="olive1", T="olive0", g="tent2"),
    "zarlman_two_moons": _p("male", ("beard", "necklace"), "spiritual leader: two moons painted on the brow",
                            "brown", "white", post=("moons",), y="flora3", t="flora2", T="flora1",
                            a="bone4", b="cryst1"),
    "hero": _p("male", ("feather", "hide"), "the hero: yellow tunic, turquoise scarf", "brown", "black",
               y="jacket3", t="jacket2", T="jacket1", a="cryst1", A="cryst0", f="white", F="cryst1"),
}


def portrait_grid(p: Portrait) -> Grid:
    parts = [PORTRAIT[p.body]] + [PORTRAIT[n] for n in p.over]
    g = compose(parts, [PORTRAIT[n] for n in p.post], size=(PW, PW))
    return swap(g, {"w": "z", "e": "z"}) if p.glow else g


def _register_portraits() -> None:
    for npc, p in PORTRAITS.items():
        register(f"az.portrait.{npc}", art(portrait_grid(p), legend=p.legend, note=p.note))


_register_portraits()
