"""City people: the runner (five metatypes, plain and augmented) and every NPC
role x metatype of the cyberpunk chapter.

Everyone faces RIGHT in the same 3/4 side view as the Tau-7 survivor (the
renderer mirrors for left and adds the drop shadow) and stands with the soles
on the bottom row, so the default bottom-centre anchor is the ground point.

How the art is built
--------------------
Each metatype has a *rig*: hand-drawn, fill-only body parts (legs per pose,
torso, bald head, hairstyles, near-arm poses, role pieces such as coats, caps
or visors) written in *slot* characters instead of colours.  A figure is a
list of parts layered in order; the 1px ``ink`` outline is added after
composing (``outline_grid``), so any piece that changes the silhouette - a
coat tail, a mohawk, a raised baton - gets a clean outline for free.  A role
is a recipe (which parts in which frame) plus a slot -> palette mapping; the
skin tone and hair colour come from a per role x race cast table, so a street
is not a row of clones while each role keeps its uniform.

Slot characters (every rig uses the same ones)::

    q s S   skin      light / mid / shadow        e  eye (glows when augmented)
    j h H   hair      light / mid / shadow        m  open mouth
    y t T   top       light / mid / shadow        v  tusk
    x r R   sleeve    light / mid / shadow        n N  horn light / dark
    d D     hand      mid / shadow (skin, glove or chrome)
    o p P   trousers  light / mid / shadow        b B  boots mid / shadow
    i a A   accent    light / mid / shadow        u U  second garment mid / shadow
    g G     glow      bright / dim                c C  metal light / dark
    k K w   ink, ink2, white (always available)

Animations: ``idle`` 8 frames @4 fps (breathing at the reference 2 fps with a
blink - or a glint / visor sweep - once per loop), ``talk`` 4 frames @4 fps
(the mouth moves every frame, the gesture every other), hero ``walk`` 4
frames @8 fps with a 1px bob, ``hurt`` 1 frame.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from ..pixelart import Grid, art, blank, grid, outline_grid, overlay, swap
from ..registry import register

RACE_NAMES = ("human", "elf", "dwarf", "ork", "troll")
ROLE_NAMES = ("fixer", "vendor", "doc", "ganger", "civilian", "collector")


# --- parts and composition ---------------------------------------------------------


@dataclass(frozen=True)
class Part:
    """A fill-only piece of a figure: full-width rows placed at row ``y``."""

    rows: Grid
    x: int = 0
    y: int = 0

    def at(self, dx: int = 0, dy: int = 0) -> "Part":
        return Part(self.rows, self.x + dx, self.y + dy)


def part(y: int, text: str, x: int = 0) -> Part:
    return Part(grid(text), x, y)


def dot(x: int, y: int, ch: str) -> Part:
    return Part((ch,), x, y)


def compose(size: tuple[int, int], parts, post=()) -> Grid:
    """Layer parts in order, outline the silhouette, then add unoutlined glows."""
    out = blank(*size)
    for p in parts:
        out = overlay(out, p.rows, p.x, p.y)
    out = outline_grid(out, "k")
    for p in post:
        out = overlay(out, p.rows, p.x, p.y)
    return out


class Rig:
    """One metatype's body parts plus where its eye and mouth are (stand pose)."""

    def __init__(self, race: str, size: tuple[int, int], eye: tuple[int, int],
                 mouth: tuple[int, int], parts: dict[str, Part], over: tuple[str, ...] = ()) -> None:
        self.race, self.size, self.eye, self.mouth, self.parts = race, size, eye, mouth, parts
        self.over = over  # drawn after hair and headgear: elf ears, troll horns

    def __getitem__(self, name: str) -> Part:
        try:
            return self.parts[name]
        except KeyError:
            raise KeyError(f"{self.race} rig has no part {name!r}") from None


@dataclass(frozen=True)
class Look:
    """What a figure wears, by layer. ``skirt`` hangs from the hips and does not
    breathe (coat tails, aprons); ``wear`` sits on the torso; ``gear`` on the head."""

    hair: str = ""
    skirt: tuple[str, ...] = ()
    wear: tuple[str, ...] = ()
    gear: tuple[str, ...] = ()


def figure(rig: Rig, look: Look, legs: str = "legs.stand", arm: str = "arm.down", *,
           far: str = "", dx: int = 0, dy: int = 0, head: tuple[int, int] = (0, 0),
           mouth: bool = False, blink: bool = False, extra: tuple[str, ...] = (),
           gear: tuple[str, ...] | None = None, post: tuple[Part, ...] = ()) -> Grid:
    """One frame: legs and skirt stay put, everything above moves by (dx, dy)
    (breathing, walk bob, recoil) and the head group by a further ``head``."""
    hx, hy = head
    lower = [rig[legs]] + [rig[n] for n in look.skirt]
    body = [rig["torso"]] + [rig[n] for n in look.wear]
    heads = [rig["head"]] + ([rig[look.hair]] if look.hair else [])
    heads += [rig[n] for n in (look.gear if gear is None else gear)]
    heads += [rig[n] for n in rig.over]
    if mouth:
        heads.append(dot(*rig.mouth, "m"))
    top = [rig[arm]] + [rig[n] for n in extra]
    parts = [rig[far].at(dx, dy)] if far else []
    parts += lower + [p.at(dx, dy) for p in body]
    parts += [p.at(dx + hx, dy + hy) for p in heads] + [p.at(dx, dy) for p in top]
    g = compose(rig.size, parts, [p.at(dx, dy) for p in post])
    return swap(g, {"e": "S"}) if blink else g


# --- colours ------------------------------------------------------------------------

SKIN = {  # light, mid, shadow
    "fair": ("skin4", "skin3", "skin2"),
    "tan": ("skin3", "skin2", "skin1"),
    "brown": ("skin2", "skin1", "skin0"),
    "pale": ("elf3", "elf2", "elf1"),
    "rose": ("skin4", "elf2", "elf1"),
    "ork": ("ork4", "ork3", "ork2"),
    "ork_dark": ("ork3", "ork2", "ork1"),
    "troll": ("troll4", "troll3", "troll2"),
    "troll_dark": ("troll3", "troll2", "troll1"),
}
HAIR = {  # light, mid, shadow
    "black": ("grey1", "ink2", "hair_black"),
    "brown": ("rust2", "hair_brown", "skin0"),
    "blond": ("sand4", "hair_blond", "gold1"),
    "red": ("hair_copper", "hair_red", "rust1"),
    "copper": ("tent3", "hair_copper", "hair_red"),
    "white": ("white", "hair_white", "grey3"),
    "grey": ("grey4", "grey3", "grey2"),
    "blue": ("glass4", "hair_blue", "denim2"),
    "green": ("moss5", "hair_green", "neon_green_dim"),
    "pink": ("spore4", "hair_pink", "spore2"),
    "mohawk": ("spore4", "hair_pink", "neon_pink_dim"),
}

BASE = {"e": "ink2", "m": "red1", "v": "tusk", "n": "bone3", "N": "bone1",
        "g": "neon_cyan", "G": "neon_cyan_dim", "c": "chrome2", "C": "chrome0"}


def legend(outfit: dict[str, str], skin: str, hair: str, hands: str = "skin") -> dict[str, str]:
    q, s, S = SKIN[skin]
    j, h, H = HAIR[hair]
    out = {**BASE, "q": q, "s": s, "S": S, "j": j, "h": h, "H": H}
    if hands == "skin":
        out.update(d=s, D=S)
    out.update(outfit)
    return out


# the runner: yellow jacket (the yellow @), dark jeans, the orange scarf cut from
# the Tau-7 survival suit
HERO_OUTFIT = {
    "y": "jacket3", "t": "jacket2", "T": "jacket1",
    "x": "jacket3", "r": "jacket2", "R": "jacket1",
    "o": "denim2", "p": "denim1", "P": "denim0",
    "b": "leather3", "B": "leather1",
    "i": "suit4", "a": "suit3", "A": "suit1",
    "u": "grey1", "U": "grey0",
}
# cyberware: the near arm is chrome from the shoulder (the sleeve torn off), one eye glows
AUG = {"x": "chrome3", "r": "chrome1", "R": "chrome0", "d": "chrome2", "D": "chrome1",
       "e": "neon_cyan"}

OUTFITS = {
    # long indigo coat, popped collar lined in cyan, shades with a neon glint, commlink
    "fixer": {"y": "city5", "t": "city4", "T": "city3", "x": "city5", "r": "city4", "R": "city3",
              "o": "grey1", "p": "grey0", "P": "ink2", "b": "grey1", "B": "grey0",
              "i": "neon_cyan", "a": "neon_cyan_dim", "A": "city2", "u": "grey2", "U": "grey1",
              "g": "neon_cyan", "G": "neon_cyan_dim", "c": "chrome1", "C": "grey0"},
    # blue work shirt, olive apron, green cap, neon-green cred reader
    "vendor": {"y": "denim3", "t": "denim2", "T": "denim1", "x": "denim3", "r": "denim2", "R": "denim1",
               "o": "leather3", "p": "leather2", "P": "leather1", "b": "rust2", "B": "rust1",
               "i": "moss5", "a": "moss4", "A": "moss3", "u": "olive3", "U": "olive2",
               "g": "neon_green", "G": "neon_green_dim", "c": "grey2", "C": "grey1"},
    # white coat over teal scrubs, red cross, blue gloves, goggles, glowing syringe
    "doc": {"y": "white", "t": "grey4", "T": "grey3", "x": "white", "r": "grey4", "R": "grey3",
            "d": "water4", "D": "water3",
            "o": "grey2", "p": "grey1", "P": "grey0", "b": "grey1", "B": "grey0",
            "i": "red4", "a": "red3", "A": "red2", "u": "cryst1", "U": "cryst0",
            "g": "glowcyan", "G": "cryst1", "c": "chrome2", "C": "chrome0"},
    # sleeveless black-leather vest with chrome spikes, tattooed arms, ripped jeans
    "ganger": {"y": "leather3", "t": "leather2", "T": "leather1",
               "o": "denim2", "p": "denim1", "P": "denim0", "b": "grey1", "B": "grey0",
               "i": "neon_pink", "a": "neon_pink_dim", "A": "ink2", "u": "grey2", "U": "grey1",
               "g": "neon_pink", "G": "neon_pink_dim", "c": "chrome3", "C": "chrome1"},
    # plain hoodie in a muted colour, jeans, sneakers, hands in the pouch
    "civilian": {"y": "grey3", "t": "grey2", "T": "grey1", "x": "grey3", "r": "grey2", "R": "grey1",
                 "o": "denim2", "p": "denim1", "P": "denim0", "b": "bone3", "B": "bone2",
                 "i": "grey3", "a": "grey2", "A": "grey1", "u": "grey1", "U": "grey0",
                 "g": "neon_cyan", "G": "neon_cyan_dim", "c": "grey3", "C": "grey1"},
    # black suit, white shirt, dark tie, black gloves, glowing red visor, stun baton
    "collector": {"y": "grey2", "t": "grey1", "T": "grey0", "x": "grey2", "r": "grey1", "R": "grey0",
                  "d": "grey1", "D": "grey0",
                  "o": "grey1", "p": "grey0", "P": "ink2", "b": "grey1", "B": "ink2",
                  "i": "red3", "a": "red2", "A": "red1", "u": "grey4", "U": "grey3",
                  "g": "neon_red", "G": "neon_red_dim", "W": "fire5", "c": "chrome2", "C": "chrome0"},
}


@dataclass(frozen=True)
class Role:
    look: Look
    idle_arm: str
    talk_arms: tuple[str, str]
    hands: str = "skin"  # skin | glove (the outfit colours the hands)
    blink: bool = True  # False when the eyes are hidden (shades, visor)
    extra: tuple[str, ...] = ()  # drawn over the arm (a sleeve cross, a tattoo)
    # gear part -> replacement per frame index (a glint, a visor sweep)
    cycle: dict[str, tuple[str, ...]] = field(default_factory=dict)


_GLINT = ("fixer.shades",) * 7 + ("fixer.shades2",)
_SWEEP = ("collector.visor", "collector.visor1", "collector.visor2", "collector.visor1") * 2

ROLES = {
    "fixer": Role(Look("hair.slick", ("fixer.coat",), (), ("fixer.collar", "fixer.shades")),
                  "fixer.hold", ("fixer.show", "fixer.show2"), blink=False,
                  cycle={"fixer.shades": _GLINT}),
    "vendor": Role(Look("hair.short", ("vendor.apron",), ("vendor.bib",), ("vendor.cap",)),
                   "vendor.rest", ("arm.open", "vendor.reader")),
    "doc": Role(Look("hair.short", ("doc.coat",), ("doc.scrubs",), ("doc.goggles",)),
                "doc.gloves_up", ("doc.syringe", "doc.syringe2"), hands="glove",
                extra=("doc.cross",)),
    "ganger": Role(Look("", (), ("ganger.spikes",), ("ganger.mohawk",)),
                   "arm.down", ("ganger.point", "ganger.pump"), extra=("ganger.tattoo",)),
    "civilian": Role(Look("", (), (), ("civilian.hood",)),
                     "civilian.pocket", ("civilian.shrug", "arm.open")),
    "collector": Role(Look("hair.crop", (), ("collector.shirt",), ("collector.visor",)),
                      "collector.baton", ("collector.raise", "collector.tap"), hands="glove",
                      blink=False, cycle={"collector.visor": _SWEEP}),
}

# idle: breathe in, in, out, out (x2) = the reference 2 fps; the last frame blinks
IDLE_DY = (0, 0, 1, 1, 0, 0, 1, 1)


def _gear(look: Look, role: Role, i: int) -> tuple[str, ...]:
    return tuple(role.cycle[n][i % len(role.cycle[n])] if n in role.cycle else n for n in look.gear)


def npc_frames(rig: Rig, role: Role, look: Look) -> tuple[list[Grid], list[Grid]]:
    idle = [figure(rig, look, arm=role.idle_arm, dy=dy, blink=role.blink and i == 7,
                   gear=_gear(look, role, i), extra=role.extra)
            for i, dy in enumerate(IDLE_DY)]
    talk = [figure(rig, look, arm=role.talk_arms[i // 2], mouth=i % 2 == 0,
                   gear=_gear(look, role, i), extra=role.extra)
            for i in range(4)]
    return idle, talk


HERO_LOOK = Look("hair.hero", (), ("hero.scarf", "hero.tee"), ())


def hero_frames(rig: Rig, look: Look = HERO_LOOK) -> dict[str, list[Grid]]:
    idle = [figure(rig, look, dy=dy, blink=i == 7, extra=("hero.tail.down",))
            for i, dy in enumerate(IDLE_DY)]
    walk = [
        figure(rig, look, "legs.w0", "arm.back", far="far.fwd", extra=("hero.tail.down",)),
        figure(rig, look, "legs.w1", "arm.down", dy=-1, extra=("hero.tail.up",)),
        figure(rig, look, "legs.w2", "arm.fwd", far="far.back", extra=("hero.tail.down",)),
        figure(rig, look, "legs.w3", "arm.down", dy=-1, extra=("hero.tail.mid",)),
    ]
    # doubled over, clutching the gut: what the collector's baton does
    hurt = [figure(rig, look, "legs.hurt", "arm.clutch", dy=1, head=(1, 0), mouth=True,
                   blink=True, extra=("hero.tail.up",))]
    return {"idle": idle, "walk": walk, "hurt": hurt}


# --- the human rig (16x16) ----------------------------------------------------------
# head rows 2-6 (eye 9,5, nose 11,5, mouth 9,6), torso rows 7-11 with the near arm
# at x 7-9 (7 = the ink line on its back edge), legs rows 12-13, boots row 14.

HUMAN = Rig("human", (16, 16), eye=(9, 5), mouth=(9, 6), parts={
    "head": part(2, """
        .....qqsss......
        ....qqsssss.....
        ....sssssss.....
        ....sSSssess....
        .....SSsss......
        """),
    "hair.hero": part(2, """
        .....jjhhhh.....
        ....jhhhhhhhh...
        ....hhhhHhs.....
        ....hhHh........
        ....hHh.........
        """),
    "hair.short": part(2, """
        .....jjhhh......
        ....jhhhhhhh....
        ....hhhhhhh.....
        ....hhHh........
        .....Hh.........
        """),
    "hair.slick": part(2, """
        .....jjhhh......
        ....jhhhhhh.....
        ....hhhhhH......
        ....hhHH........
        .....H..........
        """),
    "hair.crop": part(2, """
        .....hhhhh......
        ....hhhhhhH.....
        ....hHHh........
        """),
    "torso": part(7, """
        ......tttt......
        .....yyyttt.....
        .....yyyttt.....
        .....yyyttT.....
        .....TTTTTT.....
        """),
    "legs.stand": part(12, """
        ......PPpP......
        ......PP.pP.....
        .....BBB.bbB....
        """),
    "legs.w0": part(12, """
        .....PPppP......
        ....PP...pP.....
        ...BBB....bbB...
        """),
    "legs.w1": part(11, """
        ......PPpp......
        ......PPpp......
        .....BBBpp......
        ........bbB.....
        """),
    "legs.w2": part(12, """
        .....ppPPP......
        ....pP...PP.....
        ...bbB....BBB...
        """),
    "legs.w3": part(11, """
        ......PPpp......
        ......PPpp......
        ......PPbbB.....
        .....BBB........
        """),
    "legs.hurt": part(13, """
        ....PPp.pPp.....
        ...BBB...bbB....
        """),
    "arm.down": part(8, """
        .......kxr......
        .......kxr......
        .......kxR......
        .......kdD......
        """),
    "arm.back": part(8, """
        .......kxr......
        .......kxr......
        ......kxR.......
        ......kdD.......
        """),
    "arm.fwd": part(8, """
        .......kxr......
        .......kxr......
        ........kxR.....
        ........kdD.....
        """),
    "far.fwd": part(10, """
        ...........D....
        """),
    "far.back": part(10, """
        ....D...........
        """),
    "arm.clutch": part(8, """
        .......kxr......
        .......kxRr.....
        ........kRdD....
        """),
    "arm.open": part(8, """
        .......kxr......
        .......kxr..dD..
        .......kxRrr....
        """),
    "arm.open_up": part(7, """
        ............dD..
        .......kxr.rr...
        .......kxrr.....
        .......kxR......
        """),
    # the runner
    "hero.scarf": part(7, """
        .....Aaaai......
        """),
    "hero.tee": part(8, """
        ..........u.....
        ..........u.....
        ..........U.....
        """),
    "hero.tail.down": part(8, """
        ....a...........
        ....A...........
        """),
    "hero.tail.up": part(7, """
        ...aa...........
        ..A.............
        """),
    "hero.tail.mid": part(7, """
        ....a...........
        ...a............
        ...A............
        """),
    # fixer
    "fixer.coat": part(12, """
        .....yttttT.....
        ....yyttTT......
        """),
    "fixer.collar": part(4, """
        ...tT...........
        ...ta...........
        ....ta..........
        .....t..........
        """),
    "fixer.shades": part(5, """
        ........kKg.....
        """),
    "fixer.shades2": part(5, """
        ........kgK.....
        """),
    "fixer.hold": part(8, """
        .......kxr......
        .......kxr..g...
        .......kxRrdC...
        """),
    "fixer.show": part(7, """
        ............gC..
        .......kxr..dD..
        .......kxrrr....
        .......kxR......
        """),
    "fixer.show2": part(7, """
        ................
        .......kxr..GC..
        .......kxrrdD...
        .......kxR......
        """),
    # vendor
    "vendor.cap": part(1, """
        ......iaa.......
        .....iaaaa......
        ....aaaaaaAAA...
        """),
    "vendor.apron": part(11, """
        ........uuU.....
        .......uuuU.....
        .......uuUU.....
        """),
    "vendor.bib": part(7, """
        .........U......
        ..........u.....
        ..........u.....
        """),
    "vendor.rest": part(8, """
        .......kxr......
        .......kxr......
        .......kxrrd....
        """),
    "vendor.reader": part(7, """
        ............Cg..
        .......kxr..dD..
        .......kxrrr....
        .......kxR......
        """),
    # doc
    "doc.coat": part(12, """
        .....yttttT.....
        ....yyttTT......
        """),
    "doc.scrubs": part(7, """
        .........u......
        ..........u.....
        ..........u.....
        ..........U.....
        """),
    "doc.goggles": part(3, """
        ....CCCCCgG.....
        """),
    "doc.cross": part(8, """
        ........a.......
        .......aaa......
        ........a.......
        """),
    "doc.gloves_up": part(7, """
        ..........dD....
        .......kxr.r....
        .......kxrr.....
        .......kxR......
        """),
    "doc.syringe": part(8, """
        .......kxr...cg.
        .......kxrrdD...
        .......kxR......
        """),
    "doc.syringe2": part(7, """
        .............g..
        .......kxr..c...
        .......kxrrdD...
        .......kxR......
        """),
    # ganger
    "ganger.spikes": part(7, """
        .....c..........
        ....c...........
        """),
    "ganger.mohawk": part(0, """
        .......g.g......
        ......jhhhh.....
        .....hhhhH......
        ....SS..........
        ....Sa..........
        """),
    "ganger.tattoo": part(9, """
        ........a.......
        """),
    "ganger.point": part(8, """
        .......kxrrrdD..
        .......kxR......
        """),
    "ganger.pump": part(5, """
        ..........dD....
        ..........rr....
        ..........r.....
        .......kxrr.....
        .......kxR......
        """),
    # civilian
    "civilian.hood": part(1, """
        ......yyt.......
        .....yyttt......
        ....yyttttT.....
        ....ytTK........
        ....ytK.........
        .....tT.........
        """),
    "civilian.pocket": part(8, """
        .......kxr......
        .......kxr......
        .......kxRr.....
        ........kRU.....
        """),
    "civilian.shrug": part(8, """
        .......kxr......
        .......kxr......
        .......kxRr.dD..
        ..........rr....
        """),
    # collector
    "collector.shirt": part(7, """
        ........uu......
        ..........A.....
        ..........A.....
        """),
    "collector.visor": part(4, """
        ........CCC.....
        ......CCWggG....
        """),
    "collector.visor1": part(4, """
        ........CCC.....
        ......CCgWgG....
        """),
    "collector.visor2": part(4, """
        ........CCC.....
        ......CCggWG....
        """),
    "collector.baton": part(8, """
        .......kxr......
        .......kxr......
        .......kxR......
        .......kdD......
        .........c......
        ..........c.....
        ...........g....
        """),
    "collector.raise": part(4, """
        .............g..
        ............c...
        ...........c....
        ..........dD....
        .......kxrr.....
        .......kxR......
        """),
    "collector.tap": part(8, """
        .......kxr......
        .......kxr......
        .......kxRrdDccg
        """),
})

# --- derived rigs ---------------------------------------------------------------------
# Elf, ork and dwarf reuse the human's role pieces (collars, shades, visors, caps, props
# in hand) moved as groups - head gear with the head, arm poses with the shoulder - and
# redraw everything that makes the metatype: head, torso, legs and whatever hangs over
# them.

_HEAD_GEAR = {"fixer.collar", "fixer.shades", "fixer.shades2", "vendor.cap", "doc.goggles",
              "ganger.mohawk", "civilian.hood", "collector.visor", "collector.visor1",
              "collector.visor2"}
_BODY_WEAR = {"torso", "hero.scarf", "hero.tee", "hero.tail.down", "hero.tail.up",
              "hero.tail.mid", "vendor.bib", "doc.scrubs", "ganger.spikes", "collector.shirt"}
_SKIRTS = {"fixer.coat", "vendor.apron", "doc.coat"}


def _group(name: str) -> str:
    if name.startswith("legs.") or name in _SKIRTS:
        return "legs"
    if name == "head" or name.startswith("hair.") or name in _HEAD_GEAR:
        return "head"
    return "body" if name in _BODY_WEAR else "arm"


def derive(race: str, size: tuple[int, int], eye: tuple[int, int], mouth: tuple[int, int],
           offsets: dict[str, tuple[int, int]], parts: dict[str, Part],
           over: tuple[str, ...] = ()) -> Rig:
    """A rig whose unlisted parts are the human's, moved by their group's offset."""
    out = {}
    for name, p in HUMAN.parts.items():
        off = offsets.get(_group(name))
        if off is not None:
            out[name] = p.at(*off)
    out.update(parts)
    missing = sorted(set(HUMAN.parts) - set(out))
    if missing:
        raise ValueError(f"{race} rig lacks {missing}")
    return Rig(race, size, eye, mouth, out, over)


def _coat(y: int, text: str) -> dict[str, Part]:
    p = part(y, text)
    return {"fixer.coat": p, "doc.coat": p}


# --- elf: slim and a head taller, long legs, a long pointed ear ----------------------
ELF = derive("elf", (16, 16), eye=(9, 4), mouth=(9, 5), over=("ear",),
             offsets={"head": (0, -1), "body": (0, -1), "arm": (0, -1)}, parts={
    "head": part(1, """
        ......qqss......
        .....qsssss.....
        .....ssssss.....
        .....sSssess....
        ......SSsss.....
        .......SS.......
        """),
    "ear": part(1, """
        ...q............
        ....qs..........
        .....sS.........
        """),
    "hair.hero": part(1, """
        ......jjhh......
        .....jhhhhhh....
        .....hhhhhh.....
        .....hhHh.......
        .....hHh........
        .....hH.........
        .....H..........
        .....H..........
        """),
    "hair.short": part(1, """
        ......jjhh......
        .....jhhhhhh....
        .....hhhhhh.....
        .....hhH........
        ......H.........
        """),
    "hair.slick": part(1, """
        ......jjhh......
        .....jhhhhh.....
        .....hhhhH......
        .....hH.........
        """),
    "hair.crop": part(1, """
        ......hhhh......
        .....hhhhhH.....
        .....hH.........
        """),
    "torso": part(7, """
        ......yyttt.....
        ......yyttt.....
        ......yyttT.....
        ......TTTTT.....
        """),
    "legs.stand": part(11, """
        ......PPpP......
        ......PP.pP.....
        ......PP.pP.....
        .....BBB.bbB....
        """),
    "legs.w0": part(11, """
        ......PPpP......
        .....PP..pP.....
        ....PP....pP....
        ...BBB....bbB...
        """),
    "legs.w1": part(10, """
        ......PPpp......
        ......PPpp......
        ......PPpp......
        .....BBBpp......
        ........bbB.....
        """),
    "legs.w2": part(11, """
        ......ppPP......
        .....pP..PP.....
        ....pP....PP....
        ...bbB....BBB...
        """),
    "legs.w3": part(10, """
        ......PPpp......
        ......PPpp......
        ......PPpp......
        ......PPbbB.....
        .....BBB........
        """),
    "legs.hurt": part(12, """
        .....PPppP......
        ....PPp..pPp....
        ...BBB....bbB...
        """),
    **_coat(11, """
        ......ytttT.....
        .....yyttTT.....
        .....yyttT......
        """),
    "vendor.apron": part(10, """
        .........uU.....
        ........uuU.....
        ........uUU.....
        """),
    "ganger.mohawk": part(0, """
        ......gjgj......
        ......hhhhH.....
        """),
    "civilian.hood": part(1, """
        ......yytt......
        .....yyttttT....
        ....yyttTK......
        ....yttK........
        ....ytT.........
        .....tT.........
        """),
    "vendor.cap": part(1, """
        .....iaaaa......
        .....aaaaaAAA...
        """),
})

# --- ork: broad shoulders, a heavy underbite jaw with tusks -----------------------------
_ORK_TAILS = {n: HUMAN[n].at(-1, 1) for n in ("hero.tail.down", "hero.tail.up", "hero.tail.mid")}
ORK = derive("ork", (16, 16), eye=(9, 5), mouth=(11, 6),
             offsets={"head": (0, 0), "body": (1, 0), "arm": (1, 0)}, parts={
    "head": part(2, """
        .....qqsss......
        ....qssssss.....
        ....sSSSSSs.....
        ....sSsssessv...
        ....Sssssssss...
        .....SSSSSSS....
        """),
    "torso": part(7, """
        ....yyyttt......
        ....yyyytttt....
        ....yyyytttt....
        ....yyyyttTT....
        ....TTTTTTTT....
        """),
    "hero.scarf": HUMAN["hero.scarf"].at(0, 1),
    **_ORK_TAILS,
    "ganger.spikes": HUMAN["ganger.spikes"].at(-1, 0),
    "collector.shirt": HUMAN["collector.shirt"].at(1, 1),
    "legs.stand": part(12, """
        .....PPPppP.....
        .....PPP.ppP....
        ....BBBB.bbbB...
        """),
    "legs.w0": part(12, """
        ....PPPpppP.....
        ...PPP....ppP...
        ..BBBB....bbbB..
        """),
    "legs.w1": part(11, """
        ......PPPpp.....
        ......PPPpp.....
        .....BBBBpp.....
        ........bbbB....
        """),
    "legs.w2": part(12, """
        ....pppPPPP.....
        ...ppP....PPP...
        ..bbbB....BBBB..
        """),
    "legs.w3": part(11, """
        ......PPPpp.....
        ......PPPpp.....
        ......PPPbbbB...
        .....BBBB.......
        """),
    "legs.hurt": part(13, """
        ....PPPp.ppPp...
        ...BBBB...bbbB..
        """),
    **_coat(12, """
        ....yytttttT....
        ...yyytttTT.....
        """),
    "vendor.apron": part(11, """
        .........uuU....
        ........uuuU....
        ........uuUU....
        """),
})

# --- dwarf: three quarters tall, stocky, a big beard over the chest ---------------------
DWARF = derive("dwarf", (16, 16), eye=(9, 8), mouth=(10, 10),
               offsets={"head": (0, 3), "body": (0, 3), "arm": (0, 2)}, parts={
    "head": part(5, """
        .....qqsss......
        ....qqsssss.....
        ....sssssss.....
        ....sSSssessq...
        ....hhhhhhhhh...
        .....jhhhhhhh...
        ......hhhhhhH...
        .......hhhhH....
        """),
    "torso": part(9, """
        ...yyyttt.......
        ...yyyytttt.....
        ...yyyytttT.....
        ...TTTTTTTT.....
        """),
    "hero.tee": part(11, """
        ..........u.....
        """),
    "doc.scrubs": part(11, """
        ..........u.....
        """),
    "ganger.spikes": HUMAN["ganger.spikes"].at(-1, 2),
    "legs.stand": part(13, """
        .....PPP.pPP....
        ....BBBB.bbbB...
        """),
    "legs.w0": part(13, """
        ....PPP...pPP...
        ...BBBB...bbbB..
        """),
    "legs.w1": part(12, """
        ......PPPpp.....
        .....BBBBpp.....
        ........bbbB....
        """),
    "legs.w2": part(13, """
        ....ppP...PPP...
        ...bbbB...BBBB..
        """),
    "legs.w3": part(12, """
        ......PPPpp.....
        ......PPPbbbB...
        .....BBBB.......
        """),
    "legs.hurt": part(14, """
        ...BBBB..bbbB...
        """),
    **_coat(13, """
        ....yytttttT....
        """),
    "vendor.apron": part(12, """
        .........uuU....
        ........uuuU....
        """),
})

# --- troll (20x24): hunched mass, small head thrust forward, horns, long arms --------
# head rows 3-8 (eye 13,6), torso rows 7-16, legs rows 17-21, soles row 22.

# upper arm + forearm poses; every role arm below is one of these plus what it holds
_T_DOWN = """
    ........kxxr........
    ........kxxrr.......
    ........kxxrR.......
    ........kxxrR.......
    .........kxrR.......
    .........kxrR.......
    .........kxrR.......
    .........kxrR.......
    .........kddD.......
    .........kddD.......
    ..........dD........
    """
_T_OPEN = """
    ........kxxr........
    ........kxxrr.......
    ........kxxrR...dD..
    ........kxxrR..rdD..
    ........kxxrrrrR....
    .........kRRRR......
    """
_T_UP = """
    ...............dD...
    ...............dD...
    ........kxxr..rr....
    ........kxxrrrr.....
    ........kxxrR.......
    ........kxxrR.......
    """
_T_HOLD = """
    ........kxxr........
    ........kxxrr.......
    ........kxxrR.......
    ........kxxrR.......
    ........kxxrrrrdD...
    .........kRRRRdD....
    """


def _t(y: int, arm: str, *props: tuple[int, int, str]) -> Part:
    """A troll arm pose (rows from ``y``) with prop pixels (x, y, char) laid over it."""
    g = grid(arm)
    for x, py, ch in props:
        row = g[py - y]
        g = g[:py - y] + (row[:x] + ch + row[x + 1:],) + g[py - y + 1:]
    return Part(g, 0, y)


_T_GEAR = {n: HUMAN[n].at(4, 1) for n in HUMAN.parts if _group(n) == "head" and n != "head"}

TROLL = Rig("troll", (20, 24), eye=(13, 6), mouth=(15, 7), over=("horns",), parts={
    **_T_GEAR,
    "head": part(3, """
        .........qqss.......
        ........qsssss......
        ........sSSSSss.....
        ........sSsssessq...
        ........Ssssssssv...
        .........SSSSSSS....
        """),
    "horns": part(1, """
        ....nn..............
        .....nN.............
        ......nNN...........
        ........N...........
        """),
    "torso": part(7, """
        ...yyyyt............
        ..yyyyyyttt.........
        ..yyyyyytttttt......
        ..yyyyyyttttttt.....
        ..yyyyytttttttT.....
        ..yyyyytttttttT.....
        ...yyyytttttttT.....
        ...yyyyttttttTT.....
        ....yyytttttTT......
        ....TTTTTTTTTT......
        """),
    "legs.stand": part(17, """
        ....PPPPPpppP.......
        ....PPPPP.pppP......
        ....PPPPP.pppP......
        .....PPPP.pppP......
        ....BBBBB.bbbbB.....
        ...BBBBBB.bbbbbB....
        """),
    "legs.w0": part(17, """
        ....PPPPpppP........
        ...PPPP...pppP......
        ..PPPP.....pppP.....
        ..PPP.......ppp.....
        .BBBB.......bbbbB...
        .BBBB.......bbbbbB..
        """),
    "legs.w1": part(16, """
        .....PPPPppp........
        .....PPPPppp........
        .....PPPPppp........
        ....BBBB.ppp........
        .........pppP.......
        .........bbbbB......
        .........bbbbbB.....
        """),
    "legs.w2": part(17, """
        ....ppppPPPP........
        ...pppP...PPPP......
        ..pppP.....PPPP.....
        ..ppp.......PPP.....
        .bbbB.......BBBBB...
        .bbbB.......BBBBBB..
        """),
    "legs.w3": part(16, """
        .....PPPPppp........
        .....PPPPppp........
        .....PPPPppp........
        .....PPPP.bbbbB.....
        .....PPPP...........
        ....BBBBB...........
        ...BBBBBB...........
        """),
    "legs.hurt": part(18, """
        ....PPPPp..pppP.....
        ...PPPP.....pppP....
        ...PPP.......ppp....
        ..BBBB.......bbbB...
        ..BBBBB......bbbbB..
        """),
    "arm.down": part(9, _T_DOWN),
    "arm.back": part(9, """
        ........kxxr........
        ........kxxrr.......
        ........kxxrR.......
        ........kxxrR.......
        .......kxxrR........
        .......kxxrR........
        .......kxrR.........
        .......kxrR.........
        .......kddD.........
        .......kddD.........
        ........dD..........
        """),
    "arm.fwd": part(9, """
        ........kxxr........
        ........kxxrr.......
        ........kxxrR.......
        .........kxxrR......
        .........kxxrR......
        ..........kxrR......
        ..........kxrR......
        ..........kxrR......
        ..........kddD......
        ..........kddD......
        ...........dD.......
        """),
    "far.fwd": part(15, """
        ...............DD...
        """),
    "far.back": part(15, """
        ..DD................
        """),
    "arm.clutch": part(9, """
        ........kxxr........
        ........kxxrr.......
        ........kxxrR.......
        ........kxxrR.......
        ........kxxrrrr.....
        .........kRRddD.....
        ..........kddD......
        """),
    "arm.open": part(9, _T_OPEN),
    "arm.open_up": part(7, _T_UP),
    # the runner
    "hero.scarf": part(8, """
        ......Aaaaai........
        """),
    "hero.tee": part(10, """
        ..............u.....
        ..............u.....
        ..............u.....
        ..............U.....
        """),
    "hero.tail.down": part(9, """
        .a..................
        .A..................
        """),
    "hero.tail.up": part(8, """
        .aa.................
        A...................
        """),
    "hero.tail.mid": part(8, """
        .a..................
        a...................
        A...................
        """),
    # fixer
    **_coat(17, """
        ....yytttttttT......
        ...yyytttttTT.......
        ...yyyttttTT........
        ...yyytttTT.........
        """),
    "fixer.hold": _t(9, _T_HOLD, (15, 12, "g"), (16, 12, "C")),
    "fixer.show": _t(6, "...................." + _T_UP, (15, 6, "g"), (16, 6, "C")),
    "fixer.show2": _t(9, _T_OPEN, (16, 10, "G"), (17, 10, "C")),
    # vendor
    "vendor.apron": part(16, """
        ...........uuU......
        ...........uuuU.....
        ...........uuuU.....
        ...........uuUU.....
        """),
    "vendor.bib": part(8, """
        .............U......
        ..............u.....
        ..............u.....
        ..............u.....
        """),
    "vendor.rest": part(9, _T_HOLD),
    "vendor.reader": _t(6, "...................." + _T_UP, (15, 6, "C"), (16, 6, "g")),
    # doc
    "doc.scrubs": part(9, """
        .............u......
        ..............u.....
        ..............u.....
        ..............U.....
        """),
    "doc.cross": part(10, """
        ..........a.........
        .........aaa........
        ..........a.........
        """),
    "doc.gloves_up": part(7, _T_UP),
    "doc.syringe": _t(9, _T_OPEN, (18, 11, "c"), (19, 11, "g")),
    "doc.syringe2": _t(5, "....................\n...................." + _T_UP,
                       (17, 5, "g"), (16, 6, "c")),
    # ganger
    "ganger.spikes": part(6, """
        ....c.c.............
        ..c.................
        """),
    "ganger.tattoo": part(12, """
        ..........a.........
        ....................
        ....................
        ...........a........
        """),
    "ganger.point": part(9, """
        ........kxxrrrrrrdD.
        ........kxxRRRRRRdD.
        ........kxR.........
        """),
    "ganger.pump": part(4, """
        ...............dD...
        ...............dD...
        ..............rR....
        .............xrR....
        .........kxxxrR.....
        ........kxxrrR......
        ........kxxR........
        """),
    # civilian
    "civilian.pocket": part(9, """
        ........kxxr........
        ........kxxrr.......
        ........kxxrR.......
        ........kxxrR.......
        ........kxxrrr......
        .........kRRUU......
        """),
    "civilian.shrug": part(9, _T_OPEN),
    # collector
    "collector.shirt": part(9, """
        .............uu.....
        ..............A.....
        ..............A.....
        ..............A.....
        """),
    "collector.baton": _t(9, _T_DOWN + "....................\n....................\n",
                          (13, 18, "c"), (14, 19, "c"), (15, 20, "c"), (16, 21, "g")),
    "collector.raise": _t(3, "\n".join(["." * 20] * 4) + _T_UP,
                          (18, 3, "g"), (17, 4, "c"), (16, 5, "c"), (15, 6, "c")),
    "collector.tap": _t(9, _T_OPEN, (18, 12, "c"), (19, 13, "g")),
})

RIGS = {"human": HUMAN, "elf": ELF, "dwarf": DWARF, "ork": ORK, "troll": TROLL}


@dataclass(frozen=True)
class Cast:
    """Who plays a role in one metatype: skin tone, hair colour, optional
    hairstyle override and outfit tweaks (slot -> colour)."""

    skin: str
    hair: str
    style: str | None = None
    outfit: dict[str, str] = field(default_factory=dict)


_HOODIE = {  # muted per-metatype hoodie colours keep a street of civilians from cloning
    "elf": {"y": "denim3", "t": "denim2", "T": "denim1", "x": "denim3", "r": "denim2", "R": "denim1",
            "o": "bone2", "p": "bone1", "P": "bone0"},
    "dwarf": {"y": "bone3", "t": "bone2", "T": "bone1", "x": "bone3", "r": "bone2", "R": "bone1"},
    "ork": {"y": "rust3", "t": "rust2", "T": "rust1", "x": "rust3", "r": "rust2", "R": "rust1"},
    "troll": {"y": "steel4", "t": "steel3", "T": "steel2", "x": "steel4", "r": "steel3", "R": "steel2"},
}

CAST = {
    ("hero", "human"): Cast("fair", "brown"),
    ("hero", "elf"): Cast("rose", "blond"),
    ("hero", "dwarf"): Cast("tan", "brown"),
    ("hero", "ork"): Cast("ork", "black"),
    ("hero", "troll"): Cast("troll", "brown"),
    ("fixer", "human"): Cast("brown", "black"),
    ("fixer", "elf"): Cast("pale", "black"),
    ("fixer", "dwarf"): Cast("fair", "black"),
    ("fixer", "ork"): Cast("ork_dark", "black"),
    ("fixer", "troll"): Cast("troll_dark", "black"),
    ("vendor", "human"): Cast("tan", "red"),
    ("vendor", "elf"): Cast("rose", "copper"),
    ("vendor", "dwarf"): Cast("tan", "brown"),
    ("vendor", "ork"): Cast("ork", "copper"),
    ("vendor", "troll"): Cast("troll", "grey"),
    ("doc", "human"): Cast("fair", "brown"),
    ("doc", "elf"): Cast("pale", "blue"),
    ("doc", "dwarf"): Cast("fair", "red"),
    ("doc", "ork"): Cast("ork_dark", "white"),
    ("doc", "troll"): Cast("troll", "black"),
    ("ganger", "human"): Cast("fair", "mohawk"),
    ("ganger", "elf"): Cast("rose", "mohawk"),
    ("ganger", "dwarf"): Cast("brown", "mohawk"),
    ("ganger", "ork"): Cast("ork", "mohawk"),
    ("ganger", "troll"): Cast("troll_dark", "mohawk"),
    ("civilian", "human"): Cast("tan", "black"),
    ("civilian", "elf"): Cast("pale", "copper", outfit=_HOODIE["elf"]),
    ("civilian", "dwarf"): Cast("fair", "blond", outfit=_HOODIE["dwarf"]),
    ("civilian", "ork"): Cast("ork_dark", "brown", outfit=_HOODIE["ork"]),
    ("civilian", "troll"): Cast("troll", "grey", outfit=_HOODIE["troll"]),
    ("collector", "human"): Cast("fair", "black"),
    ("collector", "elf"): Cast("pale", "white"),
    ("collector", "dwarf"): Cast("tan", "black"),
    ("collector", "ork"): Cast("ork", "black"),
    ("collector", "troll"): Cast("troll_dark", "black"),
}


def _look(look: Look, cast: Cast) -> Look:
    return look if cast.style is None else Look(cast.style, look.skirt, look.wear, look.gear)


def _register_all() -> None:
    for race, rig in RIGS.items():
        cast = CAST[("hero", race)]
        hero = hero_frames(rig, _look(HERO_LOOK, cast))
        plain = legend({**HERO_OUTFIT, **cast.outfit}, cast.skin, cast.hair)
        aug = {**plain, **AUG}
        note = f"the runner ({race}): yellow jacket, the orange Tau-7 scarf"
        register(f"cp.hero.{race}.idle", art(*hero["idle"], legend=plain, fps=4, note=note))
        register(f"cp.hero.{race}.walk", art(*hero["walk"], legend=plain, fps=8, note=note))
        register(f"cp.hero.{race}.hurt", art(*hero["hurt"], legend=plain, note=note))
        note = f"the runner ({race}) with cyberware: chrome arm, glowing eye"
        register(f"cp.hero.{race}.aug.idle", art(*hero["idle"], legend=aug, fps=4, note=note))
        register(f"cp.hero.{race}.aug.walk", art(*hero["walk"], legend=aug, fps=8, note=note))
        for role_name, role in ROLES.items():
            cast = CAST[(role_name, race)]
            outfit = dict(OUTFITS[role_name])
            if role_name == "ganger":  # bare tattooed arms
                q, s, S = SKIN[cast.skin]
                outfit.update(x=q, r=s, R=S)
            outfit.update(cast.outfit)
            lg = legend(outfit, cast.skin, cast.hair, role.hands)
            idle, talk = npc_frames(rig, role, _look(role.look, cast))
            note = f"{role_name} ({race})"
            register(f"cp.npc.{role_name}.{race}.idle", art(*idle, legend=lg, fps=4, note=note))
            register(f"cp.npc.{role_name}.{race}.talk", art(*talk, legend=lg, fps=4, note=note))


_register_all()
