"""Items: everything the survivor or the runner can pick up, carry, eat or implant.

Each item is one 16x16 sprite that does double duty: dropped on the map it lies
on the tile (content sits low, ~12x12, 1px ``ink`` outline) and in the HUD it is
the inventory icon. Light comes from the top-left, 3-4 tones per material.
Only parts that really emit light use EMISSIVE palette colours (the artifact,
precursor traces, the power cell, flare and plasma, screens and LEDs), so at
night on the map exactly those pixels glow."""

from __future__ import annotations

from ..pixelart import Grid, art, blank, grid, overlay, pad, recolor
from ..registry import register


def _t7(key: str, *frames, legend: dict, fps: float = 0.0, outline: str | None = None, note: str = ""):
    register(f"t7.item.{key}", art(*frames, legend=legend, fps=fps, outline=outline, note=note))


def _cp(key: str, *frames, legend: dict, fps: float = 0.0, outline: str | None = None, note: str = ""):
    register(f"cp.item.{key}", art(*frames, legend=legend, fps=fps, outline=outline, note=note))


def _layer(base: str | Grid, *tops: str | Grid) -> Grid:
    """Paint each top grid over the base (all 16x16)."""
    g = grid(base) if isinstance(base, str) else base
    for t in tops:
        g = overlay(g, grid(t) if isinstance(t, str) else t)
    return g


def _top(rows: str) -> Grid:
    """A partial grid for the top rows of a 16x16 frame (sparks, steam, jets)."""
    g = grid(rows)
    return pad(g, bottom=16 - len(g))


_POOL = "ABCDEFGHIJLMNOPQRSTUVWXYZabcdefghijlmnopqrstuvxyz0123456789!#$%&*+-=?@^~<>/|;:,_"


def _recolored_frames(frames, per_frame: list[dict], legend: dict):
    """Same pixels, different colours per frame: ``per_frame[i]`` maps chars of frame i
    to palette names (a pulse, a blinking LED). Returns (frames, merged legend)."""
    gs = [grid(f) if isinstance(f, str) else f for f in frames]
    if len(gs) == 1:
        gs = gs * len(per_frame)
    used = {ch for g in gs for row in g for ch in row} | set(legend) | {".", "k", "K", "w"}
    pool = iter(c for c in _POOL if c not in used)
    merged = dict(legend)
    out = []
    for g, colours in zip(gs, per_frame):
        remap = {}
        for ch, name in colours.items():
            remap[ch] = next(pool)
            merged[remap[ch]] = name
        out.append(tuple("".join(remap.get(ch, ch) for ch in row) for row in g))
    return out, merged


# =====================================================================================
# Tau-7
# =====================================================================================

# --- fiber: a sheaf of violet xeno-flora fibres, tied with twine, ends splayed -----------------
FIBER = """
    ................
    ................
    ..........5...4.
    ..........5..4..
    ..........5.4...
    .........534....
    .......b5342133.
    ......bbB421....
    ......bBBc1.....
    .....53Bccc.....
    ....5342cc......
    .5553421........
    ....421.........
    ...4.3..........
    ..4..3..........
    ................
"""
_t7("fiber", FIBER, outline="ink", note="violet xeno-flora fibre bundle",
    legend={"5": "flora5", "4": "flora4", "3": "flora3", "2": "flora2", "1": "flora1",
            "b": "tent3", "B": "tent2", "c": "tent1"})

# --- ore: faceted grey-violet rock split by a bright orange ore vein ------------------------------
ORE = """
    ................
    ................
    ................
    ................
    ................
    .......kkk......
    .....kk554kk....
    ....k5555433k...
    ...k45555433ok..
    ..k4455443oOP2k.
    .k444443oOP322k.
    .k34433oOPoP21k.
    .k333oOP322oP1k.
    ..k2oOP222111k..
    ...kkkkkkkkkk...
    ................
"""
_t7("ore", ORE, note="ore rock chunk with an orange vein",
    legend={"5": "rock5", "4": "rock4", "3": "rock3", "2": "rock2", "1": "rock1",
            "o": "ore2", "O": "ore1", "P": "ore0"})

# --- spores: three glowing spore capsules --------------------------------------------------------
POD = """
    ..kkk..
    .k454k.
    k45g43k
    k4gg32k
    k43g32k
    k33322k
    .k221k.
    ..kkk..
"""


def _spores() -> Grid:
    pod = grid(POD)
    g = overlay(blank(16, 16), pod, 1, 6)
    g = overlay(g, pod, 8, 5)
    g = overlay(g, pod, 4, 8)
    return _layer(g, _top("""
        ................
        ................
        ......m.........
        ................
        .m...........m..
    """))


_t7("spores", _spores(), note="glowing pink spore capsules (food)",
    legend={"5": "spore5", "4": "spore4", "3": "spore3", "2": "spore2", "1": "spore1",
            "g": "glowpink", "m": "glowpink"})

# --- raw / cooked xeno-meat: the same slab, raw violet-red or seared brown ----------------------------
MEAT = """
    ................
    ................
    ................
    ................
    ................
    ................
    .....kkkkkk.....
    ...kkffffffkk...
    ..kffvMMMmmffk..
    .kfvMmmmmmmmmfk.
    .kfMmFFmmmmmmdk.
    .kfmmmmFFmbbbdk.
    .kfmmmmmmbbobdk.
    .kddmmmmmdbbbDk.
    ..kDDDDDDDDDDk..
    ...kkkkkkkkkk...
"""
RAW = {"f": "elf3", "F": "elf2", "M": "red3", "m": "red2", "d": "spore1", "D": "spore0",
       "v": "lira4", "b": "bone4", "o": "bone1"}
_t7("raw_meat", MEAT, legend=RAW, note="raw violet-red xeno-meat slab")

GRILL = """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .....g...g......
    ....g...g...g...
    ...g...g...g....
    ..g...g...g.....
    ......g.........
    ................
    ................
    ................
"""


def _steam(frames: int = 4) -> list[Grid]:
    """Two thin wisps rising off the food, one S-curve step per frame (loops)."""
    wiggle = (0, 1, 1, 0)
    out = []
    for t in range(frames):
        rows = [["."] * 16 for _ in range(6)]
        for x0, top, bottom in ((5, 1, 5), (9, 0, 4)):
            for y in range(top, bottom + 1):
                rows[y][x0 + wiggle[(y + t) % 4]] = "s" if y > (top + bottom) // 2 else "S"
        out.append(pad(tuple("".join(r) for r in rows), bottom=10))
    return out


COOKED = {"f": "tent4", "F": "tent3", "M": "brute4", "m": "brute3", "d": "brute2", "D": "brute1",
          "v": "tent4", "b": "bone4", "o": "bone1", "g": "brute1", "s": "white:130", "S": "white:60"}
_t7("cooked_meat", *(_layer(MEAT, GRILL, st) for st in _steam()), legend=COOKED, fps=5,
    note="seared xeno-meat, steaming")

# --- ration: olive ration pouch with a crimped foil seal ---------------------------------------------
RATION = """
    ................
    ................
    ................
    ...k.k.k.k.k.k..
    ..kxkxkxkckxkck.
    ..kxcxcxcCcCcCk.
    ..kkkkkkkkkkkkk.
    ..k33333333322k.
    ..k3llllllll21k.
    ..k3lLLLLtLl21k.
    ..k3lllLLLll21k.
    ..k3llllllll21k.
    ..k22222222111k.
    ...k111111100k..
    ....kkkkkkkkk...
    ................
"""
_t7("ration", RATION, note="olive ration pouch with a foil seal",
    legend={"x": "chrome3", "c": "chrome2", "C": "chrome1", "3": "olive3", "2": "olive2",
            "1": "olive1", "0": "olive0", "l": "sand4", "L": "sand1", "t": "podorange"})

# --- medkit: white case, red cross, carry handle ------------------------------------------------------
MEDKIT = """
    ................
    ................
    .....kkkkkk.....
    ....khhhhhHk....
    ....khkkkkHk....
    ..kkkHkkkkHkkk..
    ..kWWWWWWWWWWk..
    ..kW444rr4443k..
    ..k4444rR4433k..
    ..k44rrrRRR33k..
    ..k44RRRRRR32k..
    ..k4433RR3322k..
    ..k3333RR3222k..
    ..k2222222221k..
    ..kkkkkkkkkkkk..
    ................
"""
_t7("medkit", MEDKIT, note="medkit, +35 hp",
    legend={"W": "white", "4": "stat3", "3": "stat2", "2": "stat1", "1": "stat0",
            "r": "red3", "R": "red2", "h": "grey3", "H": "grey2"})

# --- flare: red flare stick, burning and spitting sparks -------------------------------------------------
FLARE = """
    ................
    ................
    ................
    ................
    ................
    ..........kk....
    .........kffk...
    ........kRrdk...
    .......kRrdk....
    ......kRrdk.....
    .....kyyYk......
    ....kRrdk.......
    ...kRrdk........
    ..khgGk.........
    ..kkkk..........
    ................
"""
SPARKS = (
    """
    ................
    ............f...
    ..............e.
    ...........FE...
    ..........eFf.F.
    """,
    """
    ..............E.
    ..........e.....
    ............f...
    ..........fFE.e.
    ...........Ff...
    """,
    """
    ................
    ...........e..f.
    .........E......
    ...........FfE..
    ..........fF..e.
    """,
)
_t7("flare", *(_layer(FLARE, _top(sp)) for sp in SPARKS), fps=8, note="red flare stick, burning",
    legend={"R": "red3", "r": "red2", "d": "red1", "y": "hazard", "Y": "hazard_dark",
            "h": "grey3", "g": "grey2", "G": "grey1", "f": "fire5", "F": "fire4", "E": "fire3",
            "e": "fire3:150"})

# --- headlamp: orange head strap with a round lamp at the front ---------------------------------------------
STRAP = """
    ................
    ................
    ................
    ................
    ...kkkkkkkkkk...
    ..kOOOObbOOOOk..
    .koOkkkkkkkkOOk.
    .kok........kOk.
    .kok........kOk.
    .kok........kOk.
    ..kok......kOk..
    ...kok....kOk...
    ....kk....kk....
    ................
    ................
    ................
"""
LAMP = """
    ..kkkk..
    .kHHssk.
    kHcLLcSk
    kHLllLSk
    ksLllLSk
    kscLLcSk
    .kSSSSk.
    ..kkkk..
"""
_t7("headlamp", overlay(grid(STRAP), grid(LAMP), 4, 7), note="head-band lamp, permanent light",
    legend={"o": "suit3", "O": "suit2", "b": "grey3", "H": "grey3", "s": "grey2", "S": "grey1",
            "c": "chrome2", "l": "fire5", "L": "fire4"})

# --- blade: scrap-metal blade (serrated spine, rust) with a fibre-wrapped grip ---------------------------------
BLADE = """
    ................
    ................
    .............k..
    ............kwk.
    ...........kwCk.
    ..........kwcSk.
    .........kwcCk..
    ........kwcrSk..
    .......kwcCkk...
    ......kwcCSk....
    .....kgGGkk.....
    ....k354k.......
    ...k532k........
    ..k354k.........
    .kpPPk..........
    ..kkk...........
"""
_t7("blade", BLADE, note="scrap blade, fibre-wrapped grip (attack 5)",
    legend={"w": "chrome3", "c": "chrome2", "C": "chrome1", "S": "steel2", "r": "rust3",
            "g": "steel4", "G": "steel2", "5": "flora4", "4": "flora3", "3": "flora2",
            "2": "flora1", "p": "steel4", "P": "steel2"})

# --- plasma cutter: industrial cutting torch with a cyan plasma jet ------------------------------------------------
CUTTER = """
    ................
    ................
    ................
    ................
    ................
    ..kkkkkkk.......
    .kjjjjjjjkkkk...
    .khhhhhhhs555k..
    kkhYhYhhhs4443k.
    kbkGGGGGGs3332k.
    kbkkkgGkkkkkkk..
    .kbkkgGk........
    ..kkgGk.........
    ...kkkk.........
    ................
    ................
"""
JETS = (
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..............q.
    ..............pq
    ..............Pp
    ..............q.
    """,
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..............Pq
    ..............pP
    ..............q.
    """,
)
_t7("plasma_cutter", *(_layer(CUTTER, _top(j)) for j in JETS), fps=8, note="plasma cutter (attack 7)",
    legend={"j": "jacket3", "h": "hazard", "Y": "hazard_dark", "G": "gold1", "b": "grey2",
            "s": "steel3", "5": "steel5", "4": "steel4", "3": "steel3", "2": "steel2",
            "g": "grey2", "p": "glowcyan", "P": "cryst2", "q": "glowcyan:110"})

# --- artifact: precursor relic, a glowing orb held in a claw cradle (pulses) -----------------------------------
ORB = """
    ...kkkk...
    ..k3332k..
    .k344432k.
    k34555432k
    k34554321k
    k34443321k
    k23332211k
    .k222211k.
    ..k1111k..
    ...kkkk...
"""
CRADLE = """
    ................
    ....h......h....
    ...h........h...
    ..k..........k..
    .kck........kCk.
    .kck........kCk.
    .kck........kCk.
    ..kck......kCk..
    ...kck....kCk...
    ...kkckkkkCkk...
    ....kHrrrrHk....
    ...kHhhhhhhHk...
    ...kkkkkkkkkk...
    ................
    ................
    ................
"""
SPARKLE = """
    ............x...
    ...........xxx..
    ............x...
"""


def _artifact():
    body = _layer(overlay(blank(16, 16), grid(ORB), 3, 1), CRADLE)
    lit = _layer(body, _top(SPARKLE))
    dim = {"1": "hive2", "2": "hive3", "3": "cryst0", "4": "cryst1", "5": "hivegl",
           "h": "hivegl:0", "r": "hive3"}
    mid = {"1": "hive3", "2": "cryst0", "3": "cryst1", "4": "hivegl", "5": "cryst2",
           "h": "hivegl:50", "r": "cryst0"}
    hot = {"1": "cryst0", "2": "cryst1", "3": "hivegl", "4": "cryst2", "5": "cryst2",
           "h": "hivegl:90", "r": "hivegl"}
    peak = {**hot, "x": "cryst2"}
    frames, legend = _recolored_frames([body, body, body, lit, body, body],
                                       [dim, mid, hot, peak, hot, mid],
                                       {"c": "hive3", "C": "hive2", "H": "hive1", "x": "cryst2"})
    return frames, legend


_frames, _legend = _artifact()
_t7("artifact", *_frames, legend=_legend, fps=5, note="precursor artifact: pulsing glowing relic")

# --- alloy: salvaged hull plate: rivets, a torn corner, a hazard-striped edge -------------------------------------
ALLOY = """
    ................
    ................
    ................
    ................
    ................
    ...kkkkkkkk.....
    ..k55555555k....
    ..k5o44444o4k...
    ..k5444444433k..
    ..kyy44444333k..
    ..kyYY4o44o33k..
    ..kYyyY333322k..
    ..kyYYyy22221k..
    ..kYyyYY11111k..
    ..kkkkkkkkkkkk..
    ................
"""
_t7("alloy", ALLOY, note="hull alloy plate (beacon part)",
    legend={"5": "steel5", "4": "steel4", "3": "steel3", "2": "steel2", "1": "steel1",
            "o": "steel2", "y": "hazard", "Y": "ink2"})

# --- circuit: precursor circuit board; pulses run out of the core along the traces ---------------------------------
CIRCUIT = """
    ................
    ................
    ................
    ................
    ...kkkkkkkkkk...
    ..k4444444443k..
    ..k3d222abcd2k..
    ..k3c2kkkk222k..
    ..k3bakeek222k..
    ..k322keekab2k..
    ..k3p2kkkk2c2k..
    ..k3222a222d2k..
    ..k1g1gag1g1gk..
    ...kkkkkkkkkk...
    ................
    ................
"""


def _circuit():
    base = {"a": "hivegl", "b": "hivegl", "c": "hivegl", "d": "hivegl"}
    frames = []
    for t in range(4):
        f = dict(base)
        f["abcd"[t]] = "cryst2"
        f["e"] = "cryst2" if t == 0 else "hivegl"
        frames.append(f)
    return _recolored_frames([CIRCUIT], frames, {"4": "hive4", "3": "hive3", "2": "hive2", "1": "hive1",
                                                 "g": "gold2", "p": "gold2"})


_frames, _legend = _circuit()
_t7("circuit", *_frames, legend=_legend, fps=6, note="precursor circuit board (beacon part)")

# --- power cell: glowing battery cell, a charge band climbing through it ----------------------------------------------
CELL = """
    ................
    ................
    ......kkkk......
    ......k54k......
    ....kkk32kkk....
    ...k55444432k...
    ...k33222211k...
    ...kk5ffff1kk...
    ....k4eeee1k....
    ....k4dddd1k....
    ....k4cccc1k....
    ....k4bbbb1k....
    ...kk5aaaa1kk...
    ...k55444432k...
    ...kkkkkkkkkk...
    ................
"""


def _cell():
    frames = []
    for t in range(4):
        f = {c: "glowlime" for c in "abcdef"}
        for c in ("ab", "cd", "ef", "")[t]:
            f[c] = "cryst2"
        frames.append(f)
    return _recolored_frames([CELL], frames, {"5": "chrome3", "4": "chrome2", "3": "chrome1",
                                              "2": "chrome0", "1": "steel1"})


_frames, _legend = _cell()
_t7("power_cell", *_frames, legend=_legend, fps=4, note="energy cell (+power for the pod)")


# =====================================================================================
# The city
# =====================================================================================

CREDSTICK = """
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ..........kgGGk.
    .........k3gGk..
    ........k32kk...
    .......k3nk2k...
    ......k3nk2k....
    .....k3nk2k.....
    ....k32k2k......
    ...kgG22k.......
    ...kGGkk........
    ...kkk..........
"""
_cp("credstick", CREDSTICK, note="certified credstick",
    legend={"g": "gold2", "G": "gold1", "3": "chrome2", "2": "chrome1", "n": "neon_green"})

NOODLES = """
    ................
    ..........k.k...
    .........kbkbk..
    ........kbkbk...
    ...kkkkkbkbkkk..
    ..knnnnbkbnnnnk.
    ..knNnNnNnNnNnk.
    ..kkkkkkkkkkkkk.
    ...kwwwwwwwwwk..
    ...krrrrrrrrRk..
    ...kwwppwwwwsk..
    ....kwppwwwsk...
    ....kwwwwwwsk...
    ....kssssssk....
    .....kkkkkk.....
    ................
"""
_cp("synth_noodles", NOODLES, note="synthetic noodle cup",
    legend={"b": "bone3", "n": "jacket3", "N": "jacket2", "w": "white", "s": "grey3",
            "r": "red2", "R": "red1", "p": "spore3"})

STIM = """
    ................
    ................
    ................
    ................
    ................
    ...kkkkkkkkkk...
    ..kbbbbbbbbbbk..
    ..kbkkkkkkkkbk..
    ..kbkgGwGggkbk..
    ..kbkGwwwGgkbk..
    ..kbkgGwGggkbk..
    ..kbkkkkkkkkBk..
    ..kbbbbbbbbBBk..
    ...kkkkkkkkkk...
    ................
    ................
"""
_cp("stim_patch", STIM, note="stim patch, +30 hp",
    legend={"b": "bone4", "B": "bone2", "g": "neon_green_dim", "G": "moss4"})

BURNER = """
    ................
    ................
    ..........k.....
    ..........kk....
    .....kkkkkkk....
    ....k3333332k...
    ....k3kkkkk2k...
    ....k3knnnk2k...
    ....k3kNnNk2k...
    ....k3kkkkk2k...
    ....k3o3o3o2k...
    ....k3o3o3o2k...
    ....k2222221k...
    .....kkkkkkk....
    ................
    ................
"""
_cp("burner_deck", BURNER, note="anonymous burner commlink",
    legend={"3": "conc3", "2": "conc2", "1": "conc1", "o": "conc4", "n": "neon_green",
            "N": "neon_green_dim"})

PISTOL = """
    ................
    ................
    ................
    ................
    ...k.......k....
    ..kkkkkkkkkkkkk.
    ..k33333333333k.
    ..k22k2222222kk.
    ..k111111111k.k.
    ...kkkgGk1kkk...
    ....kgGGkkk.....
    ...kgGGk........
    ...kgGk.........
    ..kgGGk.........
    ..kkkkk.........
    ................
"""
_cp("pistol", PISTOL, note="heavy pistol",
    legend={"3": "chrome2", "2": "chrome1", "1": "chrome0", "g": "leather3", "G": "leather2"})

JACKET = """
    ................
    ................
    ................
    ....kkk..kkk....
    ...kjjjkkjjjk...
    ..kjJjjkkjjJjk..
    ..kjjpppppjjjk..
    ..kjkpPPPPpkjk..
    ..kjkppppppkjk..
    ..kjkpPPPPpkjk..
    ..kJkppppppkJk..
    ..kkkpppppPkkk..
    ....kJJJJJJk....
    ....kkkkkkkk....
    ................
    ................
"""
_cp("armor_jacket", JACKET, note="armor jacket",
    legend={"j": "rust3", "J": "rust2", "p": "steel3", "P": "steel2"})

TRINKET = """
    ................
    ................
    ................
    .........kk.....
    ...kk...kwwk....
    ..kpwkkkkwwk....
    ..kwwwwwwwwk....
    ..kwkwwwkwwk....
    ..kwwwnwwwwk....
    ...krrrgrrk.....
    ...kwwwwwwk.....
    ...kwwwwwwk.....
    ..kgggggggGk....
    ..kkkkkkkkkk....
    ................
    ................
"""
_cp("trinket", TRINKET, note="lucky-cat souvenir (junk)",
    legend={"p": "spore4", "n": "spore3", "r": "red2", "g": "gold2", "G": "gold1"})

DATACHIP = """
    ................
    ................
    ................
    ................
    ....kkkkkkk.....
    ....kgkgkgkk....
    ....k1111111k...
    ....k1cc1111k...
    ....k1c1c111k...
    ....k1cc1111k...
    ....k111111lk...
    ....k1111111k...
    ....kkkkkkkkk...
    ................
    ................
    ................
"""
_cp("corp_data_chip", DATACHIP, DATACHIP.replace("l", "1"), fps=2, note="hot corporate data chip",
    legend={"g": "gold2", "1": "asph2", "c": "neon_cyan", "l": "neon_red"})

CYBER_EYE = """
    ................
    ................
    ................
    ................
    .....kkkkk......
    ....k32221k.....
    ...k3kkkk21k....
    ...k2kcCkk1k....
    ...k2kCwCk1k....
    ...k2kkCkk1k....
    ...k1kkkk10k.kk.
    ....k10000kkrk..
    .....kkkkk.kk...
    ................
    ................
    ................
"""
EYE = {"3": "chrome3", "2": "chrome2", "1": "chrome1", "0": "chrome0", "c": "neon_cyan",
       "C": "neon_cyan_dim", "r": "neon_red"}
_cp("cyber_eye", CYBER_EYE, legend=EYE, note="cybereye")

CYBER_ARM = """
    ................
    ................
    ................
    .........kkk....
    ........k322k...
    ........k2c1k...
    ........k221k...
    .........k2k....
    .........k2k....
    ..kkkkkkkkck....
    .k32222222c1k...
    .k2cc111111k....
    ..kkkkkkkkk.....
    ................
    ................
    ................
"""
ARM = {"3": "chrome3", "2": "chrome2", "1": "chrome1", "0": "chrome0", "c": "neon_cyan"}
_cp("cyber_arm", CYBER_ARM, legend=ARM, note="cyberarm")

DERMAL = """
    ................
    ................
    ................
    ................
    .....kkkkkk.....
    ...kk332221kk...
    ..k3322k22211k..
    ..k322k2k2111k..
    ..k22k222k110k..
    ..k2k22222k10k..
    ..k22k222k110k..
    ...k22k2k110k...
    ....kk1k10kk....
    ......kkkk......
    ................
    ................
"""
DERM = {"3": "chrome3", "2": "chrome2", "1": "chrome1", "0": "chrome0"}
_cp("dermal_plating", DERMAL, legend=DERM, note="subdermal armor plating")


# --- alphaware: the same parts in a gold/chrome premium finish, with a sparkle ------------------------
GOLD = {"chrome3": "gold3", "chrome2": "gold2", "chrome1": "gold1", "chrome0": "gold0"}


def _alpha(key: str, base: str, legend: dict, note: str) -> None:
    g = grid(base)
    gold = recolor(art(g, g, legend=legend), GOLD)
    register(f"cp.item.{key}_alpha", art(*gold.frames, legend=dict(gold.legend), fps=3, note=note))


_alpha("cyber_eye", CYBER_EYE, EYE, "alphaware cybereye")
_alpha("cyber_arm", CYBER_ARM, ARM, "alphaware cyberarm")
_alpha("dermal_plating", DERMAL, DERM, "alphaware subdermal plating")
