"""Tau-7 life: the survivor, Lira and the fauna/machines of the planet.

Every actor faces RIGHT in a 3/4 side view (the renderer mirrors it for left)
and stands with its feet on the bottom row, so the default bottom-centre
anchor puts it on the tile's ground point."""

from __future__ import annotations

from ..pixelart import Grid, art, blank, grid, outline_grid, overlay, shift
from ..procgen import Canvas
from ..registry import register


def _frame(body: str, *stamps: tuple[Grid, int, int]) -> Grid:
    """A body grid with parts (heads) stamped *under* it: the body's own pixels
    win, so an arm raised in front of the face is drawn over the head."""
    g = grid(body)
    w, h = len(g[0]), len(g)
    base = blank(w, h)
    for part, x, y in stamps:
        base = overlay(base, part, x, y)
    return overlay(base, g)


# --- the survivor ------------------------------------------------------------------
# orange survival suit, white helmet with a cyan visor, grey life-support pack

HERO = {
    "h": "grey4", "H": "grey3", "j": "white",       # helmet
    "v": "glowcyan", "V": "water3", "c": "cryst2",  # visor
    "s": "suit2", "S": "suit1", "l": "suit3",        # suit
    "b": "grey2", "B": "grey1",                      # backpack
    "g": "steel4", "G": "steel3",                    # gloves, boots
    "y": "hazard", "t": "steel3", "T": "steel2",     # multi-tool
    "u": "water4",                                   # a drop of water
    "r": "water1", "R": "water2", "x": "white",      # dead, cracked visor
    "q": "grey3", "Q": "grey2", "W": "water2",       # portrait: collar, visor depth
}

HELMET = grid("""
    ..kkkkk..
    .kjhhhhk.
    kjhhhhcvk
    khhhhvvvk
    kHhhhvVVk
    kkHHHHHkk
""")


def _hero(body: str, hx: int = 3, hy: int = 1) -> Grid:
    return _frame(body, (HELMET, hx, hy))


HERO_IDLE = [
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kSSkSkk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """),
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSslk...
        ...kkkSSSSkgk...
        .....kSSkSkk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """, hy=2),
]

HERO_WALK = [
    # contact: near leg forward, near arm swung back (tucked against the hip)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSlk....
        ..kbbksssSsk....
        ..kBBkSssSgk....
        ...kkkSSSkgk....
        ....kSSkksSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: body up 1px, near leg planted, far leg swinging through (knee forward)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kssSSkk....
        .....kssSSSk....
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
    # contact: far leg forward, near arm swung forward
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllssslk...
        ..kbbklsssSllk..
        ..kbbksssSSslk..
        ..kBBkSssSSkgk..
        ...kkkSSSSkkk...
        ....ksSkkSSk....
        ...kssk..kSSk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: body up 1px, far leg planted, near leg swinging through (knee forward)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kSSsskk....
        .....kSSsssk....
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
]

HERO_WORK = [
    # tool raised: bracing to strike / cut / tighten
    _hero("""
        ................
        .............k..
        ............kTk.
        ............ktk.
        ............kyk.
        ............kgk.
        ...........kslk.
        ..kbbkllssslksk.
        ..kbbklsssSSlk..
        ..kbbksssSSSk...
        ..kBBkSssSSk....
        ...kkkSSSSk.....
        ....kSSkkSSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # the stroke: tool driven down in front, body dips 1px
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSsllk..
        ...kkkSSSSkkgyk.
        ....kSSkkSSkkkTt
        ...kSSk..kssk.kk
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hy=2),
]

HERO_DRINK = [
    # down on one knee at the water's edge, scooping with the glove
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .kbbkllsssk.....
        .kbbklssSllk....
        .kBBksssSsslk...
        ..kkkSSSSkkslk..
        .kGSSSSkkssk.gk.
        .kkkkkkkkGgk.kk.
    """, hx=2, hy=4),
    # sitting up, lifting the water to the visor; a drop falls back
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ...........kgk..
        ..........kslk..
        ..........kslk..
        ..........kslku.
        .kbbkllssslk....
        .kbbklssSSk.....
        .kBBksssSSSk....
        ..kkkSSSSsssk...
        .kGSSSSkkssk....
        .kkkkkkkkGgk....
    """, hx=2, hy=4),
]

HERO_ATTACK = [
    # wind-up: rocked back, arm raised high in front of the helmet
    _hero("""
        ...........kk...
        ..........kggk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..kbbkllsssslk..
        ..kbbklsssSSk...
        ..kbbksssSSSk...
        ..kBBkSssSSk....
        ...kkkSSSSk.....
        ....kSSkkSSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hx=2),
    # strike: lunging forward, arm swung out level
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslkkkk.
        ..kbbklssSlllllg
        ..kbbksssSSSSSSg
        ..kBBkSssSSkkkkk
        ...kkkSSSSk.....
        ...kSSkkkSSk....
        ..kSSk...kssk...
        .kGgk.....kGgk..
        .kkkk.....kkkk..
    """, hx=4),
    # follow-through: arm carried down and forward, weight on the front leg
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSSllk..
        ...kkkSSSSkSlk..
        ...kSSkkkSSkggk.
        ..kSSk...ksskkk.
        .kGgk.....kGgk..
        .kkkk.....kkkk..
    """, hx=4, hy=2),
]

HERO_HURT = [
    # knocked back: helmet thrown back, arm flung up, front foot off the ground
    _hero("""
        ................
        ................
        ................
        ................
        ...........kk...
        ..........kglk..
        ..........kslk..
        .kbbkllssslk....
        .kbbklsssSSk....
        .kbbksssSSSk....
        .kBBkSssSSk.....
        ..kkkSSSSSk.....
        ...kSSkkssk.....
        ..kSSk..kssk....
        .kGgk...kGgk....
        .kkkk...kkkk....
    """, hx=1, hy=2),
]

HERO_SLEEP = [
    # flat on the back, visor to the sky, one knee up; the chest rises and falls
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..kk......kjcvvk
    .kssk..kkkjhvvVk
    .kSsskklllkhhhhk
    .kGkSssssSkhhHHk
    .kGSSSSSSSSkbHkk
    ..kkkkkkkkkkkkk.
    """,
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..kk...kk.kjcvvk
    .kssk.klllkhvvVk
    .kSsskllllkhhhhk
    .kGkSssssSkhhHHk
    .kGSSSSSSSSkbHkk
    ..kkkkkkkkkkkkk.
    """,
]

HERO_DEAD = [
    # sprawled on the back, an arm flung out, the visor cracked and dark
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..k.......kjrxrk
    .kGk...kkkjhxRRk
    .kGSk.kllskhhhhk
    ..kSSSSssSShhHHk
    ..kkkkSSSSkbbbkk
    ......kkkkkkkkk.
    """,
]

HERO_PORTRAIT = """
    ........................
    ..........kkkkk.........
    ........kkjjjhhkk.......
    .......kjjhhhhhhhk......
    ......kjhhhhhhhhhhk.....
    .....kjhhhhhhhhhhhhk....
    ....kjhhhhhhhhhhhhhhk...
    ....kjhhhhhhkkkkkkkkhk..
    ....khhhhhhkccvvvvvvkk..
    ...kjhhhhhkcvcvvvvvvVk..
    ...khhhhhhkvcvvvvvvvVk..
    ...khhhhhhkvvcvvvvvvVk..
    ...kHhhhhhkvvvvvvvvVVk..
    ...kHhhhhhkvvvvvvvVVWk..
    ...kHHhhhhHkVvvvVVVWkk..
    ....kHHhhhhHkkkkkkkkHk..
    ....kkHHHhhhhhhhhhHHk...
    ...kbkkHHHHHHHHHHHkk....
    ..kbbbkkqqqqqqqqqkkk....
    ..kbbbkQQkkkkkkkQQlkk...
    .kbbbbkllllsssssslssk...
    .kbbbbkllsssssyyssssSk..
    .kBbbbksssssssyysssSSk..
    .kBBBBksssssssssssSSSk..
"""

register("t7.hero.idle", art(*HERO_IDLE, legend=HERO, fps=2, note="the survivor, idle"))
register("t7.hero.walk", art(*HERO_WALK, legend=HERO, fps=8, note="the survivor, walking"))
register("t7.hero.work", art(*HERO_WORK, legend=HERO, fps=4, note="gather / craft / build / cook / repair"))
register("t7.hero.drink", art(*HERO_DRINK, legend=HERO, fps=2, note="kneeling at the water, scooping"))
register("t7.hero.attack", art(*HERO_ATTACK, legend=HERO, fps=10, note="overhead strike: raise, swing, follow through"))
register("t7.hero.hurt", art(*HERO_HURT, legend=HERO, note="recoil"))
register("t7.hero.sleep", art(*HERO_SLEEP, legend=HERO, fps=1, note="asleep on the back"))
register("t7.hero.dead", art(*HERO_DEAD, legend=HERO, note="fallen, visor cracked"))
register("t7.hero.portrait", art(HERO_PORTRAIT, legend=HERO, note="HUD portrait"))


# --- Lira ----------------------------------------------------------------------------
# the ship's engineer-cyberneticist: magenta jumpsuit, short copper hair with a
# cowlick, a chrome cybernetic arm with a cyan status light, a brown tool belt

LIRA = {
    "r": "hair_copper", "R": "dust3", "y": "tent3",          # hair
    "f": "skin3", "F": "skin2", "e": "ink2",                 # face
    "l": "lira3", "s": "lira2", "S": "lira1", "d": "lira0",  # jumpsuit
    "m": "chrome2", "M": "chrome1", "n": "chrome0", "W": "chrome3",  # cyber arm
    "c": "glowcyan", "C": "cryst1",                          # arm light (on / dim)
    "t": "tent1", "T": "tent0", "p": "tent2", "z": "gold2",  # tool belt
    "g": "grey3", "G": "grey2",                              # boots
    "v": "flora4", "V": "flora3", "u": "flora2", "U": "flora5", "x": "flora1",  # violet fiber
    "o": "tent2",                                            # sheaf cord
}

LIRA_HEAD = grid("""
    ..kk.....
    .krkkkk..
    .krryyrk.
    krryyrrrk
    kRrrrrffk
    kRrrrfefk
    .kRkkffFk
""")


def _lira(body: str, hx: int = 3, hy: int = 1) -> Grid:
    return _frame(body, (LIRA_HEAD, hx, hy))


LIRA_IDLE = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kSSSkkmmk..
        .....kSk.kSkk...
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """),
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kSssSSkmWk..
        ....ktpTzTkmCk..
        .....kSSSkkMnk..
        .....kSk.kSkmk..
        ....kGgk.kGgkk..
        ....kkkk.kkkk...
    """, hy=2),
]

LIRA_WALK = [
    # contact: near leg forward, chrome arm swung back across the hip
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkWk....
        ....kslssWmk....
        ....kSssmMck....
        ....ktpmMnk.....
        ....kSSmmkSk....
        ...kSSkkkssk....
        ..kGgk...kGgk...
        ..kkkk...kkkk...
    """),
    # passing: up 1px, near leg planted, far leg swinging through
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kssSSkmmk..
        .....kssSSSkk...
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
    # contact: far leg forward, chrome arm swung forward
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWWk.
        ....kSssSSSkmck.
        ....ktpTzTTkMnk.
        ....ksSkkSSkmmk.
        ...kssk..kSSkk..
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: up 1px, far leg planted, near leg swinging through
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kSSsskmmk..
        .....kSSsssk....
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
]

# the fiber sheaf she hauls on her back: stalk tips fan out above her shoulder
SHEAF = grid("""
    .k.k..
    kUkUk.
    kvUvk.
    kvVvVk
    .kVVvk
    .kVVuk
    .kuVuk
    .kuoVk
    .kuuVk
    .kxuuk
    ..kxuk
    ...kk.
""")


def _carry(body: str, bob: int = 0) -> Grid:
    return _frame(body, (SHEAF, 0, 1 + bob), (LIRA_HEAD, 4, 1 + bob))


LIRA_CARRY = [
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkWk...
        .....kslssoWmk..
        .....kSsoSmMck..
        .....ktoTmMnk...
        .....kSSmmkSk...
        ...kSSkkkssk....
        ..kGgk...kGgk...
        ..kkkk...kkkk...
    """),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSkmck.
        .....ktoTzTkMnk.
        .....kssSSSkmmk.
        .....kssSSSkkk..
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, bob=-1),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSSkmck
        .....ktoTzTTkMnk
        ....ksSkkSSkkmmk
        ...kssk..kSSkkk.
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSkmck.
        .....ktoTzTkMnk.
        .....kSSsssSkmmk
        .....kSSsssk.kk.
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, bob=-1),
]

LIRA_WORK = [
    # reaching up into the flora with the chrome hand
    _lira("""
        ................
        ................
        ................
        ................
        ................
        .............kk.
        ............kWmk
        ...........kmMk.
        .....kslkkkmck..
        .....kslssSkk...
        .....kSssSSk....
        .....ktpTzTk....
        .....kSSkSSk....
        ....kSSk.kssk...
        ...kGgk...kGgk..
        ...kkkk...kkkk..
    """, hx=4),
    # leaning back, pulling a violet strand free
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk.k.
        ....kslssSkmWkUk
        ....kSssSSkmcvvk
        ....ktpTzTkMnkk.
        ....kSSSkSSkk...
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hx=3, hy=1),
]

LIRA_WAVE = [
    # both arms up and wide: "over here!"
    _lira("""
        ................
        .kk..........kk.
        kffk........kWmk
        .ksk........kmk.
        ..ksk......kmk..
        ...ksk.....kmk..
        ....ksk...kmMk..
        .....kk...kmck..
        ....kslkkkkkk...
        ....kslssSSk....
        ....kSssSSSk....
        ....ktpTzTTk....
        .....kSSkSSk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """, hy=2),
    # arms swing in over the head, a little hop
    _lira("""
        ....kk....kk....
        ...kffk..kWmk...
        ...kfsk..kmMk...
        ....ksk..kmk....
        ....kkk..kck....
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmk...
        ....kSssSSkkk...
        ....ktpTzTk.....
        .....kSSkSk.....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
        ................
    """, hy=1),
]

LIRA_SLEEP = [
    # curled on her side; she never switches the arm light off (afraid of the dark)
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ....kkkkk.krryk.
    ...kSssslkRrrrrk
    ..kSSsWmmckRrffk
    .kGSSSmMnkRRfeFk
    .kGkSSSSSSkkkkk.
    ..kkkkkkkkk.....
    """,
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ...kkkkkk.krryk.
    ..kSsssslkRrrrrk
    ..kSSsWmmckRrffk
    .kGSSSmMnkRRfeFk
    .kGkSSSSSSkkkkk.
    ..kkkkkkkkk.....
    """,
]

LIRA_DRINK = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kslkkkkkk.....
        ..kSssSSkWmk....
        ..ktpTzkkmMck...
        .kGSSSkkssknmk..
        .kkkkkkkGgk.kk..
    """, hx=2, hy=5),
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..........kWk...
        .........kmMk...
        ..kslkkkkmck.v..
        ..kSssSSkkk.....
        ..ktpTzTSssk....
        .kGSSSkkssk.....
        .kkkkkkkGgk.....
    """, hx=2, hy=5),
]

LIRA_HURT = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ............kk..
        ...........kWmk.
        ...........kmk..
        ....kslkkkkmck..
        ...kslssSSkkk...
        ...kSssSSSk.....
        ...ktpTzTTk.....
        ....kSSkssk.....
        ...kSSk.kssk....
        ..kGgk..kGgk....
        ..kkkk..kkkk....
    """, hx=2, hy=2),
]

LIRA_DEAD = [
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ..kk......krryk.
    .kGk.kkkkkRrrrrk
    .kGSkslsnMkRrfFk
    ..kSSSSSMnmkkkk.
    ..kkkkkkkkkk....
    """,
]

register("t7.lira.idle", art(*LIRA_IDLE, legend=LIRA, fps=2, note="Lira, idle; the arm light pulses"))
register("t7.lira.walk", art(*LIRA_WALK, legend=LIRA, fps=8, note="Lira, walking"))
register("t7.lira.carry", art(*LIRA_CARRY, legend=LIRA, fps=8, note="Lira hauling a sheaf of violet fiber"))
register("t7.lira.work", art(*LIRA_WORK, legend=LIRA, fps=3, note="Lira gathering fiber: reach, pull"))
register("t7.lira.wave", art(*LIRA_WAVE, legend=LIRA, fps=4, note="stranded at her crash site, waving for help"))
register("t7.lira.sleep", art(*LIRA_SLEEP, legend=LIRA, fps=1, note="curled up, arm light left on"))
register("t7.lira.drink", art(*LIRA_DRINK, legend=LIRA, fps=2, note="kneeling at the water"))
register("t7.lira.hurt", art(*LIRA_HURT, legend=LIRA, note="recoil"))
register("t7.lira.dead", art(*LIRA_DEAD, legend=LIRA, note="fallen, arm light dead"))


# --- fauna -----------------------------------------------------------------------------
# hopper: a timid pale grazer. Long antenna-ears with pink bulbs, a big pink eye
# (glowpink: the only pixel that shows at night), strong hind legs.

HOPPER = {
    "a": "bone4", "b": "bone3", "B": "bone2", "d": "bone1",
    "p": "spore3", "P": "spore2", "e": "glowpink", "E": "spore2",
}

HOPPER_IDLE = [
    """
    ................
    ......kk..kk....
    .....kpPk.kpk...
    ......kak.kak...
    ......kak.kbk...
    .......kakbk....
    .......kabbkk...
    ......kaaabbbk..
    .....kkabbbaebk.
    ..kkkaaabbbbbbBk
    .kaakabbkBBBBBk.
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kbbbbbbBkkBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
    # the near ear flicks forward, listening
    """
    ................
    ......kk.....kk.
    .....kpPk...kpPk
    ......kak..kak..
    ......kak.kak...
    .......kakbk....
    .......kabbkk...
    ......kaaabbbk..
    .....kkabbbaebk.
    ..kkkaaabbbbbbBk
    .kaakabbkBBBBBk.
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kbbbbbbBkkBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
]

HOPPER_MOVE = [
    # crouch: coiled low, ears laid back
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..kkkk..........
    .kpPaakkk.......
    ..kkkbaaabkkk...
    ...kkaabbbbaebk.
    .kkabbbbbbbbbbBk
    kaakbbbbbkbbbBk.
    .kabbbbbbBkkBk..
    .kBBBBBBBBBkBBk.
    ..kkkkkkkkkkkkk.
    """,
    # airborne: stretched out, hind legs trailing, ears streaming
    """
    ................
    ................
    ................
    .kk.............
    .kpkkk..........
    ..kPaakkkkk.....
    ...kkkbaaaabkkk.
    ...kkkabbbbbaebk
    .kaakbbbbbbbbbBk
    ..kkbbbbbbbbBBk.
    .kBBBbbbbBBBBk..
    kBBkkkBBBkkBBk..
    kkk...kkk..kk...
    ................
    ................
    ................
    """,
    # landing on the front paws, haunch still up
    """
    ................
    ................
    ................
    ................
    ....kk..........
    ...kpPk.........
    ....kakkk.......
    .....kaaakk.....
    ....kkbbbaabk...
    .kk.kabbbbbabk..
    kaakabbbbbbbbekk
    .kkabbbbbbbbbbBk
    ..kBBbbbbbbBBBk.
    ...kkBBBBkkkBBk.
    .....kkkk...kBk.
    ............kkk.
    """,
]

HOPPER_HURT = [
    # flinching: ears pinned back, eye squeezed shut
    """
    ................
    ................
    ................
    ................
    ....kk..........
    ...kpPk.kk......
    ....kakkpPk.....
    .....kakkak.....
    .....kkabak.....
    .....kaabbbkk...
    ..kkkabbbbbEbk..
    .kaakabbkBBBBk..
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
]

register("t7.hopper.idle", art(*HOPPER_IDLE, legend=HOPPER, fps=1.5, note="hopper, ear twitch"))
register("t7.hopper.move", art(*HOPPER_MOVE, legend=HOPPER, fps=8, note="hopper hop: crouch, airborne, land"))
register("t7.hopper.hurt", art(*HOPPER_HURT, legend=HOPPER, note="hopper flinch"))



def _ol(text: str) -> Grid:
    """Fill-only grid -> grid with the 1px ink outline baked in."""
    return outline_grid(grid(text), "k")


# hound: a lean six-legged pack hunter with a spined ridge, a long jaw and red
# eyeshine (neon_red glows at night: a pack shows up as moving red sparks)

HOUND = {"0": "hound0", "1": "hound1", "2": "hound2", "3": "hound3", "4": "hound4",
         "e": "neon_red", "t": "bone4", "m": "red1"}

HOUND_IDLE = [
    _ol("""
        ................
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        3....3333333....
        .3..22222122333.
        ..222222122223e.
        ...222222222222.
        ...222..222mttt.
        ...21...2221....
        ...2.1..1.2.1...
        ..2..1..1..2.1..
        ................
    """),
    # tail drops, jaw closes: a slow panting loop
    _ol("""
        ................
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        .....3333333....
        33..22222122333.
        ..222222122223e.
        ...222222222222.
        ...222..2222ttt.
        ...21...2221....
        ...2.1..1.2.1...
        ..2..1..1..2.1..
        ................
    """),
]

HOUND_MOVE = [
    # stretched: front legs reaching, hind legs driving back
    _ol("""
        ................
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        33...3333333....
        ..3.22222122333.
        ..222222122223e.
        ...222222222222.
        ...22...222mttt.
        ..21.....2221...
        .2.1.....1..22..
        2...1...1.....2.
        ................
    """),
    # gathered: legs bunched under the body, body up 1px
    _ol("""
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        3....3333333....
        .3..22222122333.
        ..222222122223e.
        ...222222222222.
        ...222..2222ttt.
        ....21..1221....
        ....2.1.1.21....
        .....21..1.2....
        .....2.1..12....
        ................
    """),
    # stretched, the other legs leading
    _ol("""
        ................
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        .3...3333333....
        3.3.22222122333.
        ..222222122223e.
        ...222222222222.
        ...22...222mttt.
        ..12....12221...
        .1.2...1....21..
        1...2.1......12.
        ................
    """),
    # gathered, the other legs leading
    _ol("""
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        .3...3333333....
        3.3.22222122333.
        ..222222122223e.
        ...222222222222.
        ...222..2222ttt.
        ....12..2112....
        ....1.2.2.12....
        .....12..2.1....
        .....1.2..21....
        ................
    """),
]

HOUND_ATTACK = [
    # coiled: low on bent legs, head drawn back
    _ol("""
        ................
        ................
        ................
        ................
        ................
        ................
        ......4.4.......
        .....43434......
        3...3333333.....
        .3.22222122333..
        ..22222122223e..
        ..222222222222..
        ..222.22222ttt..
        .21...22221.....
        .2.1..1.2.1.....
        ................
    """),
    # lunge: body flung forward, jaws wide open
    _ol("""
        ................
        ................
        ................
        ................
        ................
        .......4.4......
        ......43434.....
        33...33333333...
        ..3.22222122e3..
        ...2222212222t..
        ...22222222.....
        ...22...2222mt..
        ..21.....2221t..
        .2.1.....1..22..
        2...1...1.....2.
        ................
    """),
]

HOUND_HURT = [
    _ol("""
        ................
        ................
        ................
        ................
        ................
        ......4.4.......
        .....43434......
        .3..3333333.333.
        3..22222122223e.
        ..222222122222..
        ..22222222222tt.
        ..222..2222.....
        ..21...2221.....
        ..2.1..1.2.1....
        .2..1..1..2.1...
        ................
    """),
]

register("t7.hound.idle", art(*HOUND_IDLE, legend=HOUND, fps=2, note="xenohound, panting"))
register("t7.hound.move", art(*HOUND_MOVE, legend=HOUND, fps=10, note="xenohound run cycle"))
register("t7.hound.attack", art(*HOUND_ATTACK, legend=HOUND, fps=8, note="xenohound: coil, lunge-bite"))
register("t7.hound.hurt", art(*HOUND_HURT, legend=HOUND, note="xenohound recoil"))


# brute: a hulking knuckle-walker. Bone plates on the hump, forward horns, tiny
# ember eyes (neon_orange). Built from shaded forms so every frame shares one body.

BRUTE = {"0": "brute0", "1": "brute1", "2": "brute2", "3": "brute3", "4": "brute4",
         "a": "bone4", "b": "bone3", "B": "bone2", "d": "bone1", "e": "neon_orange", "m": "red1"}


def _ellipse(cx: float, cy: float, rx: float, ry: float, w: int = 24, h: int = 24) -> set:
    return {(x, y) for y in range(h) for x in range(w)
            if ((x + 0.5 - cx) / rx) ** 2 + ((y + 0.5 - cy) / ry) ** 2 <= 1.0}


def _box(x0: int, y0: int, x1: int, y1: int) -> set:
    return {(x, y) for y in range(y0, y1 + 1) for x in range(x0, x1 + 1)}


def _paint(c: Canvas, pts: set, light: str, main: str, dark: str) -> None:
    """One form lit from the top-left: top/left rim light, bottom rim dark."""
    for (x, y) in pts:
        if (x, y - 1) not in pts or (x - 1, y) not in pts and (x, y - 1) not in pts:
            ch = light
        elif (x, y + 1) not in pts or (x + 1, y + 1) not in pts:
            ch = dark
        else:
            ch = main
        c.set(x, y, ch)


def _brute(dx: int = 0, dy: int = 0, front: int = 0, hind: int = 0, head: tuple = (0, 0),
           arm_up: bool = False, flash: bool = False) -> Grid:
    """dx/dy move the upper body; front/hind (-1..1) swing the near limbs;
    head offsets the skull; arm_up raises the near fist for a swipe."""
    c = Canvas(24, 24)
    ox, oy = dx, dy
    # far limbs (darkest), behind the body
    _paint(c, _box(9 - hind, 17 + oy, 10 - hind, 21), "1", "1", "0")
    _paint(c, _box(13 + front, 17 + oy, 14 + front, 21), "1", "1", "0")
    # body mass + hump
    body = _ellipse(11.5 + ox, 13.0 + oy, 8.2, 5.2) | _ellipse(12.5 + ox, 10.5 + oy, 6.0, 4.2)
    _paint(c, body, "3", "2", "1")
    for (x, y) in body:  # belly shadow band
        if y >= 16 + oy and c.get(x, y) == "2":
            c.set(x, y, "1")
    # hind leg (near): thick thigh into a short shin
    thigh = _ellipse(6.0 + ox - hind * 0.5, 15.5 + oy, 2.6, 2.6)
    shin = _box(5 - hind, 17 + oy, 7 - hind, 21)
    _paint(c, thigh | shin, "3", "2", "1")
    # head: low, heavy brow, horns forward
    hx, hy = 19.2 + ox + head[0], 14.8 + oy + head[1]
    skull = _ellipse(hx, hy, 3.1, 2.7)
    _paint(c, skull, "3", "2", "1")
    ix, iy = int(hx), int(hy)
    c.set(ix + 1, iy - 1, "e")                      # ember eye under the brow
    c.set(ix, iy - 2, "4"); c.set(ix + 1, iy - 2, "4")
    c.set(ix + 2, iy + 1, "m"); c.set(ix + 1, iy + 1, "m")   # mouth line
    for (x, y) in ((ix + 1, iy - 3), (ix + 2, iy - 4), (ix + 2, iy - 5), (ix + 3, iy - 6)):
        c.set(x, y, "b")                            # near horn
    c.set(ix + 3, iy - 5, "a"); c.set(ix + 3, iy - 4, "B")
    for (x, y) in ((ix - 1, iy - 3), (ix - 1, iy - 4), (ix, iy - 5)):
        c.set(x, y, "B")                            # far horn
    # bone plates along the hump
    for (px, py, w) in ((6, 8, 2), (9, 6, 3), (13, 6, 3), (16, 8, 2)):
        for k in range(w):
            c.set(px + ox + k, py + oy, "a" if k == 0 else "b")
            c.set(px + ox + k, py + oy + 1, "B" if k == 0 else "d")
        c.set(px + ox + w // 2, py + oy - 1, "b")
    # near arm: a massive forelimb down to the knuckles (or raised for a swipe)
    if arm_up:
        arm = _box(15 + ox, 7 + oy, 17 + ox, 12 + oy) | _ellipse(17.5 + ox, 6.5 + oy, 2.0, 1.8)
    else:
        arm = (_box(15 + ox + front, 13 + oy, 17 + ox + front, 20)
               | _box(15 + front, 19, 18 + front, 21))
    _paint(c, arm, "4", "3", "1")
    g = shift(c.grid(), 0, 1)  # soles on row 22, outline on row 23 = the anchor row
    if flash:
        g = tuple(row.replace("2", "3") for row in g)
    return outline_grid(g, "k")


BRUTE_IDLE = [_brute(), _brute(dy=-1)]
BRUTE_MOVE = [
    _brute(front=1, hind=-1, dy=1),   # heavy contact, weight lands
    _brute(dy=0),                     # passing
    _brute(front=-1, hind=1, dy=1),   # other side lands
    _brute(dy=0),
]
BRUTE_ATTACK = [
    _brute(dx=-1, dy=-1, head=(-1, -1), arm_up=True),   # rears up, fist raised
    _brute(dx=1, dy=1, head=(1, 1), front=1),           # slams down, horns first
]
BRUTE_HURT = [_brute(dx=-1, head=(-1, -1), flash=True)]

register("t7.brute.idle", art(*BRUTE_IDLE, legend=BRUTE, fps=1.5, note="brute, heavy breathing"))
register("t7.brute.move", art(*BRUTE_MOVE, legend=BRUTE, fps=6, note="brute heavy stomp"))
register("t7.brute.attack", art(*BRUTE_ATTACK, legend=BRUTE, fps=6, note="brute: rear up, slam"))
register("t7.brute.hurt", art(*BRUTE_HURT, legend=BRUTE, note="brute recoil"))


# --- machines of the wrecks ---------------------------------------------------------
# drone: a floating steel sphere with a red armour cap and one big red lens.
# Its lowest pixel is row 12-13 (bob): rows 14-15 always stay empty, so it hovers
# over the renderer's ground shadow at the default bottom-centre anchor.

DRONE = {"s": "steel4", "S": "steel3", "t": "steel2", "T": "steel1",
         "r": "red3", "R": "red2", "q": "red1", "Q": "red0",
         "e": "neon_red", "E": "fire5", "o": "red1", "f": "fire3", "F": "fire4"}


def _drone(dy: int = 0, lean: int = 0, lens: str = "idle", light: bool = True, flame: int = 0) -> Grid:
    c = Canvas(16, 16)
    oy = dy
    hull = _ellipse(7.5 + lean, 5.5 + oy, 4.8, 4.3, 16, 16)
    _paint(c, hull, "s", "S", "t")
    for (x, y) in hull:  # red armour cap over the top half
        if y <= 4 + oy:
            c.set(x, y, "r" if (x, y - 1) not in hull or c.get(x - 1, y) == "." else "R")
        elif y == 5 + oy:
            c.set(x, y, "q")
    # side stabiliser fin
    for y in range(4 + oy, 8 + oy):
        c.set(2 + lean, y, "T")
    c.set(1 + lean, 5 + oy, "t"); c.set(1 + lean, 6 + oy, "T")
    # status lamp set into the cap
    c.set(6 + lean, 1 + oy, "e" if light else "Q")
    # the lens
    lx, ly = 10 + lean, 5 + oy
    for (x, y) in ((lx, ly), (lx + 1, ly), (lx, ly + 1), (lx + 1, ly + 1)):
        c.set(x, y, "e")
    c.set(lx - 1, ly, "T"); c.set(lx - 1, ly + 1, "T"); c.set(lx, ly - 1, "T"); c.set(lx + 1, ly - 1, "T")
    c.set(lx, ly + 2, "T"); c.set(lx + 1, ly + 2, "T")
    if lens == "blink":
        c.set(lx, ly, "o"); c.set(lx + 1, ly, "o")
    elif lens == "charge":
        c.set(lx + 1, ly, "E")
    elif lens == "fire":
        for (x, y) in ((lx, ly), (lx + 1, ly), (lx, ly + 1), (lx + 1, ly + 1)):
            c.set(x, y, "E")
        c.set(lx + 2, ly, "e"); c.set(lx + 2, ly + 1, "e")
    else:
        c.set(lx + 1, ly, "E")
    # thruster nozzle and flame under the hull
    c.set(7 + lean, 10 + oy, "T"); c.set(8 + lean, 10 + oy, "T")
    if flame:
        c.set(7 + lean, 11 + oy, "f" if flame == 1 else "F")
        c.set(8 + lean, 11 + oy, "F" if flame == 1 else "f")
    return outline_grid(c.grid(), "k")


DRONE_IDLE = [_drone(flame=1), _drone(dy=1, lens="blink", light=False, flame=2)]
DRONE_MOVE = [_drone(lean=1, flame=1), _drone(lean=1, dy=1, light=False, flame=2)]
DRONE_ATTACK = [_drone(lens="charge", flame=1), _drone(lean=-1, lens="fire", flame=2)]
DRONE_HURT = [_drone(lean=-1, dy=-1, lens="blink", light=False)]

register("t7.drone.idle", art(*DRONE_IDLE, legend=DRONE, fps=2, note="security drone hovering; lens blinks"))
register("t7.drone.move", art(*DRONE_MOVE, legend=DRONE, fps=4, note="security drone cruising"))
register("t7.drone.attack", art(*DRONE_ATTACK, legend=DRONE, fps=6, note="drone: lens charges, fires"))
register("t7.drone.hurt", art(*DRONE_HURT, legend=DRONE, note="drone knocked back"))


# android: a damaged humanoid from the wrecks. White station plating, a torn
# chest panel with live wires, a cracked face with one red eye.

ANDROID = {"a": "white", "p": "stat3", "P": "stat2", "Q": "stat1", "j": "steel1", "q": "steel2",
           "e": "neon_red", "E": "red1", "r": "red2", "y": "hazard", "z": "fire4"}

ANDROID_IDLE = [
    """
    ................
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    ....kkjjjkk.....
    ...kaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    ....kPkkPkkk....
    ....kPk.kPk.....
    ...kPPk.kPPk....
    ...kkkk.kkkk....
    """,
    # twitch: the head jerks, a spark jumps from the torn wires
    """
    ................
    ......kkkkk.....
    .....kaapppk....
    .....kppqqek....
    .....kPpPPPk....
    .....kkQPPk.....
    ....kkjjjkk.....
    ..zkaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    ....kPkkPkkk....
    ....kPk.kPk.....
    ...kPPk.kPPk....
    ...kkkk.kkkk....
    """,
]

ANDROID_MOVE = [
    """
    ................
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    ....kkjjjkk.....
    ...kaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    ...kPkkkPkkk....
    ..kPk...kPk.....
    .kPPk....kPPk...
    .kkkk....kkkk...
    """,
    """
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    ....kkjjjkk.....
    ...kaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    .....kPPkkkk....
    .....kPPk.......
    .....kQPk.......
    ....kPPPk.......
    ....kkkkk.......
    """,
    """
    ................
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    ....kkjjjkk.....
    ...kaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    ....kPkkkkPk....
    ....kPk..kPk....
    ...kPPk...kPPk..
    ...kkkk...kkkk..
    """,
    """
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    ....kkjjjkk.....
    ...kaappPPkk....
    ...kpyrjPkpk....
    ...kprjyPkPk....
    ...kPpPPPkjk....
    ....kjjjjkPk....
    .....kPPkkkk....
    .....kPQk.......
    .....kPPk.......
    .....kPPPk......
    .....kkkkk......
    """,
]

ANDROID_ATTACK = [
    # arm cocked back, eye flaring
    """
    ................
    .....kkkkk......
    ....kaapppk.....
    ....kppqqek.....
    ....kPpPPPk.....
    .....kQPPk......
    .kk.kkjjjkk.....
    kPjkkaappPPk....
    kPkkpyrjPkPk....
    .kkkprjyPkPk....
    ...kPpPPPPk.....
    ....kjjjjk......
    ....kPkkPk......
    ...kPk..kPk.....
    ..kPPk..kPPk....
    ..kkkk..kkkk....
    """,
    # strike: the arm driven straight out
    """
    ................
    ......kkkkk.....
    .....kaapppk....
    .....kppqqek....
    .....kPpPPPk....
    ......kQPPk.....
    .....kkjjjkkkkk.
    ....kaappPPjpPPk
    ....kpyrjPkkkkkk
    ....kprjyPk.....
    ....kPpPPPk.....
    .....kjjjjk.....
    ....kPkkkPk.....
    ...kPk...kPk....
    ..kPPk....kPPk..
    ..kkkk....kkkk..
    """,
]

ANDROID_HURT = [
    """
    ................
    ................
    ....kkkkk.......
    ...kaapppk......
    ...kppqqEk......
    ...kPpPPPk......
    ....kQPPk.z.....
    ...kkjjjkk......
    ..kaappPPkk.....
    ..kpyrjPkpk.....
    ..kprjyPkPk.....
    ..kPpPPPkjk.....
    ...kjjjjkPk.....
    ...kPkkPkkk.....
    ..kPPk.kPPk.....
    ..kkkk.kkkk.....
    """,
]

register("t7.android.idle", art(*ANDROID_IDLE, legend=ANDROID, fps=1.5, note="damaged android, twitching"))
register("t7.android.move", art(*ANDROID_MOVE, legend=ANDROID, fps=6, note="android stiff walk"))
register("t7.android.attack", art(*ANDROID_ATTACK, legend=ANDROID, fps=8, note="android: cock, strike"))
register("t7.android.hurt", art(*ANDROID_HURT, legend=ANDROID, note="android jolted, eye out"))


LIRA_PORTRAIT = """
    ........................
    ........kk..............
    .......krrkkkkkk........
    ......krryyyyyrrk.......
    .....krryyyrrrrrrk......
    ....krryrrrrrrrrrrk.....
    ....krrrrrrrrrrrrrrk....
    ...kRrrrrrrrRRrrrrrk....
    ...kRrrrrRRffffRrrrrk...
    ...kRRrrRffffffffRrrk...
    ...kRRrRfffffffffffk....
    ...kRRrRffFFfffFFffk....
    ...kRRRffekfffffekfk....
    ...kRRRfFffffffffFfk....
    ....kRRfFfffffFffffk....
    ....kRRkFfffffffffk.....
    .....kkkFffFkkkFffk.....
    ......kkFFfffffffk......
    ....kkkkkFFFFFFkkkkk....
    ...kslllkkFFFFkkWmmmk...
    ..kslllsssskkkkmWWmMmk..
    ..ksllsssssslkmmmcMMmk..
    .ksslssssssslkMmmmMMnk..
    .ksssssssssssknMMMMnnk..
"""
register("t7.lira.portrait", art(LIRA_PORTRAIT, legend=LIRA, note="HUD portrait"))
