"""Tau-7 life: the survivor, Lira and the fauna/machines of the planet.

Every actor faces RIGHT in a 3/4 side view (the renderer mirrors it for left)
and stands with its feet on the bottom row, so the default bottom-centre
anchor puts it on the tile's ground point."""

from __future__ import annotations

from ..pixelart import Grid, art, blank, grid, overlay
from ..registry import register


def _frame(body: str, *stamps: tuple[Grid, int, int]) -> Grid:
    """A body grid with parts (heads) stamped *under* it: the body's own pixels
    win, so an arm raised in front of the face is drawn over the head."""
    g = grid(body)
    w, h = len(g[0]), len(g)
    base = blank(w, h)
    for part, x, y in stamps:
        base = overlay(base, part, x, y)
    return overlay(base, g)


# --- the survivor ------------------------------------------------------------------
# orange survival suit, white helmet with a cyan visor, grey life-support pack

HERO = {
    "h": "grey4", "H": "grey3", "j": "white",       # helmet
    "v": "glowcyan", "V": "water3", "c": "cryst2",  # visor
    "s": "suit2", "S": "suit1", "l": "suit3",        # suit
    "b": "grey2", "B": "grey1",                      # backpack
    "g": "steel4", "G": "steel3",                    # gloves, boots
    "y": "hazard", "t": "steel3", "T": "steel2",     # multi-tool
    "u": "water4",                                   # a drop of water
    "r": "water1", "R": "water2", "x": "white",      # dead, cracked visor
    "q": "grey3", "Q": "grey2", "W": "water2",       # portrait: collar, visor depth
}

HELMET = grid("""
    ..kkkkk..
    .kjhhhhk.
    kjhhhhcvk
    khhhhvvvk
    kHhhhvVVk
    kkHHHHHkk
""")


def _hero(body: str, hx: int = 3, hy: int = 1) -> Grid:
    return _frame(body, (HELMET, hx, hy))


HERO_IDLE = [
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kSSkSkk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """),
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSslk...
        ...kkkSSSSkgk...
        .....kSSkSkk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """, hy=2),
]

HERO_WALK = [
    # contact: near leg forward, near arm swung back (tucked against the hip)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSlk....
        ..kbbksssSsk....
        ..kBBkSssSgk....
        ...kkkSSSkgk....
        ....kSSkksSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: body up 1px, near leg planted, far leg swinging through (knee forward)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kssSSkk....
        .....kssSSSk....
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
    # contact: far leg forward, near arm swung forward
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllssslk...
        ..kbbklsssSllk..
        ..kbbksssSSslk..
        ..kBBkSssSSkgk..
        ...kkkSSSSkkk...
        ....ksSkkSSk....
        ...kssk..kSSk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: body up 1px, far leg planted, near leg swinging through (knee forward)
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kbbksssSslk...
        ..kBBkSssSsSk...
        ...kkkSSSSkgk...
        .....kSSsskk....
        .....kSSsssk....
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
]

HERO_WORK = [
    # tool raised: bracing to strike / cut / tighten
    _hero("""
        ................
        .............k..
        ............kTk.
        ............ktk.
        ............kyk.
        ............kgk.
        ...........kslk.
        ..kbbkllssslksk.
        ..kbbklsssSSlk..
        ..kbbksssSSSk...
        ..kBBkSssSSk....
        ...kkkSSSSk.....
        ....kSSkkSSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # the stroke: tool driven down in front, body dips 1px
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSsllk..
        ...kkkSSSSkkgyk.
        ....kSSkkSSkkkTt
        ...kSSk..kssk.kk
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hy=2),
]

HERO_DRINK = [
    # down on one knee at the water's edge, scooping with the glove
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .kbbkllsssk.....
        .kbbklssSllk....
        .kBBksssSsslk...
        ..kkkSSSSkkslk..
        .kGSSSSkkssk.gk.
        .kkkkkkkkGgk.kk.
    """, hx=2, hy=4),
    # sitting up, lifting the water to the visor; a drop falls back
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ...........kgk..
        ..........kslk..
        ..........kslk..
        ..........kslku.
        .kbbkllssslk....
        .kbbklssSSk.....
        .kBBksssSSSk....
        ..kkkSSSSsssk...
        .kGSSSSkkssk....
        .kkkkkkkkGgk....
    """, hx=2, hy=4),
]

HERO_ATTACK = [
    # wind-up: rocked back, arm raised high in front of the helmet
    _hero("""
        ...........kk...
        ..........kggk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..........kslk..
        ..kbbkllsssslk..
        ..kbbklsssSSk...
        ..kbbksssSSSk...
        ..kBBkSssSSk....
        ...kkkSSSSk.....
        ....kSSkkSSk....
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hx=2),
    # strike: lunging forward, arm swung out level
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslkkkk.
        ..kbbklssSlllllg
        ..kbbksssSSSSSSg
        ..kBBkSssSSkkkkk
        ...kkkSSSSk.....
        ...kSSkkkSSk....
        ..kSSk...kssk...
        .kGgk.....kGgk..
        .kkkk.....kkkk..
    """, hx=4),
    # follow-through: arm carried down and forward, weight on the front leg
    _hero("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kk............
        ..kbbkllsslk....
        ..kbbklssSllk...
        ..kBBksssSSllk..
        ...kkkSSSSkSlk..
        ...kSSkkkSSkggk.
        ..kSSk...ksskkk.
        .kGgk.....kGgk..
        .kkkk.....kkkk..
    """, hx=4, hy=2),
]

HERO_HURT = [
    # knocked back: helmet thrown back, arm flung up, front foot off the ground
    _hero("""
        ................
        ................
        ................
        ................
        ...........kk...
        ..........kglk..
        ..........kslk..
        .kbbkllssslk....
        .kbbklsssSSk....
        .kbbksssSSSk....
        .kBBkSssSSk.....
        ..kkkSSSSSk.....
        ...kSSkkssk.....
        ..kSSk..kssk....
        .kGgk...kGgk....
        .kkkk...kkkk....
    """, hx=1, hy=2),
]

HERO_SLEEP = [
    # flat on the back, visor to the sky, one knee up; the chest rises and falls
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..kk......kjcvvk
    .kssk..kkkjhvvVk
    .kSsskklllkhhhhk
    .kGkSssssSkhhHHk
    .kGSSSSSSSSkbHkk
    ..kkkkkkkkkkkkk.
    """,
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..kk...kk.kjcvvk
    .kssk.klllkhvvVk
    .kSsskllllkhhhhk
    .kGkSssssSkhhHHk
    .kGSSSSSSSSkbHkk
    ..kkkkkkkkkkkkk.
    """,
]

HERO_DEAD = [
    # sprawled on the back, an arm flung out, the visor cracked and dark
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkkk.
    ..k.......kjrxrk
    .kGk...kkkjhxRRk
    .kGSk.kllskhhhhk
    ..kSSSSssSShhHHk
    ..kkkkSSSSkbbbkk
    ......kkkkkkkkk.
    """,
]

HERO_PORTRAIT = """
    ........................
    ..........kkkkk.........
    ........kkjjjhhkk.......
    .......kjjhhhhhhhk......
    ......kjhhhhhhhhhhk.....
    .....kjhhhhhhhhhhhhk....
    ....kjhhhhhhhhhhhhhhk...
    ....kjhhhhhhkkkkkkkkhk..
    ....khhhhhhkccvvvvvvkk..
    ...kjhhhhhkcvcvvvvvvVk..
    ...khhhhhhkvcvvvvvvvVk..
    ...khhhhhhkvvcvvvvvvVk..
    ...kHhhhhhkvvvvvvvvVVk..
    ...kHhhhhhkvvvvvvvVVWk..
    ...kHHhhhhHkVvvvVVVWkk..
    ....kHHhhhhHkkkkkkkkHk..
    ....kkHHHhhhhhhhhhHHk...
    ...kbkkHHHHHHHHHHHkk....
    ..kbbbkkqqqqqqqqqkkk....
    ..kbbbkQQkkkkkkkQQlkk...
    .kbbbbkllllsssssslssk...
    .kbbbbkllsssssyyssssSk..
    .kBbbbksssssssyysssSSk..
    .kBBBBksssssssssssSSSk..
"""

register("t7.hero.idle", art(*HERO_IDLE, legend=HERO, fps=2, note="the survivor, idle"))
register("t7.hero.walk", art(*HERO_WALK, legend=HERO, fps=8, note="the survivor, walking"))
register("t7.hero.work", art(*HERO_WORK, legend=HERO, fps=4, note="gather / craft / build / cook / repair"))
register("t7.hero.drink", art(*HERO_DRINK, legend=HERO, fps=2, note="kneeling at the water, scooping"))
register("t7.hero.attack", art(*HERO_ATTACK, legend=HERO, fps=10, note="overhead strike: raise, swing, follow through"))
register("t7.hero.hurt", art(*HERO_HURT, legend=HERO, note="recoil"))
register("t7.hero.sleep", art(*HERO_SLEEP, legend=HERO, fps=1, note="asleep on the back"))
register("t7.hero.dead", art(*HERO_DEAD, legend=HERO, note="fallen, visor cracked"))
register("t7.hero.portrait", art(HERO_PORTRAIT, legend=HERO, note="HUD portrait"))


# --- Lira ----------------------------------------------------------------------------
# the ship's engineer-cyberneticist: magenta jumpsuit, short copper hair with a
# cowlick, a chrome cybernetic arm with a cyan status light, a brown tool belt

LIRA = {
    "r": "hair_copper", "R": "dust3", "y": "tent3",          # hair
    "f": "skin3", "F": "skin2", "e": "ink2",                 # face
    "l": "lira3", "s": "lira2", "S": "lira1", "d": "lira0",  # jumpsuit
    "m": "chrome2", "M": "chrome1", "n": "chrome0", "W": "chrome3",  # cyber arm
    "c": "glowcyan", "C": "cryst1",                          # arm light (on / dim)
    "t": "tent1", "T": "tent0", "p": "tent2", "z": "gold2",  # tool belt
    "g": "grey3", "G": "grey2",                              # boots
    "v": "flora4", "V": "flora3", "u": "flora2", "U": "flora5", "x": "flora1",  # violet fiber
    "o": "tent2",                                            # sheaf cord
}

LIRA_HEAD = grid("""
    ..kk.....
    .krkkkk..
    .krryyrk.
    krryyrrrk
    kRrrrrffk
    kRrrrfefk
    .kRkkffFk
""")


def _lira(body: str, hx: int = 3, hy: int = 1) -> Grid:
    return _frame(body, (LIRA_HEAD, hx, hy))


LIRA_IDLE = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kSSSkkmmk..
        .....kSk.kSkk...
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """),
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kSssSSkmWk..
        ....ktpTzTkmCk..
        .....kSSSkkMnk..
        .....kSk.kSkmk..
        ....kGgk.kGgkk..
        ....kkkk.kkkk...
    """, hy=2),
]

LIRA_WALK = [
    # contact: near leg forward, chrome arm swung back across the hip
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkWk....
        ....kslssWmk....
        ....kSssmMck....
        ....ktpmMnk.....
        ....kSSmmkSk....
        ...kSSkkkssk....
        ..kGgk...kGgk...
        ..kkkk...kkkk...
    """),
    # passing: up 1px, near leg planted, far leg swinging through
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kssSSkmmk..
        .....kssSSSkk...
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
    # contact: far leg forward, chrome arm swung forward
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWWk.
        ....kSssSSSkmck.
        ....ktpTzTTkMnk.
        ....ksSkkSSkmmk.
        ...kssk..kSSkk..
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    # passing: up 1px, far leg planted, near leg swinging through
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmWk..
        ....kSssSSkmck..
        ....ktpTzTkMnk..
        .....kSSsskmmk..
        .....kSSsssk....
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, hy=0),
]

# the fiber sheaf she hauls on her back: stalk tips fan out above her shoulder
SHEAF = grid("""
    .k.k..
    kUkUk.
    kvUvk.
    kvVvVk
    .kVVvk
    .kVVuk
    .kuVuk
    .kuoVk
    .kuuVk
    .kxuuk
    ..kxuk
    ...kk.
""")


def _carry(body: str, bob: int = 0) -> Grid:
    return _frame(body, (SHEAF, 0, 1 + bob), (LIRA_HEAD, 4, 1 + bob))


LIRA_CARRY = [
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkWk...
        .....kslssoWmk..
        .....kSsoSmMck..
        .....ktoTmMnk...
        .....kSSmmkSk...
        ...kSSkkkssk....
        ..kGgk...kGgk...
        ..kkkk...kkkk...
    """),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSkmck.
        .....ktoTzTkMnk.
        .....kssSSSkmmk.
        .....kssSSSkkk..
        .....ksskGGk....
        ....kGggkkkk....
        ....kkkkk.......
    """, bob=-1),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSSkmck
        .....ktoTzTTkMnk
        ....ksSkkSSkkmmk
        ...kssk..kSSkkk.
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """),
    _carry("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        .....kslkkkkWk..
        .....kslssoSkmWk
        .....kSsoSSkmck.
        .....ktoTzTkMnk.
        .....kSSsssSkmmk
        .....kSSsssk.kk.
        .....kSSkggk....
        ....kGggkkkk....
        ....kkkkk.......
    """, bob=-1),
]

LIRA_WORK = [
    # reaching up into the flora with the chrome hand
    _lira("""
        ................
        ................
        ................
        ................
        ................
        .............kk.
        ............kWmk
        ...........kmMk.
        .....kslkkkmck..
        .....kslssSkk...
        .....kSssSSk....
        .....ktpTzTk....
        .....kSSkSSk....
        ....kSSk.kssk...
        ...kGgk...kGgk..
        ...kkkk...kkkk..
    """, hx=4),
    # leaning back, pulling a violet strand free
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ....kslkkkkWk.k.
        ....kslssSkmWkUk
        ....kSssSSkmcvvk
        ....ktpTzTkMnkk.
        ....kSSSkSSkk...
        ...kSSk..kssk...
        ..kGgk....kGgk..
        ..kkkk....kkkk..
    """, hx=3, hy=1),
]

LIRA_WAVE = [
    # both arms up and wide: "over here!"
    _lira("""
        ................
        .kk..........kk.
        kffk........kWmk
        .ksk........kmk.
        ..ksk......kmk..
        ...ksk.....kmk..
        ....ksk...kmMk..
        .....kk...kmck..
        ....kslkkkkkk...
        ....kslssSSk....
        ....kSssSSSk....
        ....ktpTzTTk....
        .....kSSkSSk....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
    """, hy=2),
    # arms swing in over the head, a little hop
    _lira("""
        ....kk....kk....
        ...kffk..kWmk...
        ...kfsk..kmMk...
        ....ksk..kmk....
        ....kkk..kck....
        ................
        ................
        ....kslkkkkWk...
        ....kslssSkmk...
        ....kSssSSkkk...
        ....ktpTzTk.....
        .....kSSkSk.....
        .....kSk.kSk....
        ....kGgk.kGgk...
        ....kkkk.kkkk...
        ................
    """, hy=1),
]

LIRA_SLEEP = [
    # curled on her side; she never switches the arm light off (afraid of the dark)
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ....kkkkk.krryk.
    ...kSssslkRrrrrk
    ..kSSsWmmckRrffk
    .kGSSSmMnkRRfeFk
    .kGkSSSSSSkkkkk.
    ..kkkkkkkkk.....
    """,
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ...kkkkkk.krryk.
    ..kSsssslkRrrrrk
    ..kSSsWmmckRrffk
    .kGSSSmMnkRRfeFk
    .kGkSSSSSSkkkkk.
    ..kkkkkkkkk.....
    """,
]

LIRA_DRINK = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..kslkkkkkk.....
        ..kSssSSkWmk....
        ..ktpTzkkmMck...
        .kGSSSkkssknmk..
        .kkkkkkkGgk.kk..
    """, hx=2, hy=5),
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..........kWk...
        .........kmMk...
        ..kslkkkkmck.v..
        ..kSssSSkkk.....
        ..ktpTzTSssk....
        .kGSSSkkssk.....
        .kkkkkkkGgk.....
    """, hx=2, hy=5),
]

LIRA_HURT = [
    _lira("""
        ................
        ................
        ................
        ................
        ................
        ............kk..
        ...........kWmk.
        ...........kmk..
        ....kslkkkkmck..
        ...kslssSSkkk...
        ...kSssSSSk.....
        ...ktpTzTTk.....
        ....kSSkssk.....
        ...kSSk.kssk....
        ..kGgk..kGgk....
        ..kkkk..kkkk....
    """, hx=2, hy=2),
]

LIRA_DEAD = [
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ...........kkk..
    ..kk......krryk.
    .kGk.kkkkkRrrrrk
    .kGSkslsnMkRrfFk
    ..kSSSSSMnmkkkk.
    ..kkkkkkkkkk....
    """,
]

register("t7.lira.idle", art(*LIRA_IDLE, legend=LIRA, fps=2, note="Lira, idle; the arm light pulses"))
register("t7.lira.walk", art(*LIRA_WALK, legend=LIRA, fps=8, note="Lira, walking"))
register("t7.lira.carry", art(*LIRA_CARRY, legend=LIRA, fps=8, note="Lira hauling a sheaf of violet fiber"))
register("t7.lira.work", art(*LIRA_WORK, legend=LIRA, fps=3, note="Lira gathering fiber: reach, pull"))
register("t7.lira.wave", art(*LIRA_WAVE, legend=LIRA, fps=4, note="stranded at her crash site, waving for help"))
register("t7.lira.sleep", art(*LIRA_SLEEP, legend=LIRA, fps=1, note="curled up, arm light left on"))
register("t7.lira.drink", art(*LIRA_DRINK, legend=LIRA, fps=2, note="kneeling at the water"))
register("t7.lira.hurt", art(*LIRA_HURT, legend=LIRA, note="recoil"))
register("t7.lira.dead", art(*LIRA_DEAD, legend=LIRA, note="fallen, arm light dead"))


# --- fauna -----------------------------------------------------------------------------
# hopper: a timid pale grazer. Long antenna-ears with pink bulbs, a big pink eye
# (glowpink: the only pixel that shows at night), strong hind legs.

HOPPER = {
    "a": "bone4", "b": "bone3", "B": "bone2", "d": "bone1",
    "p": "spore3", "P": "spore2", "e": "glowpink", "E": "spore2",
}

HOPPER_IDLE = [
    """
    ................
    ......kk..kk....
    .....kpPk.kpk...
    ......kak.kak...
    ......kak.kbk...
    .......kakbk....
    .......kabbkk...
    ......kaaabbbk..
    .....kkabbbaebk.
    ..kkkaaabbbbbbBk
    .kaakabbkBBBBBk.
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kbbbbbbBkkBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
    # the near ear flicks forward, listening
    """
    ................
    ......kk.....kk.
    .....kpPk...kpPk
    ......kak..kak..
    ......kak.kak...
    .......kakbk....
    .......kabbkk...
    ......kaaabbbk..
    .....kkabbbaebk.
    ..kkkaaabbbbbbBk
    .kaakabbkBBBBBk.
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kbbbbbbBkkBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
]

HOPPER_MOVE = [
    # crouch: coiled low, ears laid back
    """
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ..kkkk..........
    .kpPaakkk.......
    ..kkkbaaabkkk...
    ...kkaabbbbaebk.
    .kkabbbbbbbbbbBk
    kaakbbbbbkbbbBk.
    .kabbbbbbBkkBk..
    .kBBBBBBBBBkBBk.
    ..kkkkkkkkkkkkk.
    """,
    # airborne: stretched out, hind legs trailing, ears streaming
    """
    ................
    ................
    ................
    .kk.............
    .kpkkk..........
    ..kPaakkkkk.....
    ...kkkbaaaabkkk.
    ...kkkabbbbbaebk
    .kaakbbbbbbbbbBk
    ..kkbbbbbbbbBBk.
    .kBBBbbbbBBBBk..
    kBBkkkBBBkkBBk..
    kkk...kkk..kk...
    ................
    ................
    ................
    """,
    # landing on the front paws, haunch still up
    """
    ................
    ................
    ................
    ................
    ....kk..........
    ...kpPk.........
    ....kakkk.......
    .....kaaakk.....
    ....kkbbbaabk...
    .kk.kabbbbbabk..
    kaakabbbbbbbbekk
    .kkabbbbbbbbbbBk
    ..kBBbbbbbbBBBk.
    ...kkBBBBkkkBBk.
    .....kkkk...kBk.
    ............kkk.
    """,
]

HOPPER_HURT = [
    # flinching: ears pinned back, eye squeezed shut
    """
    ................
    ................
    ................
    ................
    ....kk..........
    ...kpPk.kk......
    ....kakkpPk.....
    .....kakkak.....
    .....kkabak.....
    .....kaabbbkk...
    ..kkkabbbbbEbk..
    .kaakabbkBBBBk..
    ..kkabbbbkbbBk..
    ..kabbbbbbkbBk..
    ..kBBBBBBBBkBBk.
    ...kkkkkkkkkkkk.
    """,
]

register("t7.hopper.idle", art(*HOPPER_IDLE, legend=HOPPER, fps=1.5, note="hopper, ear twitch"))
register("t7.hopper.move", art(*HOPPER_MOVE, legend=HOPPER, fps=8, note="hopper hop: crouch, airborne, land"))
register("t7.hopper.hurt", art(*HOPPER_HURT, legend=HOPPER, note="hopper flinch"))
