"""HUD icons (12x12) and event-log markers (8x8).

They sit next to text on a dark panel at x2, so every icon is one bold idea:
a clear silhouette, a 1px ``ink`` outline, 3 tones lit from the top-left and
at most one accent. Log markers use the colours of the TUI's EVENT_STYLE
(info grey, danger red, good green, brain cyan, death white on red, event
magenta, diary yellow, talk bright cyan, victory black on green)."""

from __future__ import annotations

from ..pixelart import art, flip_v, grid
from ..registry import register


def _icon(name: str, rows: str, legend: dict, outline: bool = True, note: str = "") -> None:
    register(f"ui.{name}", art(rows, legend=legend, outline="ink" if outline else None, note=note))


def _log(kind: str, rows: str, legend: dict, outline: bool = True) -> None:
    register(f"ui.log.{kind}", art(rows, legend=legend, outline="ink" if outline else None,
                                   note=f"event-log marker: {kind}"))


# =====================================================================================
# Tau-7 HUD
# =====================================================================================

_icon("hp", """
    ............
    .kkkk..kkkk.
    k3HH3kk3332k
    kHwH3333332k
    kHH33333332k
    k3333333322k
    .k33333322k.
    ..k333322k..
    ...k3221k...
    ....k21k....
    .....kk.....
    ............
""", {"H": "red4", "3": "red3", "2": "red2", "1": "red1"}, outline=False, note="health: heart")

_icon("satiety", """
    ............
    ...4433.....
    ..444333....
    .44433332...
    .44333322...
    .43333222...
    ..3332221...
    ...22221b...
    .......bbB..
    ......bbbBB.
    ......bbBBB.
    .......BB...
""", {"4": "brute4", "3": "brute3", "2": "brute2", "1": "brute1", "b": "bone4", "B": "bone2"},
    note="satiety: drumstick")

_icon("hydration", """
    .....kk.....
    ....k55k....
    ....k54k....
    ...k5443k...
    ...k5433k...
    ..k544332k..
    .k5w433332k.
    .k54333332k.
    .k43333322k.
    .k33333221k.
    ..k332211k..
    ...kkkkkk...
""", {"5": "water5", "4": "water4", "3": "water3", "2": "water2", "1": "water1"}, outline=False,
    note="hydration: water drop")

FLAME = """
    ......k.....
    .....k2k....
    ....k232k...
    ...k2332k...
    ..k233432k..
    ..k234432k..
    .k23445432k.
    .k23455432k.
    .k23455432k.
    .k22344322k.
    ..k223322k..
    ...kkkkkk...
"""
_icon("warmth", FLAME, {"2": "fire2", "3": "fire3", "4": "fire4", "5": "fire5"}, outline=False,
      note="warmth: flame")

_icon("energy", """
    ......kkkkk.
    .....k4443k.
    ....k4443k..
    ...k4443k...
    ..k44443kkk.
    .k44444443k.
    .kkkk4443k..
    ....k443k...
    ...k443k....
    ...k43k.....
    ..k3k.......
    ..kk........
""", {"4": "neon_yellow", "3": "gold1"}, outline=False, note="energy: lightning bolt")

_icon("day", """
    .....kk.....
    ..k.k55k.k..
    .k5kkkkkk5k.
    ..kk5544kk..
    .kk554444kk.
    k5k544443k4k
    k4k444433k4k
    .kk444333kk.
    ..kk4333kk..
    .k4kkkkkk4k.
    ..k.k44k.k..
    .....kk.....
""", {"5": "fire5", "4": "fire4", "3": "fire3"}, outline=False, note="daytime: sun")

_icon("night", """
    ...kk....k..
    ..k54k..kSk.
    .k54k..kSwSk
    k544k...kSk.
    k543k....k..
    k543k.......
    k5443k......
    k54443kkkk..
    k444443333k.
    .k4433332k..
    ..k33322k...
    ...kkkkk....
""", {"5": "bone4", "4": "sand4", "3": "sand3", "2": "sand2", "S": "white"}, outline=False,
    note="night: crescent moon and a star")

_icon("power", """
    ....kkkk....
    ..kkk33kkk..
    .k44444443k.
    .k4GGGGGG3k.
    .k4gggggg3k.
    .k42222223k.
    .k4GGGGGG3k.
    .k4gggggg3k.
    .k42222223k.
    .k4GGGGGG3k.
    .k43333332k.
    ..kkkkkkkk..
""", {"4": "chrome2", "3": "chrome1", "2": "chrome0", "G": "glowlime", "g": "hound3"}, outline=False,
    note="pod battery charge")

_icon("heater", """
    ..k...k...k.
    .kfk.kfk.kfk
    kfk.kfk.kfk.
    .kfk.kfk.kfk
    kfk.kfk.kfk.
    kkkkkkkkkkkk
    k4444444443k
    k4FFFFFFFF3k
    k4gggggggg3k
    k4EEEEEEEE3k
    k3333333332k
    kkkkkkkkkkkk
""", {"f": "fire3", "4": "chrome2", "3": "chrome1", "2": "chrome0", "F": "fire4", "E": "fire3",
      "g": "grey0"}, outline=False, note="pod heater: glowing coils, heat waves")

_icon("fault", """
    .........cc.
    ........ccC.
    .......ccC..
    ......oo....
    ..y..y..y...
    ...yywwyy...
    ....ywwy....
    ...yywwyy...
    ..y.oo..y...
    ..ccC.......
    .ccC........
    .cC.........
""", {"c": "grey3", "C": "grey1", "o": "ore1", "y": "neon_yellow", "w": "white"},
    note="pod fault: severed cable sparking")

_icon("beacon", """
    ..k..kk..k..
    .kakkRrkkak.
    kak.kRrk.kak
    kak.kmMk.kak
    .kakkmMkkak.
    ..k.kmMk.k..
    ....kmMk....
    ....kmMk....
    ....kmMk....
    ....kmMk....
    ...kmmMMk...
    ..kmkkkkMk..
""", {"a": "cryst1", "R": "red3", "r": "red2", "m": "grey3", "M": "grey2"}, outline=False,
    note="distress beacon: mast, red light, radio waves")

_icon("shuttle", """
    .....kk.....
    ....kRrk....
    ...kRRrrk...
    ...kWWWSk...
    ...kWccSk...
    ...kWcCSk...
    ...kWWWSk...
    ..kkWWWSkk..
    .kRkWWSSkrk.
    .kRRkkkkrrk.
    .kkkkFFkkkk.
    ....kEEk....
""", {"R": "red3", "r": "red2", "W": "white", "S": "stat2", "c": "glowcyan", "C": "cryst0",
      "F": "fire4", "E": "fire3"}, outline=False, note="rescue shuttle")

_icon("weapon", """
    ..........w.
    .........wcC
    ........wcC.
    .......wcC..
    ......wcC...
    ..g..wcC....
    ...gwcC.....
    ....gC......
    ...p5gg.....
    ..p53..g....
    .p53........
    .33.........
""", {"w": "chrome3", "c": "chrome2", "C": "chrome1", "g": "steel4", "p": "flora4", "5": "flora3",
      "3": "flora2"}, note="weapon: blade")

_icon("light", """
    ............
    ............
    ..........BB
    .....kkk.BbB
    .kkkkhhLbbbB
    k4444hcLbbbb
    k3o33hcLbbbb
    k2222hcLbbbb
    .kkkkhcLbbbB
    .....kkk.BbB
    ..........BB
    ............
""", {"4": "steel4", "3": "steel3", "2": "steel2", "o": "podorange", "h": "chrome2", "c": "chrome1",
      "L": "fire5", "b": "win_warm:130", "B": "win_warm:60"}, outline=False, note="light: flashlight beam")

_icon("companion", """
    ...kkkkkk...
    ..kLHHHHHk..
    .kLHHHHHHhk.
    .kHHssssHhk.
    .kHssssssHk.
    .kHsessesHk.
    .kHbssssbHk.
    .kHsssmssHk.
    .kHHssssHHk.
    .kHHkkkkHHk.
    ..kkVVVVkk..
    ...kkkkkk...
""", {"L": "tent3", "H": "hair_copper", "h": "rust2", "s": "skin3", "e": "ink", "b": "blush",
      "m": "skin1", "V": "lira3"}, outline=False, note="Lira: copper hair, magenta suit")

_icon("trust", """
    ............
    ............
    .oooo.......
    oOOOOo......
    OO..OvvvV...
    OO..vVVVVV..
    OO..vV.OVV..
    .OOOOOoOVV..
    ..ooovVVVV..
    .....VVVV...
    ............
    ............
""", {"o": "suit4", "O": "suit3", "v": "lira4", "V": "lira3"}, note="trust: two linked rings (survivor + Lira)")

_icon("tension", """
    ....k.......
    ...krk......
    ...krrk.....
    ..krkrk.....
    ..krkrk.....
    kkkrkrk.....
    ooork.krkkoo
    kkk..krkrkkk
    .....krkrk..
    .....krkrk..
    ......krk...
    .......k....
""", {"r": "red3", "o": "fire3"}, outline=False, note="director tension: pulse wave")

_icon("warning", """
    .....kk.....
    ....kjyk....
    ....kjyk....
    ...kjyyyk...
    ...kjkkyk...
    ..kjykkyyk..
    ..kjykkyyk..
    .kjyykkyyYk.
    .kjyyyyyyYk.
    kjyyykkyyyYk
    kYYYYYYYYYYk
    kkkkkkkkkkkk
""", {"j": "jacket3", "y": "hazard", "Y": "hazard_dark"}, outline=False, note="warning triangle")

_icon("threat", """
    ........r..r
    .......r..rr
    ......rr.rr.
    .....rr.rr.r
    ....rr.rr.rr
    ...rr.rr.rr.
    ..rr.rr.rr..
    ..r.rr.rr...
    ...rr.rr....
    ...r.rr.....
    .....r......
    ............
""", {"r": "red3"}, note="threat: claw marks")

_icon("goal", """
    .kk.........
    kpPkkkkkkkk.
    kpPjjjjjjjOk
    kpPooooooOk.
    kpPoooooOk..
    kpPooooooOk.
    kpPOOOOOOOOk
    kpPkkkkkkkk.
    kpPk........
    kpPk........
    kpPk........
    kkkk........
""", {"p": "grey4", "P": "grey2", "j": "suit4", "o": "suit3", "O": "suit2"}, outline=False,
    note="goal: flag")

_icon("thought", """
    ..kkk.kkkk..
    .kWWWkWWWck.
    kWWWCCWCCcck
    kWkCCkCCkCck
    kCCCCCCCCcck
    .kCCCCCcccK.
    ..kkkkkkkk..
    ..kWck......
    ..kcck......
    .k.kk.......
    kWk.........
    .k..........
""", {"W": "white", "C": "cryst2", "c": "cryst1"}, outline=False, note="thought bubble")

_icon("diary", """
    ............
    .kkkkkkkkkk.
    kSjjjjjjjjPk
    kSjJJJJJJJPk
    kSjJllllJJpk
    kSjJLLLLJJPk
    kSjJllllJJpk
    kSjJJJJJJJPk
    kSjJJJJJJIpk
    kSIIIIIIIIPk
    kkkkkkkRkkkk
    .......Rk...
""", {"S": "jacket0", "j": "jacket3", "J": "jacket2", "I": "jacket1", "l": "bone4", "L": "bone2",
      "P": "bone4", "p": "bone3", "R": "red2"}, outline=False, note="diary: book")

_icon("brain", """
    ....p..p....
    ....p..p....
    ..kkkkkkkk..
    ..k444443k..
    ppk4cccc3kpp
    ..k4cWWc3k..
    ..k4cWWc3k..
    ppk4cccc3kpp
    ..k433332k..
    ..kkkkkkkk..
    ....p..p....
    ....p..p....
""", {"p": "chrome2", "4": "steel3", "3": "steel2", "2": "steel1", "c": "glowcyan", "W": "cryst2"},
    outline=False, note="AI brain: processor chip")

_icon("storage", """
    ............
    .kkkkkkkkkk.
    k5555555554k
    k4444444443k
    kkkkkkkkkkkk
    k3233yy3322k
    k3233YY3322k
    k3233333322k
    k3233333322k
    k2122222211k
    kkkkkkkkkkkk
    ............
""", {"5": "steel5", "4": "steel4", "3": "steel3", "2": "steel2", "1": "steel1", "y": "podorange",
      "Y": "suit1"}, outline=False, note="pod storage crate")

SKULL = """
    ............
    ...kkkkkk...
    ..kWWWWWBk..
    .kWWWWWWWBk.
    kWWWWWWWWWBk
    kWWkkWWkkWBk
    kWWkkWWkkWBk
    .kWWWkkWWBk.
    ..kWWWWWBk..
    ..kWkWkWBk..
    ...kkkkkk...
    ............
"""
_icon("skull", SKULL, {"W": "bone4", "B": "bone3"}, outline=False, note="skull")

# --- director phases: one family of tension graphs ------------------------------------------------------
_icon("phase.calm", """
    ............
    ............
    ............
    .kk....kk...
    kLLk..kLLk..
    LllLkkLllLkk
    lkklLLlkklLL
    k..kllk..kll
    ....kk....kk
    ............
    ............
    ............
""", {"L": "grey4", "l": "grey3"}, outline=False, note="director phase: calm (затишшя)")

RISING = """
    ............
    .....jjjjjj.
    ......jyyyy.
    .......yyyy.
    ......yyyyY.
    .....yyy.YY.
    ....yyy...Y.
    ...yyy......
    ..yyy.......
    .yyY........
    .yY.........
    ............
"""
_icon("phase.rising", RISING, {"j": "jacket3", "y": "hazard", "Y": "hazard_dark"},
      note="director phase: rising (наростання)")

_icon("phase.peak", """
    ............
    .....yy.....
    ....RyyR....
    ....Rrrr....
    ...RR..rr...
    ...RR..rr...
    ..RR....rr..
    ..RR....rr..
    .RR......rr.
    RR........rr
    ............
    ............
""", {"y": "fire4", "R": "red4", "r": "red3"}, note="director phase: peak (пік)")

register("ui.phase.relief", art(flip_v(grid(RISING)), legend={"j": "neon_green_dim", "y": "neon_green",
                                                               "Y": "neon_green_dim"},
                                outline="ink", note="director phase: relief (перепочинок)"))


# =====================================================================================
# City HUD
# =====================================================================================

_icon("nuyen", """
    ...333322...
    ..33222222..
    .3D222222D1.
    .32D2222D21.
    .322DDDD221.
    .3DDDDDDDD1.
    .3222DD2221.
    .3DDDDDDDD1.
    .3222DD2221.
    .3222DD2211.
    ..22222211..
    ...211111...
""", {"3": "gold3", "2": "gold2", "1": "gold1", "D": "gold0"}, note="nuyen: gold coin")

_icon("debt", """
    ............
    .3322.......
    3....2......
    3....2......
    3....2B.....
    .322BB2.....
    ....BB.3322.
    .....B3....2
    ......3....2
    ......3....2
    .......2221.
    ............
""", {"3": "chrome3", "2": "chrome1", "1": "chrome0", "B": "chrome2"}, note="debt: chain links")

_icon("essence", """
    .a..........
    .....WV.....
    ....WVVv....
    ...WVVvvu..a
    ..WVVVvvuu..
    ..VVVVvuuU..
    ..vvvvuuUU..
    ...vvuuUU...
    ....uuUU....
    .a...UU.....
    ..........a.
    ............
""", {"W": "white", "V": "glowviolet", "v": "flora4", "u": "flora3", "U": "flora2",
      "a": "glowviolet:150"}, note="essence: soul crystal")

_icon("heat", """
    ......k.....
    .....k2k....
    ....k232k...
    ...k2332k...
    ..k233432k..
    ..k2kkkk2k..
    .k2kwrrwk2k.
    .k23kkkk32k.
    .k23455432k.
    .k22344322k.
    ..k223322k..
    ...kkkkkk...
""", {"2": "red2", "3": "fire2", "4": "fire3", "5": "fire4", "w": "white", "r": "red3"}, outline=False,
    note="district heat: a watching flame")

_icon("ship", """
    ............
    ............
    ............
    ...Hm.......
    ..HHmmm.....
    .EmmmmmCcc..
    EemmmmmmmmH.
    .Ehhhhhhhh..
    ...hh.......
    ............
    ............
    ............
""", {"H": "chrome3", "m": "chrome2", "h": "chrome1", "C": "glass3", "c": "neon_cyan", "E": "fire4",
      "e": "fire5"}, note="the runner's ship")

_icon("fuel", """
    ............
    ..HHH..SS...
    ..H.H..SS...
    .jjjjjjjjjR.
    .RdRRRRRRdr.
    .RRdRRRRdRr.
    .RRRdRRdRRr.
    .RRRRddRRRr.
    .RRRRddRRRr.
    .RRRdRRdRRr.
    .rrrrrrrrrr.
    ............
""", {"H": "red2", "S": "grey3", "j": "red3", "R": "red2", "r": "red1", "d": "red1"},
    note="ship fuel: jerrycan")

_icon("hull", """
    ............
    .5544443322.
    .5o44443o32.
    .5444443322.
    .5444443322.
    .5444443322.
    ..44444332..
    ..44444332..
    ...444332...
    ....4433....
    .....43.....
    ............
""", {"5": "steel5", "4": "steel4", "3": "steel3", "2": "steel2", "o": "steel2"},
    note="ship hull: armoured shield")

_icon("contract", """
    ............
    ............
    .LLLLLTTLLL.
    .LLLLLTTLLL.
    .eeeeeTTeee.
    .mmmmmTTmmd.
    .mmmmmTTmmd.
    .mwwwmTTmmd.
    .mwllmTTmmd.
    .mmmmmTTmmd.
    .dddddttddd.
    ............
""", {"L": "sand4", "e": "sand1", "m": "sand2", "d": "sand1", "T": "bone4", "t": "bone3", "w": "white",
      "l": "grey2"}, note="courier contract: parcel")

_icon("delinquent", """
    ............
    ...443322...
    ..44322222..
    .4332ww2221.
    .4322ww2221.
    .3222ww2221.
    .3222ww2221.
    .3222222221.
    .3222ww2211.
    ..22222211..
    ...211111...
    ............
""", {"4": "red4", "3": "red3", "2": "red2", "1": "red1", "w": "white"}, note="overdue payment")

_icon("evicted", """
    .....rr.....
    ....rrrR....
    ...rrrrRR...
    ..rrrrrRRR..
    .XXrrrrRRXX.
    ..XXcccXXc..
    ..cXXcXXcC..
    ..ccXXXXcC..
    ..cccXXccC..
    ..ccXXXXcC..
    ..cXXddXXC..
    .XX.....XX..
""", {"r": "rust3", "R": "rust2", "c": "conc3", "C": "conc2", "d": "leather3", "X": "neon_red"},
    note="evicted: house crossed out")

_icon("race", """
    ............
    ....ssss....
    ...ssssS....
    ...sssSS....
    ...ssSSS....
    ....SSS.....
    .....S......
    ..jjjjjjJ...
    .jjjjjjJJJ..
    .jjjjjJJJJ..
    .jjjjJJJJJ..
    ............
""", {"s": "skin4", "S": "skin2", "j": "jacket2", "J": "jacket1"}, note="metatype: person bust")

_icon("location", """
    ....4433....
    ...443322...
    ..44322222..
    ..432ww221..
    ..322ww221..
    ..32222221..
    ...222221...
    ...222211...
    ....2211....
    ....2211....
    .....11.....
    ............
""", {"4": "red4", "3": "red3", "2": "red2", "1": "red1", "w": "white"}, note="location: map pin")

_icon("rep.fixers", """
    ............
    ............
    ....wwww....
    ..wwCccCww..
    .wwCckkcCbb.
    .wwckkWkcbb.
    ..wwCccCbb..
    ....bbbb....
    ............
    ............
    ............
    ............
""", {"w": "white", "b": "bone3", "C": "neon_cyan_dim", "c": "neon_cyan", "W": "white"},
    note="reputation with fixers: the watching eye")

_icon("rep.vendors", """
    ....s..s....
    .....ss.....
    .....rr.....
    ....SSSS....
    ...SSSSsS...
    ..SSSDDSss..
    .SSSDSSSsss.
    .SSSSDSSsss.
    .SSSSSDSsss.
    .SSSDDSSsss.
    ..sssssssS..
    ............
""", {"S": "sand3", "s": "sand2", "r": "rust2", "D": "gold0"}, note="reputation with vendors: money bag")

_icon("rep.gangs", """
    ..........q.
    ......n.qPq.
    ....ccc...q.
    ....ccc.....
    ...CCCCC....
    ...pPPPp....
    ...pPPPp....
    ...qqqqq....
    ...pPPPp....
    ...pPPPp....
    ...CCCCC....
    ............
""", {"n": "grey3", "c": "grey3", "C": "chrome2", "p": "neon_pink", "P": "neon_pink_dim",
      "q": "neon_pink"}, note="reputation with gangs: spray can")

# --- controls ------------------------------------------------------------------------------------------------
_icon("speed", """
    ............
    ............
    .W....W.....
    .WW...WW....
    .WWW..WWW...
    .WWWW.WWWW..
    .ggggWggggW.
    .ggg..ggg...
    .gg...gg....
    .g....g.....
    ............
    ............
""", {"W": "white", "g": "grey3"}, note="speed: fast-forward")

_icon("pause", """
    ............
    ............
    ..WWW..WWW..
    ..WWg..WWg..
    ..WWg..WWg..
    ..WWg..WWg..
    ..WWg..WWg..
    ..WWg..WWg..
    ..Wgg..Wgg..
    ..ggg..ggg..
    ............
    ............
""", {"W": "white", "g": "grey3"}, note="pause")


# =====================================================================================
# Event-log markers (8x8)
# =====================================================================================

_log("info", """
    ........
    ........
    ...44...
    ..4433..
    ..4332..
    ...32...
    ........
    ........
""", {"4": "grey4", "3": "grey3", "2": "grey2"})

_log("danger", """
    ...RR...
    ...Rr...
    ...Rr...
    ...Rr...
    ...rr...
    ........
    ...rr...
    ........
""", {"R": "red4", "r": "red3"})

_log("good", """
    ........
    ......G.
    .....Gg.
    .G..Gg..
    .GgGg...
    ..Gg....
    ...g....
    ........
""", {"G": "neon_green", "g": "neon_green_dim"})

_log("brain", """
    ........
    ..CC.C..
    .CWCCCc.
    .CCCCcc.
    ..Cccc..
    ........
    .C......
    ........
""", {"W": "white", "C": "glowcyan", "c": "cryst1"})

_log("death", """
    .rrrrrr.
    rrWWWWrr
    rWkWWkWr
    rWkWWkWr
    rrWWWWrr
    rrWkWkrr
    RrrrrrrR
    .RRRRRR.
""", {"r": "red2", "R": "red1", "W": "white"})

_log("event", """
    ...kk...
    ..kppk..
    ..kpPk..
    .kppPPk.
    .kpkkPk.
    kppkkPPk
    kpppPPPk
    kkkkkkkk
""", {"p": "neon_pink", "P": "neon_pink_dim"}, outline=False)

_log("diary", """
    ........
    .SjjjjP.
    .SjllJP.
    .SjJJJp.
    .SjllJP.
    .SJJJJp.
    .SIIIIP.
    ........
""", {"S": "jacket0", "j": "jacket3", "J": "jacket2", "I": "jacket1", "l": "bone4", "P": "bone4",
      "p": "bone3"})

_log("talk", """
    ........
    .WCCCCc.
    .CkCkCc.
    .CCCCcc.
    ..Cccc..
    ..Cc....
    ..C.....
    ........
""", {"W": "white", "C": "neon_cyan", "c": "cryst1"})

_log("victory", """
    ...GG...
    ...GG...
    GGGGgGgg
    .GGGggg.
    ..GGgg..
    .GGg.gg.
    .Gg...g.
    ........
""", {"G": "neon_green", "g": "neon_green_dim"})
